### ISSUE TITLE
Check tile repository initialization

### ISSUE THREAD

**Issue by Dade916** [LuxCoreRender/LuxCore#10]
https://forums.luxcorerender.org/viewtopic.php?f=4&t=12

**Comment by Dade916** [comment]
The source of the problem is in having a single small film for each tile (instead of one single big film). So the cost of allocating a tile, at the startup, is not trivial.
Once we had one big film but it was changed to be able to render the same tile multiple times (for instance, when you have only one tile to render, LuxCore still uses all CPU cores available instead of running with a single thread). So it is a trade-off of between memory/startup costs and running speed.

I have alleviated the problem by supporting multi-threading in the initialization. The initialization of your scene, now takes 3.15 seconds:

[code]
[LuxCore][0.726] Configuring 12 CPU render threads
[LuxCore][3.880] Tiles initialization time: 3.15 secs
[LuxCore][4.008] Film OpenCL image pipeline
[/code]

instead of 21.13 seconds:

[code]
[LuxCore][0.715] Configuring 12 CPU render threads
<The old code miss the "Tiles initialization time" message>
[LuxCore][21.840] Film OpenCL image pipeline
[/code]

It is now about 6 times as expected on six core + hyper-threading.

**Comment by Theverat** [comment]
That seems good enough for now.
I can also set the soft_min of the tile size property in BlendLuxCore to something higher than 8 so users don't stumble upon this problem too often.

**Comment by Theverat** [comment]
By the way, about your commit:
```
	#pragma omp parallel for
	for (
			// Visual C++ 2013 supports only OpenMP 2.5
#if _OPENMP >= 200805
			unsigned
#endif
			int i = 0; i < size; ++i)
```
Couldn't you replace that with the following code?
```
#if _OPENMP >= 200805
	typedef unsigned int itertype;
#else
	// Visual C++ 2013 supports only OpenMP 2.5
	typedef int itertype;
#endif

for (itertype i = 0; i < size; ++i) {
```
(looks more readable to me)

**Comment by Dade916** [comment]
It may be also better to define itertype in a single place but the code is there only as workaround for a VS2013 limitation: the support  only for 2008 (!) OpenMP.

I assume it can be removed as soon as we move to a newer OpenMP version.
