### ISSUE TITLE
disable image convergence test

### ISSUE THREAD

**Issue by nyers33** [LuxCoreRender/LuxCore#101]
How can one disable the convergence test? I tried with batch.halttreshold "-1.0" flag, but it didn't have any effect.
`./bin/luxcoreconsole sceneName -D batch.halttime 120 -D batch.halttreshold -1.0`
[luxcore_bigmonkey_bigmonkey_GPU.log](https://github.com/LuxCoreRender/LuxCore/files/1985069/luxcore_bigmonkey_bigmonkey_GPU.log)
It seems that with PATHOCL gpu rendering only (and without hybrid rendering) a CPU thread is constantly at 100% usage - does covergence test use this thread?

version: luxcorerender-v2.0-linux64-opencl-sdk
os: Ubuntu 16.04.4 LTS

It would be great to turn off this test entirely so the convergence rate is not calculated - not just disable it as a halt condition. 
Thanks!

**Comment by nyers33** [comment]
Just a quick follow up.
@Dade916 [suggested](https://forums.luxcorerender.org/viewtopic.php?f=5&t=83&p=1973&hilit=convergence#p1973) that "batch.haltthreshold.stoprendering.enable" should be set to false. It doesn't work or I use the flags incorrectly. 
[luxcore_LuxMark-LuxBall_render_GPU.log](https://github.com/LuxCoreRender/LuxCore/files/1985115/luxcore_LuxMark-LuxBall_render_GPU.log)

**Comment by nyers33** [comment]
Thanks for the help!

Actually, I would like to add LuxCoreRender to our GPU benchmark suite and I'm looking for ways to measure the performance of the renderer - with as little variance as possible.
My idea is / was to replicate the scenes from the popular LuxMark-v3.1 suite - the scenes are rendered for 2mins and a score is provided (K samples / sec).

As a side note: slg4 shows the very same behavior, a thread is locked at 100% usage. Upped the resolution to check whether it can stress the GPU more, but the scores didn't change.

It seems that setting the _batch.halttreshold.warmup_ and _batch.halttreshold.step_ has no effect.
`./bin/luxcoreconsole "scenes/LuxMark-LuxBall/render.cfg" -D batch.halttime 120 -D batch.halttreshold -1.0 -D batch.halttreshold.warmup 16384 -D batch.halttreshold.step 16384 -D batch.halttreshold.stoprendering.enable 0 -D renderengine.type "PATHOCL" -D opencl.platform.index -1 -D opencl.cpu.use 0 -D opencl.gpu.use 1 -D opencl.native.threads.count 0`

Log file for the run: [luxcore_LuxMark-LuxBall_GPU_set_warmup.log](https://github.com/LuxCoreRender/LuxCore/files/1987459/luxcore_LuxMark-LuxBall_GPU_set_warmup.log)

As you suggested, increasing the resolution somewhat solves the problem - convergence test kicks in much later.

**Comment by Dade916** [comment]
Ahah, sorry, I was the one to lost it in my previous post.

**Comment by nyers33** [comment]
Sorry for the typo! Thanks for the help!
