### ISSUE TITLE
Error 0xc00007b in executables

### ISSUE THREAD

**Issue by nathanmiguel123** [LuxCoreRender/LuxCore#107]
I have this error at the time of starting the executable already compiled, the compilation was 100% ok but when I run the app it opens but of this error as in the image below, which was the same as I had in the radeon pro render repository.

https://gyazo.com/e3d861a95aa693601d6ef7f2bc3ce318

**Comment by nathanmiguel123** [comment]
I believe it is the lack of certain dlls in system 64 like msvcp100d, because I have these and all the others in system 32.

**Comment by Dade916** [comment]
You should get a different error if it is a matter of a missing DLL.

Do the official binaries from https://luxcorerender.org/download/ work ?

Dow your OpenCL installation work ? Have you tried to run LuxMark to check if OpenCL work fine ?

**Comment by nathanmiguel123** [comment]
yes

**Comment by Dade916** [comment]
You need a bit to elaborate the answer.

**Comment by nathanmiguel123** [comment]
Already the sdk, it seems that I've been able to find a solution, I'll see if the version for VS is the same.

![sem titulo](https://user-images.githubusercontent.com/29849613/40125692-e6e2a876-5901-11e8-85dd-8a1989b42695.png)

**Comment by nathanmiguel123** [comment]
good as I predicted it was 4 dll shortage where the executable directory was. I solved the problem thanks for the support

**Comment by Dade916** [comment]
Ok, good.
