### ISSUE TITLE
LuxCore v1.5 vs LuxCoreRender v2.0 - performance, convergence

### ISSUE THREAD

**Issue by nyers33** [LuxCoreRender/LuxCore#112]
I would like to add the new LuxCoreRender to our benchmark suite. As LuxMark is / was a pretty popular tool I thought I will replicate the same scenes. Scenes for LuxCore v1.5 are from the LuxMark v3.1 binaries, LuxCoreRender scenes are from the repo.

LuxMark runs for 2 mins and provides a score based on "Average samples / sec". 2 minute run time is more or less enough for reach convergence.

LuxCore v1.5 reported values is oscillating a bit even after convergence - I checked the source and it seems that the reported "Average samples / sec" is an overall average not an average over a 1 sec interval, so I don't know the reason for this.
LuxCoreRender v2.0 on the other hand has a much smoother run but takes considerably more time to converge.
![luxcore_luxmark-mic_3min](https://user-images.githubusercontent.com/37452404/40205404-34af09f2-5a2c-11e8-9372-b6b3b6c73336.png)
![luxcore_luxmark-mic_6min](https://user-images.githubusercontent.com/37452404/40205406-380d7660-5a2c-11e8-80aa-17cf6ac4926b.png)
![slg4_mic](https://user-images.githubusercontent.com/37452404/40205410-3b66159c-5a2c-11e8-8ee5-35518400cb24.png)
3 consecutive run is overlayed on each single plot - the results match perfectly. My score is the average of the last 10 reported "Average samples / sec" value.
LuxCore v1.5 was run for 3 mins. LuxCoreRender v2.0 was run for 3 mins and 6 mins to highlight the slower convergence.

I haven't set OpenCL C compiler flags for LuxCore v1.5. It seems that LuxCoreRender v2.0 processes the same command line options but I'm not sure it has an effect on OpenCL compilation.

Any thoughts? :)
[slg4_luxcore.zip](https://github.com/LuxCoreRender/LuxCore/files/2014833/slg4_luxcore.zip)

**Comment by Dade916** [comment]
When you talk of "covergence", you mean score convergence, not about rendering quality speed, right ?

Anyway, I can explain the results you are observing: the rendering runs on the GPU and the result is periodically downloaded by the CPU, so the avg. samples per pixel is updated only at the time the film is downloaded while the time still move on for the CPU. This will make the score suddenly jump once the film is downloaded and it will slowly goes down until the next update.

About the behavior of different versions:

- LuxCore v1.5 updated the film with a fixed interval of something like 1 second (I don't remember exactly);

- LuxMark v3.1 updated the film every 5 seconds

- LuxCore v2.0 is quite smarter as it dynamically adapt the download interval according the time spent to transfer the film. This is very important when rendering large images as the time required for the download can be significative. For instance, a 4k image can take up to 250ms for the transfer and if the transfer is done every seconds it will reduce the rendering performance by a 25%.
You can find the related code here: https://github.com/LuxCoreRender/LuxCore/blob/85ba6cb2e2107bdccad8b3436e09ab3d258a5e72/src/slg/engines/pathocl/pathoclopenclthread.cpp#L145

**Comment by nyers33** [comment]
Thank you!
Yeah, I should have stated that more precisely, it is score convergence.

So if I get it right:
 - LuxCore v1.5 updates the film >1 sec interval; the score is logged / refreshed every sec - this explains the jumps in the score
 - LuxCore v2.0 defaults to 0.2 sec and checks whether enough time was spent in rendering kernels - in my case yes as the render resolutions are not that high - smooth score log

Any comments on the performance of the different LuxCore versions?

scene | v1.5 | v2.0
-- | -- | --
LuxBall | 12.6 | 9.7
Mic | 7.9 | 9.9
Hotel | 3.7 | 3.2

**Comment by Dade916** [comment]
> Any comments on the performance of the different LuxCore versions?

You can not compare samples/sec among different versions. A newer version can run at half of the samples/sec but reduce the noise by 4 times (i.e. it is effectively 2 times faster and render the same image quality in half the time).

For instance v2.0 use adaptive rendering so it stops sampling the white background of Mic scene very soon (while the older versions will not).

You would have to evaluate "noise reduction"/sec to have an absolute estimation of the rendering speed of the software (using the same hardware). But "noise reduction" speed is hard to evaluate and it requires the finished rendering for estimation (i.e. something, you can not have during the rendering).

**Comment by nyers33** [comment]
Thanks for the insights!
