### ISSUE TITLE
Materials look very different depending on camera position

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#113]
https://forums.luxcorerender.org/viewtopic.php?f=4&p=4062#p4062
https://youtu.be/oDtza9dQTYs

This zip contains the .blend and the same scene exported to .bcf from two different camera positions.
[view_dependent_problem_LuxCore.zip](https://github.com/LuxCoreRender/LuxCore/files/2015723/view_dependent_problem_LuxCore.zip)

**Comment by wasd** [comment]
From my observation, bug resides somewhere inside .blend file. Once file is corrupted, every transmissive material renders weirdly. This topic https://forums.luxcorerender.org/viewtopic.php?f=2&t=575 and this message https://forums.luxcorerender.org/viewtopic.php?f=2&t=474&start=120#p5785 has some evidence.

**Comment by wasd** [comment]
I can't find exact steps to reproduce. I can tell that I've created 10-30 various transmissive materials (matter translucent, glossy translucet, glass) and roughly the same amount of volume nodes, then a few (3-10) particle systems (hair) with groups and objects as particles. With 30000-100000 particles in each. At some point the file becomes bugged.

**Comment by Theverat** [comment]
In the OP I attached a video where you can see how the material looks correct from one camera position and wrong from another.
Only the camera is updated in between.
This looks like a bug in LuxCore to me.

**Comment by wasd** [comment]
Maybe I've mentioned it before or not: backfaces disappear for translucent materials in corrupted files. Sometimes it depends on angle... haha just now. while making thes screenshots, I've made a new camera, switched to it, and backfaces were magically cured!
![planes1](https://user-images.githubusercontent.com/438829/46165101-f29e5080-c2b9-11e8-9b54-6fc7073d1e8f.jpg)
![planes2](https://user-images.githubusercontent.com/438829/46165107-f7630480-c2b9-11e8-89b4-88766b331045.jpg)

I think I've got pretty close to the lair of the beast. 
It's here:
![3](https://user-images.githubusercontent.com/438829/46165897-fd59e500-c2bb-11e8-824f-e24d02336d8a.jpg)
I think "corruption" occur when I disable auto-detect camera volume. Now I can corrupt/uncorrupt file few times a second.

**Comment by Theverat** [comment]
Sounds like something is wrong with your volume setup.
Maybe also the normals of your meshes (where the normal points is exterior volume, the other side is interior volume).
On meshes without thickness that are floating in the middle of the scene, like in the image above, you should use the same volume for interior and exterior.

**Comment by Theverat** [comment]
Can not reproduce from this description, please upload a scene.

**Comment by wasd** [comment]
[untitled.zip](https://github.com/LuxCoreRender/LuxCore/files/2425829/untitled.zip)

To make volume I opened world settings and pressed button "New" at the "World Volume"
