### ISSUE TITLE
Feature Request/Bug report Net Console Exposure too High

### ISSUE THREAD

**Issue by batstick** [LuxCoreRender/LuxCore#119]
In the net console I am rendering scenes with some node computers but the exposure (which looks fine in blender renderings) is far too high resulting in white or nearly white preview images. All of my machines are on Beta 2.1 Alpha 1. This issue is consistent across different scenes and different rendering methods and across 3 completely different machines (even across operating systems). So for the solution, could we have some sort of exposure/gamma controls in the preview panel of the net console? Thanks!

This was rendered inside blender:
![image](https://user-images.githubusercontent.com/30424137/41071241-c9a776c8-69c4-11e8-9482-a5945d34052c.png)

The same scene rendered on the network:
![image](https://user-images.githubusercontent.com/30424137/41071284-e22d44ca-69c4-11e8-8d54-0efc7646d29c.png)

**Comment by Theverat** [comment]
Did you adjust the Blender color management settings?
Blender color management can not be applied outside of Blender, so it should be left at the default values if you want to match an exported scene.

**Comment by Dade916** [comment]
I assume B.Y.O.B. posted the correct answer to the problem.
