### ISSUE TITLE
wrong GPU

### ISSUE THREAD

**Issue by andreimd87** [LuxCoreRender/LuxCore#122]
getting error while trying to render a scene saved on a machine with a different GPU.

![image](https://user-images.githubusercontent.com/19931241/42528463-2eecd24c-8484-11e8-9dab-7f75c02ee7bb.png)

this scene was saved on my laptop with gt520. now i'm trying to render this scene on my office pc with a gtx1060 but it shows my home laptop gpu.

**Comment by Dade916** [comment]
You have just to refresh the OpenCL device list after loading the scene on the new hardware.

**Comment by Theverat** [comment]
Weird, the addon should automatically update the OpenCL devices if they are different.
This check is done when loading the .blend file.
Not sure why it fails, are there any error messages in the console?

You can run the device detection manually by pressing spacebar, then searching for "update open" and run the LuxCore operator:

![scrn_2018-07-10_22-15-08](https://user-images.githubusercontent.com/1584761/42535137-e6791db2-848e-11e8-8e76-226c62eae401.png)
