### ISSUE TITLE
Darkening effect when stacking more than about 16 mesh layers with transparent material

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#124]
Forum post: https://forums.luxcorerender.org/viewtopic.php?f=4&t=519&p=5107#p5107

16 layered planes:
![0001](https://user-images.githubusercontent.com/1584761/43355165-1306fe18-9258-11e8-9bd2-fac389bbfccc.jpg)

26 layered planes:
![0011](https://user-images.githubusercontent.com/1584761/43355169-2343be10-9258-11e8-83c7-aaf0f30d98b6.jpg)

Scene setup:
![scrn_2018-07-28_11-21-39](https://user-images.githubusercontent.com/1584761/43355189-783dc384-9258-11e8-96af-be89746c397a.png)

Blender and LuxCore files:
[opacity.blend.zip](https://github.com/LuxCoreRender/LuxCore/files/2237833/opacity.blend.zip)
[opacity_LuxCore.zip](https://github.com/LuxCoreRender/LuxCore/files/2237834/opacity_LuxCore.zip)

**Comment by Dade916** [comment]
The problem should be now fixed.

**Comment by Theverat** [comment]
Confirmed, thanks!

**Comment by Dade916** [comment]
Note: TILEPATHOCL (and RTPATHOCL) count the layers of transparent surfaces as an iteration of the rendering fines state machine so they requires to increase the max. path depth to avoid black regions. This is an unavoidable problem without a performance penalty. All other rendering engines work as intended a can use a max. path depth where transparent surfaces are skipped.
