### ISSUE TITLE
Jpeg Compilation problem in Ubuntu 16.04

### ISSUE THREAD

**Issue by QhelDIV** [LuxCoreRender/LuxCore#125]
Now I've followed the instructions in LinuxCompile repo, everything is fine, until this happened:

> * Cleaning and unpacking jpeg
>  * Compiling jpeg
> **cp: cannot stat '/usr/bin/libtool': No such file or directory
> cp: cannot stat '/usr/share/gnuconfig/config.guess': No such file or directory
> cp: cannot stat '/usr/share/gnuconfig/config.sub': No such file or directory**
> checking for gcc... gcc
> checking whether the C compiler (gcc -w -mtune=generic -std=gnu++98 -mmmx -msse -msse2 -O2 -pipe -mfpmath=sse -fPIC -L/mnt/data/qheldiv/tools/LinuxCompile-master/target-64-sse2/lib -static-libgcc -static-libstdc++) works... yes
> checking whether the C compiler (gcc -w -mtune=generic -std=gnu++98 -mmmx -msse -msse2 -O2 -pipe -mfpmath=sse -fPIC -L/mnt/data/qheldiv/tools/LinuxCompile-master/target-64-sse2/lib -static-libgcc -static-libstdc++) is a cross-compiler... no
> checking whether we are using GNU C... yes
> checking how to run the C preprocessor... gcc -E
> checking for function prototypes... yes
> checking for stddef.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for size_t... yes
> checking for type unsigned char... yes
> checking for type unsigned short... yes
> checking for type void... yes
> checking for working const... yes
> checking for inline... __inline__
> checking for broken incomplete types... ok
> checking for short external names... ok
> checking to see if char is signed... yes
> checking to see if right shift is signed... yes
> checking to see if fopen accepts b spec... yes
> checking for a BSD compatible install... /usr/bin/install -c
> checking for ranlib... ranlib
> checking host system type... Invalid configuration `x86_64-unknown-linux-gnu': machine `x86_64-unknown' not recognized
> 
> checking libjpeg version number... 62
> creating ./config.status
> creating Makefile
> creating jconfig.h
> ./libtool --mode=compile gcc -w -mtune=generic -std=gnu++98 -mmmx -msse -msse2 -O2 -pipe -mfpmath=sse -fPIC  -I. -c ./jcapimin.c
> ./libtool --mode=compile gcc -w -mtune=generic -std=gnu++98 -mmmx -msse -msse2 -O2 -pipe -mfpmath=sse -fPIC  -I. -c ./jcapistd.c
> make: ./libtool: Command not found
> make: ./libtool: Command not found
> Makefile:143: recipe for target 'jcapimin.lo' failed
> make: *** [jcapimin.lo] Error 127
> make: *** Waiting for unfinished jobs....
> Makefile:143: recipe for target 'jcapistd.lo' failed
> make: *** [jcapistd.lo] Error 127
>  !!! Jpeg compilation failed

I've checked the /usr/share/ folder, there are no gnuconfig subfolders but only gnupg and gnupg2.
So what's the problem?

**Comment by Dade916** [comment]
You need to install libtool package with apt/aptitude/etc.
