### ISSUE TITLE
Unable to load scene from LuxCoreUI

### ISSUE THREAD

**Issue by Fact87** [LuxCoreRender/LuxCore#128]
I am not able to open the Cornell scene that comes with the standalone package:
The following error is displayed:

LuxCoreUI v2.0 (LuxCore demo: http://www.luxcorerender.org)
[LuxCore][19.750] Configuration:
[LuxCore][19.766]   film.width = "512"
[LuxCore][19.766]   film.height = "512"
[LuxCore][19.766]   image.filename = "cornell.png"
[LuxCore][19.766]   scene.file = "scenes/cornell/cornell.scn"
[SDL][19.766] Reading scene: scenes/cornell/cornell.scn
RenderConfig loading error:
Unable to open properties file: scenes/cornell/cornell.scn

I am on Window 10 64 bits.

**Comment by Dade916** [comment]
The file paths inside the scene files are set up to work with the following command:

./bin/luxcoreui scenes/cornell/cornell.cfg

If you load the scene from the menu, luxcoreui will unable to find the scenes/cornell/cornell.scn because the current directory is "scenes/cornell" instead of ".".
