### ISSUE TITLE
Possible shrink of HitPoint structure

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#130]
I noticed that the HitPoint structure can be made smaller by putting the two `bool`s in front of the two pointers.
This saves 8 Bytes of padding. The current HitPoint struct is 280 Bytes large with 10 Bytes of padding, after the reorder it's 272 Bytes large.

Not sure if this actually matters much, tell me what you think. Should I push this as a commit?
Are there additional changes required (e.g. in OpenCL code)?

```diff
diff --git a/include/slg/bsdf/hitpoint.h b/include/slg/bsdf/hitpoint.h
index f68cff4..c134725 100644
--- a/include/slg/bsdf/hitpoint.h
+++ b/include/slg/bsdf/hitpoint.h
@@ -49,10 +49,10 @@ typedef struct {
 	float passThroughEvent;
 	// Transformation from local object to world reference frame
 	luxrays::Transform localToWorld;
+	bool fromLight, intoObject;
 	// Interior and exterior volume (this includes volume priority system
 	// computation and scene default world volume)
 	const Volume *interiorVolume, *exteriorVolume;
-	bool fromLight, intoObject;
 
 	luxrays::Frame GetFrame() const { return luxrays::Frame(dpdu, dpdv, shadeN); }
 } HitPoint;
diff --git a/src/slg/volumes/clear.cpp b/src/slg/volumes/clear.cpp
index 05eb219..5d2ac93 100644
--- a/src/slg/volumes/clear.cpp
+++ b/src/slg/volumes/clear.cpp
@@ -57,8 +57,8 @@ float ClearVolume::Scatter(const Ray &ray, const float u,
 		1.f,
 		0.f, // It doesn't matter here
 		Transform(),
-		this, this, // It doesn't matter here
-		true, true // It doesn't matter here
+		true, true, // It doesn't matter here
+		this, this // It doesn't matter here
 	};
 	
 	const float distance = ray.maxt - ray.mint;
diff --git a/src/slg/volumes/heterogenous.cpp b/src/slg/volumes/heterogenous.cpp
index 2645450..7000496 100644
--- a/src/slg/volumes/heterogenous.cpp
+++ b/src/slg/volumes/heterogenous.cpp
@@ -78,8 +78,8 @@ float HeterogeneousVolume::Scatter(const Ray &ray, const float u,
 		1.f,
 		0.f, // It doesn't matter here
 		Transform(),
-		this, this, // It doesn't matter here
-		true, true // It doesn't matter here
+		true, true, // It doesn't matter here
+		this, this // It doesn't matter here
 	};
 
 	for (u_int s = 0; s < steps; ++s) {
diff --git a/src/slg/volumes/homogenous.cpp b/src/slg/volumes/homogenous.cpp
index e30b7c0..8fe2e62 100644
--- a/src/slg/volumes/homogenous.cpp
+++ b/src/slg/volumes/homogenous.cpp
@@ -113,8 +113,8 @@ float HomogeneousVolume::Scatter(const Ray &ray, const float u,
 		1.f,
 		0.f, // It doesn't matter here
 		Transform(),
-		this, this, // It doesn't matter here
-		true, true // It doesn't matter here
+		true, true, // It doesn't matter here
+		this, this // It doesn't matter here
 	};
 
 	const Spectrum sigmaA = SigmaA(hitPoint);
```

**Comment by Dade916** [comment]
slg::HitPoint is used only on CPU so you are saving about 8 bytes for each rendering thread. What you are looking for is here: https://github.com/LuxCoreRender/LuxCore/blob/master/include/slg/bsdf/hitpoint_types.cl

(included by include/slg/bsdf/hitpoint.h under the slg::ocl name space: https://github.com/LuxCoreRender/LuxCore/blob/46a28c5234ce9ffcf2141e78a83cd79af45d336b/include/slg/bsdf/hitpoint.h#L31)

It is the one used by OpenCL (with something like 500,000 threads so it is the one where you can save a lot of GPU memory).

**Comment by Theverat** [comment]
The OpenCL version does not contain any padding Bytes (everything is 4 Bytes large).

If the scene has less than 257 material indices, we could use `unsigned char`s for the volume indices to save 6 Bytes.
If we also use an `unsigned char` for the "bool" value `intoObject`, we would save another 3 Bytes.
Makes a total of 9 Bytes saved, but since the struct is padded to 4 Byte segments, this would create 1 padding Byte and we would have 8 Bytes saved in total.

However, I am not sure if this creates more problems than it's worth... I think it can easily happen that there are more than 256 material indices in complex scenes.

**Comment by frankyifei** [comment]
is it possible to use half precision float, that would save a lot at cost of accuracy.

**Comment by Dade916** [comment]
Nearly all GPU can not read 8bit aligned fields and many can not read 16bit aligned. There is an OpenCL extension to read char fields but it is optional and there is usually a big performance hit for reading char fields anyway.

Half is another possible solution and it could be quite effective in term of memory saving but it would open a can of worms in term of numerical precision problems and related artifacts.

**Comment by Theverat** [comment]
Interesting info about the GPU abilities.
I think we can close this, I agree about half precision probably increasing the floating point problems.
But there might be other areas where half precision is acceptable.
