### ISSUE TITLE
pyluxcoretool CLI not working without pyside

### ISSUE THREAD

**Issue by minecraft2048** [LuxCoreRender/LuxCore#131]
I'm trying this with Luxcore 2.0 from download page in an AWS Ubuntu Linux environment:
```
ubuntu@ip-172-31-9-30:~/luxcorerender-v2.0-linux64-opencl$ python3 pyluxcoretools.zip merge
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pyluxcoretools.zip/__main__.py", line 44, in <module>
  File "pyluxcoretools.zip/pyluxcoretools/pyluxcoremenu/cmd.py", line 24, in <module>
    different completion depending upon which position the argument is in.
ModuleNotFoundError: No module named 'PySide'
```

As this is a CLI command this should work according to this:

> You can avoid to install PySide if you use only the command line tools available in pyluxcoretool. You can than run pyluxcoretool with a:
>python3 pyluxcoretools.zip (or python pyluxcoretools.zip)

**Comment by worldbeater** [comment]
I confirm the issue exists. When I use a stable build from the releases page, and execute `python3 pyluxcoretools.zip` command on a clean Ubuntu 18.04 or 16.04, I get the following exception printed to console:
```
root@d55a9e6518db:/luxcorerender-v2.0-linux64-opencl# python3 pyluxcoretools.zip
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pyluxcoretools.zip/__main__.py", line 40, in <module>
  File "pyluxcoretools.zip/pyluxcoretools/pyluxcoreconsole/cmd.py", line 26, in <module>
    The `default' method may be overridden to intercept commands for which there
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
If I use latest alpha build from the releases page, the exception text changes:
```
root@50f0bca25e57:/luxcorerender-v2.1alpha4-linux64# python3 pyluxcoretools.zip
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pyluxcoretools.zip/__main__.py", line 44, in <module>
  File "pyluxcoretools.zip/pyluxcoretools/pyluxcoremenu/cmd.py", line 24, in <module>
    different completion depending upon which position the argument is in.
ModuleNotFoundError: No module named 'PySide'
```
My Ubuntu 16.04 and Ubuntu 18.04 were preconfigured as such:
```
apt-get update
apt-get -y install git wget python3 python3-pip
wget https://github.com/LuxCoreRender/LuxCore/releases/download/luxcorerender_v2.1alpha4/luxcorerender-v2.1alpha4-linux64.tar.bz2 -O luxcorerender.tar.bz2
tar xvjf luxcorerender.tar.bz2
rm luxcorerender.tar.bz2
```
Are there any instructions on how to get the CLI tooling working with `PySide`, or even how to install that package? `PySide` seems to be completely broken with Python 3.5 and throws freaky exceptions blocking it's installation.

**Comment by Dade916** [comment]
Running:

sudo pip3 install PySide

should fix your problem, at least it fixes the problem for Ubuntu 14.04LTS (using python v3.5). I'm aware of the PySide 1 Vs Pyton v3.6 problem but, for the moment, we are stuck with v3.5 because of Blender. I vaguely remember that PySide 1 may work with Python v3.6 too.
The code works also with PySide 2 on MacOS so it may work with PySide 2 also on Linux (but I have never tried).

**Comment by worldbeater** [comment]
@Dade916 thank-you, with `Ubuntu-14.04` the error blocking `PySide` installation is finally gone! But I'm still unable to install `PySide`. `pip3 install PySide` says the following:
```
error: Failed to find qmake. Please specify the path to qmake with --qmake parameter.

Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/PySide/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5e4t2m1h-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/PySide
Storing debug log for failure in /root/.pip/pip.log
```
I'd say it would be great to have a complete list of required dependencies somewhere in README :+1:

**Comment by minecraft2048** [comment]
Is the documentation misleading in this case? It says that I can run pyluxcoretool CLI without pyside

**Comment by knut-soltvedt** [comment]
I think this issue should be reopened: 
- PySide is not supported for Python > 3.4
- the workaround proposed by @Dade916 is not working - as the __main__.py is still importing a script depending on PySide (`pyluxcoremenu.cmd`):
https://github.com/LuxCoreRender/LuxCore/blob/master/samples/pyluxcoretool/pyluxcoretool.py#L44
And even though there is in this file a test to switch to PySide2 in case PySide is not present:
https://github.com/LuxCoreRender/LuxCore/blob/master/src/pyluxcoretools/pyluxcoretools/pyluxcoremenu/cmd.py#L28
That test is pointless as one of the files (`pyluxcoretools.pyluxcoremenu.menuwindow`) imported right after the test is itself importing PySide without check:
https://github.com/LuxCoreRender/LuxCore/blob/master/src/pyluxcoretools/pyluxcoretools/pyluxcoremenu/menuwindow.py#L10
Leading to a crash.

I think both issues should be fixed, i.e.:
- ensure the CLI scripts does not need PySide,
- enforce PySide vs. PySide2 switch everywhere.

**Comment by s10z** [comment]
I can conform this, having an Ubuntu 18.04 installation and facing the issue while trying to get the luxcorerenderer 2.1 running without a GUI. I even installed PySide2 but the suggested workaround providing "help" as command leads to the following:

$ python3 pyluxcoretools.zip help
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pyluxcoretools.zip/__main__.py", line 44, in <module>
  File "pyluxcoretools.zip/pyluxcoretools/pyluxcoremenu/cmd.py", line 34, in <module>

  File "pyluxcoretools.zip/pyluxcoretools/pyluxcoremenu/menuwindow.py", line 10, in <module>
ModuleNotFoundError: No module named 'PySide'

**Comment by acasta69** [comment]
The above mentioned commit should solve the problem of the CLI still needing pyside.
The pyside/pyside2 problem is different and not addressed here.

**Comment by acasta69** [comment]
Since there were no more comments, I would say this can be closed.
