### ISSUE TITLE
Add device setting for image pipeline in BlendLuxCore

### ISSUE THREAD

**Issue by minecraft2048** [LuxCoreRender/LuxCore#133]
For some reason if the OpenCL image pipeline uses my CPU OpenCL device it will segfault, which is a bug in itself. In previous Luxrender, there is a toggle to enable/disable OpenCL for image pipeline, but here it is missing, so instead of just adding it, I think a device setting like LuxCore device settings menu but for image pipeline will be better, as then the user can choose which OpenCL devices that they want to use, and they can separate the main rendering device and the image pipeline device

**Comment by Theverat** [comment]
> For some reason if the OpenCL image pipeline uses my CPU OpenCL device it will segfault, which is a bug in itself.

I have fixed this bug a while ago, unfortunately after v2.1alpha3 was released, so you will have to wait for the next release to get the fix.
https://github.com/LuxCoreRender/LuxCore/commit/1d8a983cbfb3c8e34e35e44605aebfa2c31e14a2

I also added a checkbox to enable/disable the OpenCL imagepipeline. 76048f6a720ab20934d6aa998300cf6d468f8df2
LuxCore only searches the GPUs for a suitable OpenCL device, CPUs are ignored.
Not sure if an explicit selection option is necessary.
