### ISSUE TITLE
Multiple vertex color support per mesh [$5]

### ISSUE THREAD

**Issue by stanland** [LuxCoreRender/LuxCore#134]
LuxCore currently only supports one set of vertex colors per mesh, it would be great to have multiple vertex color support per mesh.

**Comment by Dade916** [comment]
The support must be for vertex colors, UVs and alpha.

**Comment by Dade916** [comment]
Done, the new support is explained here: https://forums.luxcorerender.org/viewtopic.php?f=5&t=1558
