### ISSUE TITLE
Volume auto detection correctness

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#141]
This code seems weird to me:
https://github.com/LuxCoreRender/LuxCore/blob/master/src/slg/cameras/camera.cpp#L91
```c++
const Volume *volume = intoObject ? material->GetExteriorVolume() :	material->GetInteriorVolume();
if (volume)
	volume = scene->defaultWorldVolume;
```
* I find it confusing that a local variable `volume` is created with the same name as the `volume` member variable of the `Camera` class.
* If I understand correctly, this code is supposed to assign the default world volume to the camera if the material that was hit does not have a volume assigned on the side that was hit. However, currently it does the opposite: the default world volume is used **when** a volume is found on the material.

So, shouldn't the code be like this?
```c++
const Volume *foundVolume = intoObject ? material->GetExteriorVolume() : material->GetInteriorVolume();
if (foundVolume)
	volume = foundVolume;
else
	volume = scene->defaultWorldVolume;
```

**Comment by Dade916** [comment]
Yes, it is wrong, the code was supposed to be this:

```
			volume = intoObject ? material->GetExteriorVolume() : material->GetInteriorVolume();
			if (!volume)
				volume = scene->defaultWorldVolume;
```
