### ISSUE TITLE
RTPATHOCL bug when adding object

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#143]
Some users have reported crashes which happen when an object is added during a running OpenCL viewport render.
I could not reproduce a crash myself, but I observe other weird behaviour when adding objects.
For example, in the video below you can see that a new cube is added. It should use the default material (grey matte), however one of its faces seems to copy the light emitting material of the area light source.
It can be reproduced in every case on my PC. Blender scene attached.
When rendering on CPU, this does not happen.

* Video: https://youtu.be/PLHYkpY0fnw
* Blender file: [ocl_viewport_bug.zip](https://github.com/LuxCoreRender/LuxCore/files/2447745/ocl_viewport_bug.zip)

I tested on Windows 7.
One of the users who reported crashes uses Linux.
My GPU is an AMD HD7970 GHz, latest drivers.
There are no error messages in the console.

**Comment by Dade916** [comment]
Everything is working fine with my AMD GPU but I'm experiencing crashes and dead lock with the NVIDIA GPU. As a test, I forced the usage of AMD OpenCL CPU and I'm experiencing a crash there too, so there must be a problem.

**Comment by Dade916** [comment]
I should have fixed the problem.
