### ISSUE TITLE
autoexposure doesn't work with tiled sampling

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/LuxCore#144]
When both autobrightness in camera and tiled is enabled each pass makes rendering darker
[autoexpo_and_tiled_bug.zip](https://github.com/LuxCoreRender/LuxCore/files/2478078/autoexpo_and_tiled_bug.zip)

attached simple blender file where just pressing f12 to render will show what's the problem.

Disable autoexposure in camera or disable tiled and the issue is gone.

The issue is present in alphav4 in blender 2.79b and easiest visible when using sun and sky.

**Comment by Dade916** [comment]
I should have fixed the problem. It was caused by an error in variance clamping code. It was incorrectly handling samples weights and it was working fine only for a weight of 1 (TILEPATH with 3x3 AA add samples of weight 9).

**Comment by Dade916** [comment]
I should have fixed the problem. It was caused by an error in variance clamping code. It was incorrectly handling samples weights and it was working fine only for a weight of 1 (TILEPATH with 3x3 AA add samples of weight 9).

**Comment by Dade916** [comment]
I should have fixed the problem. It was caused by an error in variance clamping code. It was incorrectly handling samples weights and it was working fine only for a weight of 1 (TILEPATH with 3x3 AA add samples of weight 9).

**Comment by Dade916** [comment]
I should have fixed the problem. It was caused by an error in variance clamping code. It was incorrectly handling samples weights and it was working fine only for a weight of 1 (TILEPATH with 3x3 AA add samples of weight 9).
