### ISSUE TITLE
Bump is wrong

### ISSUE THREAD

**Issue by wasd** [LuxCoreRender/LuxCore#150]
Pictures here:
https://forums.luxcorerender.org/viewtopic.php?f=4&t=703#p7201

**Comment by Dade916** [comment]
It doesn't look like a bug to me: LuxCore just uses a different sign in the direction of bump mapping when compared to Cycles. If you want to obtain the same Cycles result, you have only to use a negative bump height value.

This is a normal rendering with a Bump height of 5mm (flipped when compared to Cycles):

![plain](https://user-images.githubusercontent.com/3247881/48010244-82d37f00-e11d-11e8-8bb5-fefb03a38b49.png)

and this is with a Bump height of -5mm (same as Cycles):

![rgb_imagepipeline_0](https://user-images.githubusercontent.com/3247881/48010218-751df980-e11d-11e8-822b-7ecef451037e.png)

It should be just a different default reference system.

**Comment by wasd** [comment]
Shadow on depressed square shoud be at the upper and left sides.
Cycles:
![b1](https://user-images.githubusercontent.com/438829/48022069-b7baf280-e16c-11e8-9a5e-1deefed0d2b8.png)

Luxcore bump -5mm:
shadows are at the left and lower side
![b3](https://user-images.githubusercontent.com/438829/48022251-4d568200-e16d-11e8-96fe-06f5155676e9.png)

Luxcore bump 5mm:
depression and extrusion switched, but shadows still at wrong sides
![b2](https://user-images.githubusercontent.com/438829/48022098-d4efc100-e16c-11e8-9279-452dffb4e695.png)

**Comment by wasd** [comment]
![b4](https://user-images.githubusercontent.com/438829/48022571-15037380-e16e-11e8-909c-050f31f22476.png)

**Comment by Dade916** [comment]
I should have fixed the problem (more information avilable at https://forums.luxcorerender.org/viewtopic.php?f=4&t=703&start=10#p7525).
