### ISSUE TITLE
glass material shows no caustics using path engine, rough glass has caustics

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/LuxCore#152]
Path engine should render caustics for glass material, but only rough glass works under path engine.

**Comment by frankyifei** [comment]
update: I can use rough glass with lowest roughness as a workaround.

**Comment by Theverat** [comment]
Please upload a scene and a render.
Which light source is casting the caustic? It has to be intersectible so path can find it.

**Comment by frankyifei** [comment]
[00000.bcf.zip](https://github.com/LuxCoreRender/LuxCore/files/2544908/00000.bcf.zip)
bidi-20 samples
![bidi-20samples](https://user-images.githubusercontent.com/8104251/47952043-33743e00-dfb9-11e8-970a-085a4c797366.jpg)
pathocl - 200 samples
![pathocl-200samples](https://user-images.githubusercontent.com/8104251/47952044-3707c500-dfb9-11e8-9b5c-4e273552aef6.jpg)

pathocl- 5000 samples - rough glass
![pathocl5000samples](https://user-images.githubusercontent.com/8104251/47952066-bdbca200-dfb9-11e8-9915-44c1e6d9da5c.png)

**Comment by frankyifei** [comment]
Ok, so spot light is not intersectible light. That's the reason.
 I just wonder how does the rough glass material works in this case
