### ISSUE TITLE
triplanar mapping with blending

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/LuxCore#153]
Many models don't really need detailed uv map. In other cases an artist can be given a cad mesh for example that might be difficult and also unnecessary to uv map as we can get away using simple "dirt" type of textures that introduce some variance in otherwise uniform looking shader.

Triplanar projection of texture with the ability to blend between projections can greatly reduce time spent on making a lot of common materials.

Good working example is cycles inage texture node which can switch between this generated box mapping and flat uv projection.

**Comment by lacilaci** [comment]
vray example of map:
https://docs.chaosgroup.com/display/VRAY3MAX/Triplanar+Texture+Mapping+%7C+VRayTriplanarTex

**Comment by Dade916** [comment]
The forum related thread: https://forums.luxcorerender.org/viewtopic.php?f=5&t=1638

**Comment by Dade916** [comment]
The support for triplanar mapping should be now complete.
