### ISSUE TITLE
OpenCL Sigabort using Mix Node on OS X with Nvidia Card

### ISSUE THREAD

**Issue by rebpdx** [LuxCoreRender/LuxCore#155]
When using Mix Node in Blender OpenCL crashes with a Sigabort

### Steps to reproduce

With mix sig abort occurs:
1. Using a Mac OS Computer with an Nvidia Card
2. Load LuxCore2.1Benchmark.blend
3. Set LuxCore Config to Device: OpenCL
4. Start Render
5. Program Crashes with SigAbort

Without mix render succeeds:
1. Using a Mac OS Computer with an Nvidia Card
2. Load LuxCore2.1Benchmark.blend
3. Remove all Mix Nodes and replace with a link to diffuse input from Box057, NurbsPath.000, NurbsPath.001, NurbsPath.003, and Shape01

### Version and Hardware info
Blender 2.79b
LuxCore v2.1Alpha4
Mac OS 10.12.6
NVIDIA GTX 980 Ti

**Comment by Theverat** [comment]
Did you try OpenCL CPU device?
It might be a bug in the Nvidia OpenCL compiler.

**Comment by rebpdx** [comment]
OpenCL CPU device works ok and it worked when using an ATI card so seems to be Nvidia OpenCL compiler related. Next steps are, most likely, see about reducing the problem down to a single object with a mix node in it to see about isolating to a smaller problem space.

**Comment by Dade916** [comment]
@rebpdx, the OpenCL code has a work around to some odd/broken inlining obsession of NVIDIA OpenCL compiler and it is used only on OpenCL "NVIDIA" platform. I wonder if MacOS+NVIDIA GPU is reported as "NVIDIA" or "APPLE" platform. 

The code is here: https://github.com/LuxCoreRender/LuxCore/blob/ef423b30615f4dce9379fd556bd704bf66a8f703/src/slg/engines/pathoclbase/pathoclbaseoclthreadkernels.cpp#L588

Mix is a material calling other materials and it is the typical situation where NVIDIA compiler was going crazy without the above "inline" workaround.

**Comment by Dade916** [comment]
I assume this is now outdated and can be closed.
