### ISSUE TITLE
Bidirectional CPU failing tests MacOS

### ISSUE THREAD

**Issue by rebpdx** [LuxCoreRender/LuxCore#156]
Bidirectional CPU is failing tests with an out of bounds PDF on MacOS

### Steps to reproduce

1. Compile LuxCore on MacOS
2. Run Python tests for BIDIRCPU

Observe failed assert for throughput.IsInf()

### Version and Hardware info
LuxCore v2.1Alpha4
Mac OS 10.12.6

### Root Cause Analysis:
Root cause is yet to be not determined, it appears that the throughput.IsInf() occurs twice for BIDIRCPU_METROPOLIS infinite light test and occasionally passes tests for BIDIRCPU_RANDOM infinite light test.

Floating point arguments for Clang on Mac OS have been investigated and appear to be set to most accurate options possible to avoid rounding and optimization errors.

It was also determine that Linux on the same hardware passes these tests as expected. It has not been determined if Clang in Linux passes these tests which may help isolate Clang vs. GCC or Linux vs. MacOS related issue.

**Comment by rebpdx** [comment]
The issue is no longer reproducible since v2.1beta2 root cause is unknown, most likely related to the Embree 3.2.4 update or bad build environment during v2.1alpha4.

With the v2.1beta2 builds it was confirmed that clang in Linux builds and passes tests as well.

**Comment by Dade916** [comment]
I assume this is now outdated and can be closed.
