### ISSUE TITLE
LuxCore compilation problems under linux

### ISSUE THREAD

**Issue by onebiozz** [LuxCoreRender/LuxCore#161]
Trying to install luxcore on an ubuntu 18.04 rendering box has caused all sorts of problems. i used the install script and the latest output is as follows 

zlib-1.2.8.tar.gz
 * Done checking distfiles
 * Checking target tree
 * Target tree exists
 * Checking libstdc++
 * Done checking libstdc++
 * Checking python
 * Done checking python
 * Prechecks completed

 * Using Python library path: /home/biozz/LinuxCompile/target-64-sse2/lib/libpython3.6.a
 * Using Python include path: /usr/include/python3.6m

]0;LuxCore stage * Configuring luxrays luxcore pyluxcore luxcoreui
-- CMake version 3.10.2 detected
-- Single-config generator detected
-- Using build variant: 
-- Available custom configurations in cmake/SpecializedConfig:
--   Config_Dade
--   Config_Linux-Static
--   Config_OSX
--   Config_Windows
-- Using custom build config: cmake/SpecializedConfig/Config_Linux-Static.cmake
-- Using my own settings
-- Could NOT find Boost
-- Re-trying with link static = ON
-- Could NOT find Boost
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
-- Could NOT find OPENCL (missing: OPENCL_LIBRARIES OPENCL_INCLUDE_DIR OPENCL_C_INCLUDE_DIR) 
-- OpenMP found - compiling with
-- Configuring incomplete, errors occurred!
See also "/home/biozz/LinuxCompile/LuxCore/CMakeFiles/CMakeOutput.log".
 !!! luxrays luxcore pyluxcore luxcoreui configuration failed

boost is installed both on my system and by the script
OPENCL should not be installing as this is CPU only and no OPENCL devices are installed
all dependencies should be installed and everything else worked properly 

any help would be appreciated 

EDIT: it does say opencl is disabled at the top of the output

**Comment by Dade916** [comment]
If it is required only to run renderings (and not for development) why you don't use the pre-compiled binaries ? They are statically linked and will work on Ubuntu 18.04.

**Comment by onebiozz** [comment]
I was unaware luxcore had precompiled binaries, where are they at?

**Comment by Dade916** [comment]
Last stable release is available here: https://luxcorerender.org/download/
Last under development build is available here: https://forums.luxcorerender.org/viewtopic.php?f=9&t=727
And, finally, after every GitHub commit, binaries are automatically built and posted here: https://github.com/LuxCoreRender/LuxCore/releases/tag/latest

**Comment by onebiozz** [comment]
That appears to have worked, thank you.
