### ISSUE TITLE
Strange Artefacts on light area 

### ISSUE THREAD

**Issue by PetrTT** [LuxCoreRender/LuxCore#164]
Strange Artefacts on border of  light area on the floor from sun
Open_CL+Path+Sobol +direct light Cache
![sobol_direct_](https://user-images.githubusercontent.com/20154959/48966732-41c9de80-efe8-11e8-93f4-e629806f5f98.png)
Open_CL+Path+Sobol +Log Power
![sobol_logpower](https://user-images.githubusercontent.com/20154959/48966734-4f7f6400-efe8-11e8-8514-3b43c0386469.png)
is clean
[TEST_02.zip](https://github.com/LuxCoreRender/LuxCore/files/2612170/TEST_02.zip)
the same result if use Metropolis sampler instead Sobol

**Comment by Dade916** [comment]
There is a known problem between Glossy material (and Glossy coating)  and DLSC, it is listed here: https://wiki.luxcorerender.org/LuxCoreRender_Release_Notes_v2.1 (https://github.com/LuxCoreRender/LuxCore/issues/158)

It should work fine if you use a normal Matte material  (or low glossy roughness values) for the floor.
