### ISSUE TITLE
Artifacts on faces in path tracing

### ISSUE THREAD

**Issue by canonex** [LuxCoreRender/LuxCore#168]
Artifacts appears in path tracing render (on the ceiling and right wall):
![luxpath](https://user-images.githubusercontent.com/1444378/50368901-bfecb700-058d-11e9-95dc-76d433ec237e.jpg)

but not in bidir:
![luxbidir](https://user-images.githubusercontent.com/1444378/50368906-cbd87900-058d-11e9-8570-15b84ba4b516.jpg)

The mesh has no issue, normals are consistent. The material is a mix of a Matte (with bump) and a Glossy. Both images rendered for 10 minutes.

Thank you,
Riccardo

**Comment by Theverat** [comment]
I think the issue is there in the bidir render as well, just a lot weaker.

**Comment by canonex** [comment]
Attached you find the scene.
[master-L2-bugReport.zip](https://github.com/LuxCoreRender/LuxCore/files/2704690/master-L2-bugReport.zip)

I'm on Debian Linux 64, Nouveau drivers
Blender 2.79b official, LuxCore beta 4

**Comment by Dade916** [comment]
The test scene seems to work fine here:

![test](https://user-images.githubusercontent.com/3247881/50373072-935e8c80-05d9-11e9-97e7-c5a514169967.jpg)

Do you get a different result ?

**Comment by canonex** [comment]
I get the images attached in the first post...

Thank you,
Rickyx

**Comment by Dade916** [comment]
It is not the same scene (?)

**Comment by lacilaci** [comment]
> It looks like the problem is in bump mapping because it works fine without.

Not exactly, the problem is lack of UV mapping with bump mapping applied, I did smart UV's and left bump map and now it looks ok. I noticed similar problems too, when I forget to properly map object and apply bump map all kinds of weird shading appears. Not sure if this can be somehow avoided (maybe missing uv warning when applying bump map?)

**Comment by Dade916** [comment]
Ok, so I will check why OpenCL and CPU produce different results when using a mesh without UV coordinates (however you can not have working bump map without UV coordinates when using an image map as bump texture so this is the source of the problem for @canonex 's scene).

**Comment by lacilaci** [comment]
> you can not have working bump map without UV coordinates when using an image map as bump texture

Maybe B.Y.O.B. could give a warning message in the addon on the bump node?(missing UV = shading problems?) There is a similar "missing uv" message on the fabric shader afaik, so it could be doable.

**Comment by Theverat** [comment]
I already show a warning on the imagemap node, not sure if an extra warning on bump node is required.

![2018-12-22_14-36-05](https://user-images.githubusercontent.com/1584761/50375003-0296a980-05f7-11e9-9f15-99e8e42e3c3b.png)

**Comment by lacilaci** [comment]
Hm I really don't know, what would be the best way.
Lets skip additional warning then and just straight autodisable any bump on materials that have no mapping.

Or a separate warning message in error log about object having no uv but bump applied. So in future cases checking log can help diagnose the issue for new users.

**Comment by canonex** [comment]
I understand that the lack of the uv on the ceiling is causing this issue. In fact I can properly render the scene just adding a uv.
But the wall on the right has uv mapping and vertical banding appears.

Thank you,
Riccardo

**Comment by canonex** [comment]
> I already show a warning on the imagemap node, not sure if an extra warning on bump node is required.

I dont' see the warning!

And what happens if the material is applied to 2 objects, one with the uv and the other without?

Thank you,
Riccardo

**Comment by canonex** [comment]
Ok, that extra warning should be enough to avoid this problem.
Again, thank you,
Riccardo

ps. I was not aware that Lux supported only one uv... good to know!

**Comment by Theverat** [comment]
I added this warning:

![2018-12-23_15-57-04](https://user-images.githubusercontent.com/1584761/50384892-ee70ac00-06cb-11e9-924f-2f090d91a053.png)
https://github.com/LuxCoreRender/BlendLuxCore/commit/7bf220b7f1fc1ced3945641fdd70aec0b1d6e30a#diff-30460531c11c2a795d226750ff7634c6R116
