### ISSUE TITLE
boost v1.69.0 eos_portable_archiver

### ISSUE THREAD

**Issue by szczepaniak-bartek** [LuxCoreRender/LuxCore#169]
Spirit V2.5.7  (Boost V1.69.0) has dropped own FP routines in favor of boost::math.

**Comment by Dade916** [comment]
Sorry, what do you mean ? eos_portable_archiver  is not compatible with Boost 1.69 ?

**Comment by bartoszek** [comment]
Yes, it include spirit headers that no longer exists, I've tried to substitute them with math ones, but still have some errors.

**Comment by Dade916** [comment]
Ok (just stick to the older Boost version in the mean time)

**Comment by Dade916** [comment]
Going to close this and fix the problem if/when we upgrade to a newer Boost version.
