### ISSUE TITLE
Regression: Meshlights with many triangles take a very long time to initialize

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#17]
I just updated to the latest LuxCore and somewhere in the last commits this regression happened I think.
I don't know what the last working commit was, but I think the one I had before was around 208f71bc19d1f7c94061387c91216eb7df803411.

*The problem:* When I put a light emitting material on the LuxBall, the intialization takes a very long time (singlethreaded apparently). Before the regression this was instant, no noticeable difference between light emitting materials and non-light-emitting.
Here's a test scene:
[testscene.zip](https://github.com/LuxCoreRender/LuxCore/files/1580948/testscene.zip)

And here's the CPU usage during the startup (on the left it starts, on the right the render starts with all cores)
![scrn_2017-12-22_00-14-12](https://user-images.githubusercontent.com/1584761/34279007-9ce88760-e6ae-11e7-9ed0-ff7df0fcf0de.png)

This is the log:
```
[SDL][4.850] Material definition: Material__001SURFACE
[SDL][4.852] The Luxball000 object is a light sources with 85824 triangles
[SDL][36.040] Scene objects count: 1
[SDL][36.041] The Luxball__ring000 object is a light sources with 12386 triangles
[SDL][40.490] Scene objects count: 3
```
Tested on Linux 64 bit no OpenCL.
P.S. once the render runs, I can move around the scene normally (very fast).

**Comment by Theverat** [comment]
I can confirm that, thanks.

**Comment by aedancullen** [comment]
3765a33 seems to cause:

`src/luxrays/core/exttrianglemesh.cpp:603:16: error: cannot bind non-const lvalue reference of type ‘const luxrays::ExtTriangleMesh*&’ to an rvalue of type ‘const luxrays::ExtTriangleMesh*’
  outArchive << this;
`

for me on Ubuntu 17.10.

**Comment by Dade916** [comment]
@aedancullen I'm using Ubuntu 14.04 and I can not replicate the problem here but I assume 17.10 has a newer GCC version and it is more picky. My last commit should fix the problem. Let me know if it does.

**Comment by aedancullen** [comment]
Yes, it's good now. Ubuntu 17.10 has GCC 7.2.0, by the way.

**Comment by Theverat** [comment]
>I'm using Ubuntu 14.04

Ah, someone else with ancient Ubuntu.
All my friends laugh about my 14.04 but it's too much of a hassle to upgrade on a laptop.
