### ISSUE TITLE
LuxCore hangs when using SAMPLECOUNT AOV with Bidir

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#172]
When I add the SAMPLECOUNT AOV while using Bidir, only a few samples appear and rendering speed is at 0 samples/sec, but CPU load at 100%.
If I try to stop the render, Blender/luxcoreui hangs completely and has to be killed.
Removing the SAMPLECOUNT output fixes the problem.

![capture](https://user-images.githubusercontent.com/1584761/52489315-3ab37500-2bc2-11e9-84d7-d619bbc365ed.PNG)

[bidir_hangs.blend.zip](https://github.com/LuxCoreRender/LuxCore/files/2845783/bidir_hangs.blend.zip)
[bidir_hangs.cfg.zip](https://github.com/LuxCoreRender/LuxCore/files/2845784/bidir_hangs.cfg.zip)

**Comment by lacilaci** [comment]
Could this explain non-working adaptivity or is this just bad aov?

**Comment by Theverat** [comment]
> Could this explain non-working adaptivity or is this just bad aov?

Might be related. Anyway LuxCore shouldn't hang/crash, I can set other AOVs that aren't supported by Bidir and LuxCore just ignores them.

**Comment by Dade916** [comment]
BiDir support both SAMPLECOUNT and CONVERGENCE AOVs: https://github.com/LuxCoreRender/LuxCore/blob/cd346b2aa97f04efaee77a121f4e78f7ca81d6ef/src/slg/engines/bidircpu/bidircputhread.cpp#L48

And they are working fine here with your test scene:

![bidir](https://user-images.githubusercontent.com/3247881/52556114-e25fbb80-2deb-11e9-8510-4e45f3283d15.jpg)

@Theverat can you still reproduce the problem with the latest sources ?

**Comment by Theverat** [comment]
> can you still reproduce the problem with the latest sources ?

Yes, on Windows.
But not on Linux.

But I discovered another problem on Linux: when I open the Film Outputs editor (instead of the Channels window) and click "Show" on the SAMPLECOUNT output, LuxCore exits with error 
```RUNTIME ERROR: Unknown film output type in Film::GetOutput<float>(): 27```

**Comment by Dade916** [comment]
> But I discovered another problem on Linux: when I open the Film Outputs editor (instead of the Channels window) and click "Show" on the SAMPLECOUNT output, LuxCore exits with error
> `RUNTIME ERROR: Unknown film output type in Film::GetOutput<float>(): 27`

This is just a bug in LuxCoreUI: the SAMPLECOUNT data type is "unsigned int", not "float". I fixed this problem.

**Comment by Theverat** [comment]
I can no longer reproduce this problem, even on Windows.
