### ISSUE TITLE
Feature Request: Thin Film Interference

### ISSUE THREAD

**Issue by wasd** [LuxCoreRender/LuxCore#175]
Soap bubbles, oil slicks, skin surface, grease stains, optic coatings and butterfly wings – there's many materials that cause interference.
I've found this paper https://www.ci.i.u-tokyo.ac.jp/~hachisuka/mcp.pdf and this article https://www.gamedev.net/articles/progra ... ics-r2962/ which may help.

**Comment by Theverat** [comment]
The second link is broken.

**Comment by wasd** [comment]
I've copied it from phpbb :)
https://www.gamedev.net/articles/programming/graphics/thin-film-interference-for-computer-graphics-r2962/

**Comment by Dade916** [comment]
The v2.3 will be about materials rework and new materials.

**Comment by Theverat** [comment]
Just for the record: I have done some work on this topic in the [thin_film_interference branch](https://github.com/LuxCoreRender/LuxCore/tree/thin_film_interference) a while ago, but could not solve some mismatches between the simulated film colors and the real-world reference images.

**Comment by DEBIHOOD** [comment]
Why it is not closed? Isn't it was implemented already?

**Comment by Dade916** [comment]
I think so.
