### ISSUE TITLE
Crash when emission color is negative

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#177]
[crash_LuxCore.zip](https://github.com/LuxCoreRender/LuxCore/files/3005438/crash_LuxCore.zip)
[crash.blend.zip](https://github.com/LuxCoreRender/LuxCore/files/3005439/crash.blend.zip)

The crash seems to happen somewhere in [`slg::PathTracer::DirectLightSampling(luxrays::IntersectionDevice*, slg::Scene const*, float, float, float, float, float, float, slg::PathDepthInfo const&, luxrays::RGBColor const&, slg::BSDF const&, slg::PathVolumeInfo, slg::SampleResult*) const`](https://github.com/LuxCoreRender/LuxCore/blob/master/src/slg/engines/pathtracer.cpp#L98).

Maybe the returned spectrum value of the `emittedTex` should be clamped in https://github.com/LuxCoreRender/LuxCore/blob/master/src/slg/materials/material.cpp#L93

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Thanks!
