### ISSUE TITLE
Sky/Infinitelight: assertion failure

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#180]
In a scene I'm currently testing, LuxCore throws an assertion failure at line https://github.com/LuxCoreRender/LuxCore/blob/3479a1480f60d6944f5e9f0200d1cb6a4721c67c/src/slg/lights/sky2light.cpp#L430

Through debugging I found that the value of `directPdfW` is zero.
I'm wondering if zero really is forbidden for `directPdfW`,
 or if the check should be `(*directPdfW >= 0.f)`?

(similar occurence in https://github.com/LuxCoreRender/LuxCore/blob/master/src/slg/lights/infinitelight.cpp#L187)

**Comment by Dade916** [comment]
`*directPdfW = distPdf * latLongMappingPdf;`

and before there is a check:

`	if (latLongMappingPdf == 0.f)
		return Spectrum();`

so distPdf must be 0.0 to have an assertion failure.  And if "distPdf = 0.0" there is something very wrong going on with the Distribution2D.

Do you have a totally black sky or something like that (so no values is a valid pick) ?

**Comment by Theverat** [comment]
> Do you have a totally black sky or something like that (so no values is a valid pick) ?

No. But it seems that it only happens when the visibility map is enabled.
Here's the scene:

[scene.zip](https://github.com/LuxCoreRender/LuxCore/files/3039519/scene.zip)

**Comment by Dade916** [comment]
I should have fixed the problem: it is more a work around than a fix because Distribution1D doesn't handle an endless number of corner cases. I should rewrite that class.

**Comment by Theverat** [comment]
Thanks!
