### ISSUE TITLE
Carpaint specular color

### ISSUE THREAD

**Issue by Piitas** [LuxCoreRender/LuxCore#186]
Using luxcore 2.1 and blender 2.78c

Specular color in carpaint seems to not work quite right. Setting specular color 1 to any color and the other two to pure black does not show the correct specularty when rendering. Setting specular color 2 or 3 to anything but black, even RGB 0.004, will show a lot of specularity when rendering. See attached blend file.
I checked with classic lux and it does not show the same behavior. That one works as expected.

[car paint.zip](https://github.com/LuxCoreRender/LuxCore/files/3076629/car.paint.zip)

**Comment by Dade916** [comment]
I'm looking into this, I have already fixed one problem but there are more.

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Piitas** [comment]
Excellent. Thanks. The render looks good now
