### ISSUE TITLE
Wrong brightness when mixing glass with roughglass

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#187]
Reported by Fox: https://forums.luxcorerender.org/viewtopic.php?f=4&t=1049
Scenes and blend file: [mix_brightness_issue.zip](https://github.com/LuxCoreRender/LuxCore/files/3077704/mix_brightness_issue.zip)

Glass:
![glass](https://user-images.githubusercontent.com/1584761/56097127-b4cce680-5ef0-11e9-8e98-c1cc2acb2dc3.png)

Rough Glass:
![roughglass](https://user-images.githubusercontent.com/1584761/56097128-b696aa00-5ef0-11e9-8d8c-b2489e278927.png)

Mix between both:
~~(mix amount is 0, so the result should be identical to the glass result)~~
Mix amount is 0.001, with glass being first and roughglass being second material.
![mix](https://user-images.githubusercontent.com/1584761/56097129-b8606d80-5ef0-11e9-903a-fec926efedf7.png)

**Comment by Dade916** [comment]
If I edit mix_brightness_issue/mix/scene.scn and set:

`scene.materials.Surface_Lens__Glass__1_2218819541336.amount = 0.0`

I get:

![RGB_IMAGEPIPELINE_0](https://user-images.githubusercontent.com/3247881/56290804-3d7f9880-6124-11e9-9617-3f423b48e052.png)

The same result I get from rendering mix_brightness_issue/glass/render.cfg:

![RGB_IMAGEPIPELINE_0](https://user-images.githubusercontent.com/3247881/56290913-7ae42600-6124-11e9-8887-d28b7c556a4a.png)

Are you doing something different ?

**Comment by Theverat** [comment]
Sorry, my mistake, the mix amount is not 0, but in fact 0.001 (Blender UI cut off the last decimal).
By the way, scn files would be more readable if FILESAVER would not create all those implicit constfloat(3) textures.

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Thanks!
