### ISSUE TITLE
Overwrite just one property

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#188]
Is there a way to overwrite just one property?

For example, I have some scene properties:
```
[... camera definitions, material definitions, other object definitions ...]
scene.objects.myobj.material = "140282332853768"
scene.objects.myobj.ply = "Mesh-140282318231560000"
scene.objects.myobj.camerainvisible = 0
scene.objects.myobj.transformation = 0.367410332 0.113838762 0.923065722 0 -0.142140895 0.987694621 -0.0652325153 0 -0.919133067 -0.107238293 0.379070371 0 0.690034628 0.0802595764 0.189451084 1
[...]
```
And I only want to assign a new value to the property `scene.objects.myobj.transformation`. Is that possible?

**Comment by Dade916** [comment]
It is something like:

```
props = scene.ToProperties()
oldObjDefiniton = props.GetAllProperties("scene.objects.myobj.")
newObjDefintion = oldObjDefiniton.Set(Property("scene.objects.myobj.transformation")(blabla))

scene.Parse(newObjDefintion)
```

**Comment by Dade916** [comment]
There is also a specific/faster method to update only object transformation but I assume it is not what you were looking for.

**Comment by Theverat** [comment]
Thanks, my code is working now, but I'm still a bit puzzled why my first approach didn't work.
It looked like this:
```python
# Loading frame-specific props from file
frame_props = pyluxcore.Properties(os.path.join(anim_props_dir, "%05d.scn" % frame))
scene_props = scene.ToProperties()
scene_props.Set(frame_props)
scene.Parse(scene_props)
```

The working code now:
```python
    cam_props = frame_props.GetAllProperties("scene.camera")
    scene.Parse(cam_props)

    for key in frame_props.GetAllUniqueSubNames("scene.objects"):
        obj_props = scene.ToProperties().GetAllProperties(key)
        obj_props_frame = frame_props.GetAllProperties(key)
        obj_props.Set(obj_props_frame)
        scene.Parse(obj_props)
```
I don't really understand why I have to call `scene.Parse()` for each property group separately.
Anyway, my original code would probably have caused a lot of unnecessary sceneedits.

**Comment by Dade916** [comment]
The working code is redefining only camera/objects while the old code was redefining everything (also textures, materials, lights, shapes).

The working code is also leaving untouched any object not defined in "frame_props", not sure if it is the intended behavior (or should they be deleted ?).

**Comment by Theverat** [comment]
> The working code is redefining only camera/objects while the old code was redefining everything (also textures, materials, lights, shapes).

Yes, but I wonder why nothing moves when I do that. Of course it's a waste, but since I changed the transformations of some objects, I would expect them to move, however the render result stays exactly the same.

> The working code is also leaving untouched any object not defined in "frame_props", not sure if it is the intended behavior (or should they be deleted ?).

That's intended, anything not in frame_props just is not animated.

**Comment by Dade916** [comment]
You must investigate the original code to find an explaination, just try:

```
frame_props = pyluxcore.Properties(os.path.join(anim_props_dir, "%05d.scn" % frame))
scene_props = scene.ToProperties()
scene_props.Set(frame_props)
scene_props = scene_props.GetAllProperties("scene.objects.<name of a moving object>")
scene.Parse(scene_props)
```

and check if it works, if it doesn't print "scene_props", etc.

**Comment by Theverat** [comment]
That works. However I'm not going to investigate further.
Thanks for your help!
