### ISSUE TITLE
Broken shell shape and position misalignment in pysideluxcoredemo

### ISSUE THREAD

**Issue by JayFoxRox** [LuxCoreRender/LuxCore#190]
Versions:

- LuxCore #189 (as this sample is broken in master)
- Python 3
- PySide2

Steps to reproduce:

1. Start the sample
2. Hit "LuxBall Shape" &rarr; "Toggle Shell"
3. Hit "LuxBall Position" &rarr; "Move Left" (Ctrl + Left)
4. Hit "LuxBall Position" &rarr; "Move Left" (Ctrl + Left)
5. Hit "LuxBall Shape" &rarr; "Toggle Shell"

**~~Shape/Visibility error~~**

*(Edit: Apparently this is intended, as implied by `luxBallShapeIsCube` - I personally assumed the shell would be toggled between visible / invisible, or at least a good looking shape)*

~~After step 2, I get the following image (happens regardless of position; so I can also do steps in order 1, 3, 4, 2 and the error also occurs):~~

[~~Click here for a screenshot: Bad shape~~](https://user-images.githubusercontent.com/360330/56242664-116b0580-6099-11e9-88d3-0d27fb92cb34.png)

**Position misalignment**

After step 5, I get the following (only prepared by setup moves 3 and 4; also happens in order 1, 3, 4, 2, 5):

![Bad position](https://user-images.githubusercontent.com/360330/56242673-162fb980-6099-11e9-9cae-672b697086a7.png)

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by JayFoxRox** [comment]
It is not fixed yet.

The issue also still remains in f673cc780a7380bf94bf67f14bac2eb4201e7068 (please try my steps to reproduce). I'm not sure if I understand the intended fix either.

I don't know enough about the LuxCore SDL yet, but what appears to happen (assumptions):

1. Setting the `.ply` property on the shell seems to reset the transformation (should it?).
2. Deleting an object does not reset its transformation (shouldn't it?). I assume `.transformation` remains set.

I've attempted to confirm these assumptions using `print(self.scene.ToProperties().Get("scene.objects.luxinner.transformation"))` (same for "luxshell") but the property isn't found; I blame my lack of LuxCore SDL / API knowledge for this.

Ideally the shell would be modified without resetting the transform, so deleting the objects to reset the positions (which appears to have been the intention of the fix) is not a good solution in my opinion.

**Comment by Dade916** [comment]
> It is not fixed yet.
> 
> The issue also still remains in [f673cc7](https://github.com/LuxCoreRender/LuxCore/commit/f673cc780a7380bf94bf67f14bac2eb4201e7068) (please try my steps to reproduce).

I have and now it works fine here.

Are you sure to have re-compiled pyluxcore.so and not only updated pysideluxcoredemo.py ?

**Comment by JayFoxRox** [comment]
You are right. I didn't realize there were changes outside of the Python script (and it appears I didn't recompile).

It works in https://github.com/LuxCoreRender/LuxCore/commit/f673cc780a7380bf94bf67f14bac2eb4201e7068.
