### ISSUE TITLE
Different Output between CPU and OpenCL

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#198]
This new example scene shows very different output between PathCPU and PathOCL on my notebook's OpenCL CPU device: https://github.com/LuxCoreRender/LuxCoreTestScenes/tree/master/scenes/ProceduralLeaves

Here's the rendered output, note that the CPU render has some more samples than the OCL render, but I hope the problem is already visible:

**PathCPU:**
![pathcpu](https://user-images.githubusercontent.com/1584761/57199870-90f74080-6f84-11e9-9bdf-fb09441d20de.png)

**PathOCL:**
![pathocl](https://user-images.githubusercontent.com/1584761/57199880-9ce30280-6f84-11e9-899c-b5d4e0c4f4d2.png)

The leaf meshes have no thickness, the material is glossytranslucent.

**Comment by Theverat** [comment]
The problem might be in the OpenCL bump code.

I replaced the glossytranslucent material with matte and fed only the bump into it.
[ProceduralLeaves_onlybump.blend.zip](https://github.com/LuxCoreRender/LuxCore/files/3146006/ProceduralLeaves_onlybump.blend.zip)

This is what is fed into the bump socket:

**Bump input CPU:**
![bump_input_cpu](https://user-images.githubusercontent.com/1584761/57200047-dfa5da00-6f86-11e9-9c5e-d1009d488ced.png)

**Bump input OCL:**
![bump_input_ocl](https://user-images.githubusercontent.com/1584761/57200050-e5032480-6f86-11e9-842c-e63b6c59fe6b.png)

And this is the result of the bump:

**Bump result CPU:**
![bump_cpu](https://user-images.githubusercontent.com/1584761/57200043-d0bf2780-6f86-11e9-8c3a-a74e227f9d7b.png)

**Bump result OCL:**
![bump_ocl](https://user-images.githubusercontent.com/1584761/57200061-06fca700-6f87-11e9-944d-7490cbf6d5d0.png)

The bump input is identical, but the result is different.

**Comment by Dade916** [comment]
I should have fixed this problem.
