### ISSUE TITLE
Travis CI for releases

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#20]
I just discovered that Travis CI can upload the compiled binaries to create releases on github:
* https://docs.travis-ci.com/user/deployment/releases/
* https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci/33109519#33109519
We could use this to automatically create test builds for people who want to use the bleeding edge binaries without compiling themselves (replacing the old daily builds).
But we could also use this to create final releases.

Now all we need is a cross compiler so Travis can also build Windows binaries for us and we'll never again have to package a release by hand...

**Comment by Dade916** [comment]
This issue should be moved to "LinuxCompile" repository. I'm going to close this one here.

**Comment by Theverat** [comment]
True, I created it over there.
