### ISSUE TITLE
How to bake texture maps?

### ISSUE THREAD

**Issue by oschakravarthi** [LuxCoreRender/LuxCore#201]
Hi,

How to bake texture maps for each mesh in my scene? Does Lux renderer has this feature?

**Comment by Theverat** [comment]
No, baking is currently not possible in LuxCore.

**Comment by LumiereDeLOmbre** [comment]
Is that answer still relevant in 2023? (Wanted to use the forum but the confirmation email is taking ages to come).

Thanks
