### ISSUE TITLE
Fails to find boost because python-related packages are listed in the boost requirements

### ISSUE THREAD

**Issue by yurivict** [LuxCoreRender/LuxCore#205]
The message:
```
CMake Error at CMakeLists.txt:101 (MESSAGE):
  --> Could not locate required Boost files - Please check


-- Configuring incomplete, errors occurred!
```

This line seems to be a culprit: https://github.com/LuxCoreRender/LuxCore/blob/master/cmake/Dependencies.cmake#L69

```numpy``` an ```python``` aren't a part of boost, I'm not sure why should they be in this line.

Please also make the failure message more informative and say which components are missing.

FreeBSD 12.

**Comment by Theverat** [comment]
The Python and Numpy boost components are required by pyluxcore (LuxCore's Python API wrapper).

**Comment by yurivict** [comment]
I'm sorry, the subject should have been different.
boost-libs-1.70.0_1 does install /usr/local/include/boost/python/numpy.hpp and python extensions, but LuxCore fails to find them.

**Comment by Dade916** [comment]
You should use the static compiling procedure at https://github.com/LuxCoreRender/LinuxCompile

We don't support other libraries versions and/or combinations.

**Comment by Dade916** [comment]
I guess we can close this one.
