### ISSUE TITLE
Mix material + architectural glass bug

### ISSUE THREAD

**Issue by Piitas** [LuxCoreRender/LuxCore#210]
The mix material appears to not use the transmission component from arch glass. Using a mix material set to use 100% of the arch glass will render a black material. 
This is specific to arch glass only. Glass and rough glass renders correct with the mix material.

Attached files
*Scene 1: using arch glass only. Rendering is correct
*Scene 2: using mix material with arch glass and matte. mix is set to 100% arch glass. Rendering is a black sphere.
*blend file

luxcoreui 2.2 beta 2
blendluxcore 2.2 beta 1

[mixing architectural glass bug_LuxCore.zip](https://github.com/LuxCoreRender/LuxCore/files/3236576/mixing.architectural.glass.bug_LuxCore.zip)

**Comment by Dade916** [comment]
For the first time in history, this works fine in OpenCL and it is a CPU only bug, there is a first for everything.

I assume it will easy to track where the problem is.

**Comment by Dade916** [comment]
The bug was the result of a quite incredible typo. It should now work fine.

**Comment by Piitas** [comment]
Excellent! Thanks
