### ISSUE TITLE
LinuxDeps OpenImageIO Build Issue

### ISSUE THREAD

**Issue by CatherineTower** [LuxCoreRender/LuxCore#211]
All right, here we go.

I'm running Arch Linux (fairly recently updated) and trying to run the LinuxDeps `build-64-sse2` script. The build progresses all the way through
`[ 95%] Linking CXX static library libOpenImageIO.a`
where it sits for a good long while, and then fails without giving me a link error, just a Make error:
```
make[2]: Leaving directory '/tmp/luxbuild/oiio-Release-1.8.11/build/linux64'
make[1]: *** [Makefile:163: all] Error 2
make[1]: Leaving directory '/tmp/luxbuild/oiio-Release-1.8.11/build/linux64'
make: *** [Makefile:365: cmake] Error 2
 !!! openimageio compilation failed
```

If I navigate to `/tmp/luxbuild` I can find the unpacked build files and if I go to `/tmp/luxbuild/oiio-Release-1.8.11/build/linux64` I can run `make` again, where I get the error
`make[2]: *** No rule to make target '../../src/doc/oiiotool', needed by 'src/doc/oiiotool.1'.  Stop.`
Navigating to `../../src/doc` I find that there's a file called `oiiotool.tex`, which makes me think that maybe there's just a mistake in the Makefiles? But I've dredged through so many Makefiles and couldn't find mention of `oiiotool` at all. I'm at a loss on this one.

I did some searching and saw an issue from about a year and a half ago that said that using the compiler switch `-std=gnu++98` would make it work better, since OpenImageIO has problems with C++11, but when I edited the main script to change the switch, it was overridden in another configuration file somewhere. I was unable to find mention of additional compiler options in other files.

In addition, this is one of my first issues I've posted, so please let me know if there's anything I've missed that I need to provide.

Thank you,
Catherine Tower

**Comment by Theverat** [comment]
tex, doc ... is it failing to build the latex documentation? Maybe this step can be disabled?

**Comment by CatherineTower** [comment]
After searching through more Makefiles, I found a directory with some C++ sources that looked like they're used to generate an executable called `oiiotool`. I tried compiling them manually and it gave me a link error, I can revisit that later.

I ended up just telling `build-64-sse2` to skip to the next stage and it continued along just fine. This seems more like a workaround than anything else, but it's good enough for now.

My next problem comes from a missing Boost header. Should I create a new issue, or can I continue on here?

**Comment by Theverat** [comment]
Better to post it here, the problems might be interlinked.

**Comment by CatherineTower** [comment]
`boost/spirit/home/support/detail/math/fpclassify.hpp` is not present on my system. Looking through Boost documentation, it appears to have been taken out of more recent releases. The build script goes through the build process for Boost and succeeds, but doesn't seem to find it when it comes time to compile LuxCore.

**Comment by Theverat** [comment]
The boost version in LinuxCompileDeps is boost_1_67_0.
What's the exact error message?

**Comment by CatherineTower** [comment]
```
In file included from /home/catherine/src/personal/luxcore/LuxCore/include/luxrays/utils/serializationutils.h:47,
                 from /home/catherine/src/personal/luxcore/LuxCore/include/luxrays/core/geometry/vector.h:29,
                 from /home/catherine/src/personal/luxcore/LuxCore/include/luxrays/core/epsilon.h:23,
                 from /home/catherine/src/personal/luxcore/LuxCore/src/slg/cameras/projective.cpp:21:
/home/catherine/src/personal/luxcore/LuxCore/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:125:10: fatal error: boost/spirit/home/support/detail/math/fpclassify.hpp: No such file or directory
 #include <boost/spirit/home/support/detail/math/fpclassify.hpp>
```
It's that error some thirty times or so for various different files.
My system version of Boost is 1.69.0, but I was under the impression that the script would download and use its own version.

**Comment by Dade916** [comment]
Try to check your LinuxCompile/LuxCore/CMakeCache.txt file, just look for any boost related line, they should point to LinuxDeps Boost library with something like:

```
//Boost chrono library (debug)
Boost_CHRONO_LIBRARY_DEBUG:FILEPATH=/home/david/projects/luxcorerender/LinuxCompile/target-64-sse2/lib/libboost_chrono.a

//Boost chrono library (release)
Boost_CHRONO_LIBRARY_RELEASE:FILEPATH=/home/david/projects/luxcorerender/LinuxCompile/target-64-sse2/lib/libboost_chrono.a

//Boost date_time library (debug)
Boost_DATE_TIME_LIBRARY_DEBUG:FILEPATH=/home/david/projects/luxcorerender/LinuxCompile/target-64-sse2/lib/libboost_date_time.a
```

They are likely to point to your system Boost v1.69.0 instead that LinuxDeps v1.67.0 (where fpclassify.hpp is still available).

The problem is to investigate why your cmake are picking the system Boost instead of the local one. What cmake version do you have ?

**Comment by CatherineTower** [comment]
Sure enough, that solved it. I changed all references to `/usr/include` to `/home/catherine/src/personal/luxcore/target-64-sse2/include` and `/usr/lib` to `/home/catherine/src/personal/luxcore/target-64-sse2/lib` and it built just fine.


I'm using CMake version 3.14.4
```
% cmake --version
cmake version 3.14.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by Theverat** [comment]
So LuxCore built successful? Fixing the openimageio stuff was not required?

**Comment by CatherineTower** [comment]
I'm not entirely clear on how that ended up working out. The build script didn't report an error, but it did say that it finished building OpenImageIO. When it stopped, I restarted it at a stage past the OpenImageIO stage, and it continued without complaining. It seems very much like a brittle workaround, but it did solve my problem.

**Comment by Theverat** [comment]
The error messages seemed to indicate to me that only the documentation building was failing (the PDF manual for oiio). That's probably why it worked out.

**Comment by CatherineTower** [comment]
Good enough for now, I say. If a subsequent commit breaks the build, I'll revisit this. Thank you very much for your help.
