### ISSUE TITLE
Artifacts with Laser, BiDir and Volumetrics

### ISSUE THREAD

**Issue by CodeFHD** [LuxCoreRender/LuxCore#216]
Shooting a laser beam into a homogeneous volume shows a few issues:
- A dark band may appear around the center of the image.
- The directly visible beam (camera -> volume -> laser) appears to decay very quickly. This effect seems stronger for a large laser size.
- After a glass object, the decayed beam reappears.
- The direct beam appears to build up in two components: The decaying part, which renders noise-free very quickly, and a more constant beam path that renders slowly and looks similar to the result using the Path engine. I would hence assume that the decay-issue is caused by light rays rather than camera rays.
- images and blend-file attached to demonstrate the problem

![bidir1_setup](https://user-images.githubusercontent.com/48182552/59562172-a8b4f080-9029-11e9-811c-4262a7e58ade.PNG)
![bidir2_wide](https://user-images.githubusercontent.com/48182552/59562173-a8b4f080-9029-11e9-9a63-15a61c108631.PNG)
![bidir3_narrow](https://user-images.githubusercontent.com/48182552/59562174-a8b4f080-9029-11e9-8860-b35d1fb6db0b.PNG)
[bidir_volume_lightrays2.zip](https://github.com/LuxCoreRender/LuxCore/files/3293997/bidir_volume_lightrays2.zip)

**Comment by epileptrolytics** [comment]
There are several versions of this bug reported [here](https://forums.luxcorerender.org/viewtopic.php?f=4&t=1146&start=30) with example pics and files.

**Comment by CodeFHD** [comment]
Update: The issue is not limited to lasers. observed also with a point-source that was collimated with a parabolic mirror. So, perhaps connected to paralell light beams?

**Comment by Dade916** [comment]
As far as I know, this problem has been fixed.
