### ISSUE TITLE
Specular component

### ISSUE THREAD

**Issue by PetrTT** [LuxCoreRender/LuxCore#219]
#### System Information

win 7  gtx 1070

#### Software Version

Blender 2.79b
Luxcore daily build

Hi
have a problem with glossy shader and disney
1 Disney shader
Specular component on value 0 is still exist
2 Glossy shader
glossy shader the same behavior

**Comment by Theverat** [comment]
I can confirm this.
Testscene: [luxcore_cycles_disney_comparison.blend.zip](https://github.com/LuxCoreRender/LuxCore/files/3340355/luxcore_cycles_disney_comparison.blend.zip)

**Cycles with specular = 0:**
![cycles_specular_0](https://user-images.githubusercontent.com/1584761/60362654-ce56d800-99e1-11e9-8714-4969b9c14cc9.png)

**LuxCore with specular = 0:**
![lux_specular_0](https://user-images.githubusercontent.com/1584761/60362681-dd3d8a80-99e1-11e9-8655-3c114500d3ca.png)

**For comparison, Cycles with specular = 0.5:**
![cycles_specular_0 5](https://user-images.githubusercontent.com/1584761/60362696-e7f81f80-99e1-11e9-9ae0-0004e562cb91.png)

**And LuxCore with specular = 0.5:**
![lux_specular_0 5](https://user-images.githubusercontent.com/1584761/60362724-f0e8f100-99e1-11e9-92d8-a6e13f6cceed.png)

**Comment by PetrTT** [comment]
i note that in material preview is working right

**Comment by Dade916** [comment]
As far as I can see, LuxCore has the correct behavior. You are keeping the roughness parameter set to 0.0, if you set to 1.0, you will get a matte-like material (and Cycles-like result).

If you check the Siggraph course notes, pag. 32: https://blog.selfshadow.com/publications/s2012-shading-course/burley/s2012_pbs_disney_brdf_slides_v2.pdf

![param](https://user-images.githubusercontent.com/3247881/60395004-120a2880-9b2d-11e9-86e8-1900dc3dd4d3.jpg)

You can see how the roughness raw, show a very shiny result for roughness set to 0.0 and a matte-like result for 1.0.

This may be a bug in Cycles (?)

**Comment by PetrTT** [comment]
i am not  expert in this topic.Just use it in work.
as i anderstand this spec value control brightness of reflection

[TEST_SPEC.zip](https://github.com/LuxCoreRender/LuxCore/files/3342802/TEST_SPEC.zip)
in example reflection exist in viewport
but not in material preview as i expected

Same workflow in Corona,Amd ProRender
User can control weght of components difuse,glossy etc

**Comment by Dade916** [comment]
I don't understand your test scene: it uses glossy material (?).

If I switch to Disney, in your test scene, and I change the roughness value when specular is set to 0.0, I get exactly the behavior shown in the slide posted before, both in rendering and material preview (?)

Cycles also shows a quite strange behavior in the same test, roughness has no effect at all when specular is set to 0.0 but there is a huge difference if it is set to 0.01.

Now, we have the Disney material form Siggraph 2012, while Cycles uses the extended (with transparencies) from Siggraph 2015 so there may be some difference but I'm checking the 2015 slides and they seem to show the same behavior of the 2012: https://blog.selfshadow.com/publications/s2015-shading-course/burley/s2015_pbs_disney_bsdf_slides.pdf

**Comment by PetrTT** [comment]
It is my expectations of material workflow.Don t undestand me wrong.May be i am wrong
I expected that this value control color and opacity or weight of glossy component  with current roughness in glossy and disney shader.

**Comment by Theverat** [comment]
From an artistic perspective, it would be nice if specular = 0 meant no specular at all, because then you can use specular maps to disable reflections completely in some regions. With the disney material behaviour, you have to supply an additional roughness texture that sets the roughness to 1 in those regions to hide the reflections.
This might be the reason for the decision of the Cycles devs, or maybe it was a performance consideration, or something else entirely. @PetrTT you could try to ask the Blender devs why this decision was made and link them to this issue.

I think we should follow the disney specification, since we do not only want to be compatible with Cycles, but also with any other render engine supporting the disney shader (Unreal engine, appleseed, Unity, Substance and so on).

**Comment by juancarlosgzrz** [comment]
Specular level doesn't have anything to do with roughness, it's obviusly a bug or a bad implementation.
