### ISSUE TITLE
Dead Black Screen, Simple material with homo. vol., openCL

### ISSUE THREAD

**Issue by FarbigeWelt** [LuxCoreRender/LuxCore#222]
On my Windows PC with AMD Hawaii graphic cards rendering with  **LuxCoreRender V2.2 beta2, 11ce3abthe of "Dead Black Screen simple homo material with openCL.blend" leads to Black Screen crash**. Computer does not shut down automatically. Caps lock key does not respond. Brute force PC shut down (switch off running system) is required. The issue happens a short while during rendering **after approx. 750 to 1250 samples**. First I thought issue is hardware related (overheating, CPU fan stop). Coincidentally CPU fan was worn out and BIOS reported CPU fan error sometimes in start up process. After replacing CPU cooler CPU stress with "CPUID CPU-Z" succeeded effortless. The Black Screen scene renders **reliable for more than a half hour on CPU only**. openCL leads to Black screen in less than 10 minutes. After simplifying original scene the **reason of the issue** has been found to be **in material node: homogeneous volume**. More details like console log see attachment. Log files do not show any error. The crash happens obvious to suddenly to allow system to write latest logs to file.
[Dead Black Screen with openCL, build V2.2 beta2, 11ce3ab.zip](https://github.com/LuxCoreRender/LuxCore/files/3388918/Dead.Black.Screen.with.openCL.build.V2.2.beta2.11ce3ab.zip)

**Comment by FarbigeWelt** [comment]
Black Screen happens too with material node heterogeneous volume.
[Dead Black Screen simple hetero material with openCL.zip](https://github.com/LuxCoreRender/LuxCore/files/3389277/Dead.Black.Screen.simple.hetero.material.with.openCL.zip)

**Comment by FarbigeWelt** [comment]
After my last Black Screen, this time I got it rendering a scene without any scattering material volume, I decided to overwrite all files in BlendLuxCore add-on folder with the files of the latest released beta version, V2.2 beta 2. Some when in the series of latest build the first Black Sceens appeared. As hopefully expected, **LuxCoreRender V2.2 beta 2 worked perfectly reliable**. I have rendered many 600x600 images with thousand of samples without any crashes. Because Path Hybrid is a newer feature I finally **overwrote all files in BlendLuxCore folder with latest LuxCoreRender build as well as with BlendLuxCore maintenance branch.** A new scene rendered effortless more than 5000 samples with openCL Hybrid. I wondered about what happens with the scenes attached to the first post of this issue and started the renderer. **Everything was okay.** I rendered a next formerly crashing scene. Again, rendering stopped at final 5000 samples. I am still not sure if the **issues is solved with the 'reinstall'**. I will observe my PC's behavior over the next days until I issue can be closed.

**Comment by Theverat** [comment]
In general, a userspace program like Blender/LuxCore without special privileges can't really lock up your PC in the way you describe. It is most likely a problem in some code with elevated permissions, like the OS kernel or the GPU driver. You could try to do a GPU driver update to see if the issue was already solved.

**Comment by FarbigeWelt** [comment]
In the end issue was hardware related. My AMD R 390x rendered the last Black Screen and left the party. Actually it was the newer of my both graphic cards. Most probably it produced sporadically low level bugs with big impact. 

I think the issue can be closed.

**Comment by Theverat** [comment]
Glad you found the culprit!
