### ISSUE TITLE
CMake fails while looking for system files on macOS 

### ISSUE THREAD

**Issue by jamespa16** [LuxCoreRender/LuxCore#225]
While this may be a 10.15 Catalina surprise, CMake will not compile LuxCore, failing with `Could NOT find Threads` Threads is a system library, and so either LuxCore's macOS CMake script has some serious problems or macOS does; both are equally likely. 

Attempted on:
Mac mini 2018 i7 32GB & macOS 10.15 Catalina Beta 4

**Comment by u3dreal** [comment]
10.15 is not yet supported in build files. So the SDK will not be found.

**Comment by Dade916** [comment]
I guess we can close this one.
