### ISSUE TITLE
Rendering fails due to low iGPU memory even if using CPU only rendering

### ISSUE THREAD

**Issue by jamespa16** [LuxCoreRender/LuxCore#227]
Tried to render out an 8K image using CPU Bidir and it failed because `The Merge buffer is too big for Intel(R) UHD Graphics 630 Intersect device (i.e. CL_DEVICE_MAX_MEM_ALLOC_SIZE=402653184): try to reduce related parameters`. Something tells me that Bidir shouldn't rely on iGPU memory size...

**Comment by Dade916** [comment]
I'm out of the town, I will be back next week. Anyway, image pipiline will still run on the GPU by default. You need to disable OpenCL for image pipeline too. There  is flag in Blender, may be in the camera pannel but I don't have access to Blender until next week.

**Comment by lacilaci** [comment]
Yes imagepipeline settings in camera are set to opencl by default. The bigger question is why would luxcore pick for framebuffer integrated gpu. Is the igpu powering the display as well?

**Comment by jamespa16** [comment]
No actually, the iGPU is not in the loop at all. I have a 16GB Radeon VII running the display, and interestingly trying to render with OpenCL Path on that alone also doesn't work for the same reason.

**Comment by lacilaci** [comment]
I think blendluxcore already filters out igpus as rendering devices, maybe same should be done for framebuffer. There are only problems with them.

**Comment by Dade916** [comment]
I guess we can close this one.

**Comment by Theverat** [comment]
@lacilaci 
> maybe same should be done for framebuffer.

I already do this in BlendLuxCore.
