### ISSUE TITLE
Procedural stochastic texturing [$65]

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/LuxCore#228]
for true seamless mapping of repetitive surfaces.

https://blogs.unity3d.com/2019/02/14/procedural-stochastic-texturing-in-unity/

**Comment by Theverat** [comment]
Here's a WebGL implementation of this technique: https://benedikt-bitterli.me/histogram-tiling/

**Comment by lacilaci** [comment]
hm, I wonder if it's possible to limit rotation and have customizable regular offset of the pattern to make this work with patterns like bricks

**Comment by Dade916** [comment]
I have the first working version: https://forums.luxcorerender.org/viewtopic.php?f=5&t=2516

**Comment by Dade916** [comment]
The support should be now complete.
