### ISSUE TITLE
Disney, wrong photonGI behavior [$5]

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/LuxCore#229]
indirect cache seem too strong when using disney.
https://forums.luxcorerender.org/viewtopic.php?f=4&t=1303

**Comment by lacilaci** [comment]
Tested few things today and this is 100% related to clamping not being taken into account when generating cache. So if I clamp the sun and sky for example the rendering will look as expected when clamped unless you turn on PhotonGI - indirect cache (those cache entries will have look fully unclamped)

**Comment by lacilaci** [comment]
But you know what... Don't fix it. It actually allows to puch GI stronger than direct light would allow. So you can control balance between bright direct light and GI by using low clamping and strong lightsource. This leads also to some interestingly fast interior GI :D

**Comment by Dade916** [comment]
Yes, I consider this the correct behavior as clamping should be done only at the very end of the pipeline.

P.S. I have also the feeling you always use very strong clamping values.

**Comment by lacilaci** [comment]
I do. There is no good way to control fireflies and I cannot always use 100% of denoised results. So I need to mix noisy and denoised results, using high clamping values would cause few fireflies that would show through the mixed results (let's say 50% denoised result and 50% noisy mixed would still show bright spots, so I need to push clamping extremely low, especially for animation where this would flicker like crazy)

**Comment by lacilaci** [comment]
Maybe additional way (very fast way!) of handling fireflies is needed. Especially for animations, but even for stills cause using 100% denoised result will only look good if the source-noisy rendering is already very clean. I always think that maybe clamping only secondary bounces and keeping direct light unclamped could be a way... but there is probably a better way

**Comment by Theverat** [comment]
Maybe we could try clamping only specular and glossy bounces, since they create all the fireflies (I think)? Not sure though if that would make sense.

**Comment by lacilaci** [comment]
It's very bad especially with dark glossy materials where even heavy clamping doesn't help and it's very visible even when blended with denoised pass, like here:

![frame3](https://user-images.githubusercontent.com/43474911/71826381-1431de80-309e-11ea-9c97-f4a6aa09436e.jpg)

sorry that this got off topic kinda...
