### ISSUE TITLE
Hybrid glass/transparent shadows [$5]

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/LuxCore#233]
Even with upcoming SDS solution rendering behind refracting glass might be very computationaly expensive. Current solution with non-refracting architectural glass is working only on distant glass panes that only contribute to scene with some weak reflections at best.

However detailed view near glass panels, especially if there are multiple layers of those makes rendering look very ugly. Even in corona where they can do sds efficiently now, they still need to keep hybrid glass behavior on by default, otherwise the rendertime can jump from +50% to +100% required rendertime.

So having hybrid glass option for rendering could be a very good way of optimizing scenes that have heavy presence of glass like objects.

Another reason is that sometimes strong caustics can be distracting. But if we don't have option for hybrid glass rendering we also cannot disable caustics/light tracing cause this would also bring us back to original problem. 

So we can end up in situation where we have to choose to being able to use proper glass and have caustics or not having caustics but also no refraction.
With this feature we could even disable lighttracing and use both cpu and gpu to do pathtracing and benefit from getting light through glass objects.

Personally ~70% of my projects I can get away without this feature. But proper looking refracting glass that also renders fast is definitely not a corner case.

**Comment by Dade916** [comment]
Discussed in this forum thread: https://forums.luxcorerender.org/viewtopic.php?f=5&t=1474

**Comment by Dade916** [comment]
Done.
