### ISSUE TITLE
Environment lighting results different by cpu and opencl

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/LuxCore#234]
The scene is lit by sky and sun. I tried with only sky or flat colour, the difference is still there. Maybe it is a bug in opencl code.
both rendered 500 samples without any cache.
opencl
![opencl](https://user-images.githubusercontent.com/8104251/64078366-e2d48b00-cd18-11e9-93f2-fc5212a3490e.jpg)
cpu
![cpu](https://user-images.githubusercontent.com/8104251/64078367-e2d48b00-cd18-11e9-9234-9ecc843a86ea.jpg)

**Comment by Dade916** [comment]
It has been explained here: https://forums.luxcorerender.org/viewtopic.php?f=4&t=1376#p16076
