### ISSUE TITLE
Too dark edges in BIDIR mode

### ISSUE THREAD

**Issue by ivovanderlans** [LuxCoreRender/LuxCore#237]
A simple scene with a point light that reflects onto
a mirror that reflects onto a glossy backdrop plane
and a matte cube that are observed by a square camera.
There is no lighting from the world/environment.

The render engine is set up for BI-directional path
tracing at default settings. The image output is set
for 64-by-64 pixels to speed up the rendering.

BUG: the top and right-most edge of the output image
are darker than the rest of the image with no apparent
reason. When switching to the forward path tracer, the
problem is gone but convergence is way too slow. Using
the forward path tracer with added light tracing again
introduces the problem and emphasizes it even more.

I found the bug using the latest BlendLuxCore addin for Blender3D 2.80 but suspect that the issue is with LuxCore itself. The attached blend file shows the issue:

[LuxCore bug.zip](https://github.com/LuxCoreRender/LuxCore/files/3641128/LuxCore.bug.zip)

**Comment by Dade916** [comment]
I have recently fixed a similar bug: https://forums.luxcorerender.org/viewtopic.php?f=4&t=1409&p=16428#p16428

What LuxCore version are you using ?

**Comment by ivovanderlans** [comment]
I am using the latest BlendLuxCore (beyond v2.2RC1) from here: [https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest). Be aware that the bug is _not_ about the edges of objects/geometry but of the output image itself.

**Comment by ivovanderlans** [comment]
![Too dark edges in BIDIR mode](https://user-images.githubusercontent.com/55686592/65411983-87b12800-ddee-11e9-863f-4bdb3f2be2b1.png)
See the upper row and rightmost column in the attached rendered image .

**Comment by Dade916** [comment]
Ok, you mean the first top raw of pixels and the rightmost are black, right ?

**Comment by ivovanderlans** [comment]
Well, darker really - not exactly black. I have another much more complex blend file (containing proprietary research data which I cannot share) where that row and column is less dark but still too dark (by about 10%).

**Comment by ivovanderlans** [comment]
It looks to me like LuxCore has the pixel grid shifted down and left by a fraction of a pixel width, but only for the light rays.

**Comment by Dade916** [comment]
If you set the pixel filter to "NONE" (otherwise, each pixel affects the neighbors) the black pixels are clearly visible:

![RGB_IMAGEPIPELINE_0](https://user-images.githubusercontent.com/3247881/65412489-a06e0d80-ddef-11e9-8536-4e6625e137c0.png)

The image is shifted down and left by one pixel, checking why...

P.S. if you use "METROPOLIS" sampler instead of "SOBOL", the rendering will be a lot faster.

**Comment by Dade916** [comment]
Ok, I should have fixed the problem. The fix will be included in the next automatic build: https://forums.luxcorerender.org/viewtopic.php?f=9&t=736

It should be ready in 2-3 hours.
