### ISSUE TITLE
Bright bottom and left edge when using hybridbackforward

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#239]
Steps to reproduce: 
* Open this scene: [lighttracing_brightline.zip](https://github.com/LuxCoreRender/LuxCore/files/3653434/lighttracing_brightline.zip)
* Press F12
* You should see the attached results

Note: since github uses a bright background, you might have to open the images in a new tab or download them and open them in a program that has dark background so you can spot the bright bottom and right lines.

hybridbackforward enabled:

![lighttracing_on](https://user-images.githubusercontent.com/1584761/65616594-96006f00-dfbb-11e9-802e-37f161ab7b21.png)

hybridbackforward disabled:

![lighttracing_off](https://user-images.githubusercontent.com/1584761/65616635-aa446c00-dfbb-11e9-9edb-8e6a0f6b40b9.png)

It happens with Path CPU and Path OpenCL.
Bidir is fine.
Sampler doesn't matter.

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Thanks!
