### ISSUE TITLE
Add feature: imagemap wrapping

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#24]
Add the imagemap wrapping modes that were supported in Classic Lux: http://www.luxrender.net/wiki/Scene_file_format_1.0#imagemap
> How to wrap the texture using "repeat", "black" (black beyond texture) or "clamp" (clamps to border color)

**Comment by Dade916** [comment]
I have add ed the support for 4 wrap mode: "repeat", "black", "white" and "clamp" (default: repeat). They can be used with the new image map texture ".wrap" properties:

```
scene.textures.imagetex.type = imagemap
scene.textures.imagetex.file = resources/img/grid.png
scene.textures.imagetex.wrap = clamp
```

**Comment by Theverat** [comment]
Great, thanks!
