### ISSUE TITLE
Add displacement support [$5]

### ISSUE THREAD

**Issue by Dade916** [LuxCoreRender/LuxCore#241]
Add support for displacement in a similar way Cycles does.

**Comment by Theverat** [comment]
A few ideas from my side:
* The algorithm should not introduce cracks
* It would be good if a texture node tree could be used to drive displacement strength (not just an image texture)

**Comment by Dade916** [comment]
The solution is discussed here: https://forums.luxcorerender.org/viewtopic.php?f=5&t=1483

**Comment by Dade916** [comment]
And here for the simplification step: https://forums.luxcorerender.org/viewtopic.php?f=5&t=1523

Done.
