### ISSUE TITLE
CUDA/Optix 7 with RTX hardware support [$30]

### ISSUE THREAD

**Issue by Dade916** [LuxCoreRender/LuxCore#245]
CUDA/Optix 7 with RTX hardware support

**Comment by Dade916** [comment]
CUDA support has been added: https://forums.luxcorerender.org/viewtopic.php?f=5&t=2073

RTX support will be added in v2.5.

**Comment by Squadrick** [comment]
@Dade916 Any progress on this? I recently upgraded to an RTX 2070, and I don't mind taking a crack at this.

**Comment by juangea** [comment]
@Squadrick yep :)

2.4 is already CUDA compatible, around 30% faster than 2.4 in OpenCL.

It has many other things, like single time kernel compilation.

And I think Optix will come for 2.5 :)

**Comment by Dade916** [comment]
I started to work on Optix (i.e. RTX) support few days ago on "optix_intersection" branch: https://github.com/LuxCoreRender/LuxCore/tree/optix_intersection

**Comment by Dade916** [comment]
Optix support is now available in v2.5 automatic builds.

**Comment by bartoszek** [comment]
What is the limitation? I can't get Optix to work on `GTX970` despite `blender:cycles` works fine on it.
