### ISSUE TITLE
blender_2.7 maintenance branch.

### ISSUE THREAD

**Issue by bartoszek** [LuxCoreRender/LuxCore#247]
@Theverat  could we have `blender_2.7` maintenance branch, or perhaps add flag to `cmake` to build both version, and rename `blender_2.7` on to `pyluxcore_2.7` :thinking:  ...

**Comment by Theverat** [comment]
I don't really see a reason for that. LuxCore v2.2 is the last release to support Blender 2.79, there will be no further ones, and you can just checkout the `luxcorerender_v2.2` tag to compile it.

**Comment by bartoszek** [comment]
Ok
