### ISSUE TITLE
BlendLuxCore 2.2 Linux OpenCL version broken when initializing render or using "Update OpenCL Device List"

### ISSUE THREAD

**Issue by Lincoln504** [LuxCoreRender/LuxCore#250]
System: Ryzen 5 2600x, 32 GB ram, RTX 2060, Fedora 30 Linux, and tested on both 2.2 Release Candidate 1 and 2.2

When using the OpenCL version of BlendLuxCore, starting a viewport or f12 render on either the CPU or the GPU immediately prints `ClGetDeviceIDs` and does not continue building or rendering the scene. 

Clicking on the "Update OpenCL Device List" button always returns the following error:

`Traceback (most recent call last):
  File "/home/***/.config/blender/2.80/scripts/addons/BlendLuxCore/operators/general.py", line 114, in execute
    device_list = opencl.get_opencl_devices()
  File "/home/***/.config/blender/2.80/scripts/addons/BlendLuxCore/properties/opencl.py", line 77, in get_opencl_devices
    return pyluxcore.GetOpenCLDeviceList()
RuntimeError: clGetDeviceIDs`

**Comment by Dade916** [comment]
Have you tried to run LuxMark to check if your OpenCL drivers aren't broken ? It happens quite often.

**Comment by Lincoln504** [comment]
Nice for the suggestion, just gave it a shot. Seems like the same error, so yeah, maybe the drivers are broken and it isn't a Lux issue. This is what what LuxMark printed:

`terminate called after throwing an instance of 'cl::Error'
  what():  clGetDeviceIDs
./luxmark: line 12:  4063 Aborted                 (core dumped) ./luxmark.bin "$@"`

If it is a driver issue, do you have any pointers on where to begin fixing it? Thanks

**Comment by Theverat** [comment]
Maybe try to remove and reinstall them first?

**Comment by Dade916** [comment]
Are you using the drivers from NVIDIA web site ? Also check if you have some not fully compliant OpenCL option installed like POCL (OpenCL for CPU).

**Comment by Lincoln504** [comment]
The drivers I'm using are from a unofficial Fedora repository called RPM Fusion, although i believe they are made directly from NVIDIAs, but like.. not totally sure. The current version I'm on is 430.40.

**Comment by Theverat** [comment]
You might have to contact the developers of those drivers for support.

**Comment by Lincoln504** [comment]
Sounds good, and thank you both for looking into the issue bit. Seems like there's not anything that can be done on our side, so I'll close this up 👍
