### ISSUE TITLE
Object with material is black on render

### ISSUE THREAD

**Issue by PetrTT** [LuxCoreRender/LuxCore#253]
Hi
Applying normal map on material with option 
NormalMap checked in texture panel makes black render
On preview is everything right
Luxcore Build 31.10
Win 7
Blender 2.81

![029](https://user-images.githubusercontent.com/20154959/68002643-d7e79980-fc7a-11e9-8d78-db969f214f59.png)
![028](https://user-images.githubusercontent.com/20154959/68002644-da49f380-fc7a-11e9-87ba-6b0a5751af39.png)

**Comment by Dade916** [comment]
Normal mapping is working fine here however I have the feeling it may be a problem in how BlendLuxCore exports the information. Can you post your test scene ?

P.S. as far as I remember the "Height" parameter is expressed in meters so 0.50 is a really huge values (i.e. half a meter).

**Comment by Theverat** [comment]
> P.S. as far as I remember the "Height" parameter is expressed in meters so 0.50 is a really huge values (i.e. half a meter).

No, it's the "scale" parameter of the normalmap texture: 
https://github.com/LuxCoreRender/LuxCore/blob/ec483005bf666848c7e7d824b90ba86bfc2a3d41/src/slg/textures/normalmap.cpp#L41
It is a relative scale, 1 means use the normalmap values unchanged, 0.5 means use half the height encoded in the normalmap.

**Comment by PetrTT** [comment]
[TEST.zip](https://github.com/LuxCoreRender/LuxCore/files/3800643/TEST.zip)  floor was make  as box
remaking as plane solved problem.Try to recreate old one but get another bug .If floor maked from box it has no glossy

**Comment by Dade916** [comment]
I'm trying your test scene:

![test](https://user-images.githubusercontent.com/3247881/68073854-a4992d80-fd94-11e9-9286-31729f334dd6.png)

It seems to work fine here, it looks like both normal mapping and glossy are there. Are you obtaining a different result ?

**Comment by PetrTT** [comment]
on the right side floor(plane) glossy is clear visible,reflections
on the left box does not any reflections but material is the same

**Comment by Theverat** [comment]
We still have this weird legacy behaviour in the glossy material where it's matte on the backface. We should remove this at some point.
@PetrTT the normals on the left are probably pointing down, try to recalculate them.

**Comment by Dade916** [comment]
Yes, that old Glossy material behavior is quite strange and unexpected.

@PetrTT, you can also use the Disney material for glossy surfaces, it is probably more user friendly than the old double-face glossy material.

**Comment by PetrTT** [comment]
Thanks.It works now well
