### ISSUE TITLE
Path OpenCL seems to use different seed every render

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#255]
Even when setting `renderengine.seed = 1`, Path OpenCL generates a different noise pattern each time a render is started. Path CPU doesn't show this problem.

OS: Windows 10
GPU: Nvidia RTX 2080
LuxCore version: 0a96233d56c2060aede3b2073a6539528e173f9d

Scene: [different_noise_ocl.zip](https://github.com/LuxCoreRender/LuxCore/files/3800332/different_noise_ocl.zip)

Path OpenCL, first render:
![ocl_1](https://user-images.githubusercontent.com/1584761/68069337-5158b800-fd5f-11e9-8d88-98f5dfb08b5a.png)

Path OpenCL, second render (noise pattern different):
![ocl_2](https://user-images.githubusercontent.com/1584761/68069338-5ddd1080-fd5f-11e9-903a-53f22bc95daf.png)

Path CPU, first render:
![cpu_1](https://user-images.githubusercontent.com/1584761/68069340-633a5b00-fd5f-11e9-82d0-24b4de8778a0.png)

Path CPU, second render (same noise pattern, just a few more samples):
![cpu_2](https://user-images.githubusercontent.com/1584761/68069342-6a616900-fd5f-11e9-95f4-83770a1002b5.png)

**Comment by Dade916** [comment]
This is normal, the process is deterministic only if you use one single thread. More threads you have and more room for differences there is (so it is very noticeable if PATHOCL where you have thousands of threads).
This pretty common in multi-thread applications where the order of operations is not deterministic (i.e. for instance the OS load will determine the order of threads picking up the work, the time to perform the some work, etc.).

To have a deterministic result, you would often need some kind of synchronization (i.e. slower performance.

**Comment by Theverat** [comment]
Ok, I see.
