### ISSUE TITLE
LuxCore v2.2: Brightness difference between Path OpenCL and Path CPU

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#257]
Reported by **Dez!**.

How to reproduce: 
* Open official Blender 2.80 with BlendLuxCore v2.2 installed and open this file:
  https://drive.google.com/file/d/1Tv7HFhW6papNMIVBGtqJtxLJ6UzlWwgN/view?usp=sharing
* Press F12, the OpenCL version will render
* After the render is done, switch to slot 2 in the image editor on the right
* change device to "CPU"
* Render again

You should obtain these results:

OpenCL:

![ocl](https://user-images.githubusercontent.com/1584761/68306647-39a86900-00aa-11ea-897f-8861fe0c6b8c.png)

CPU:

![cpu](https://user-images.githubusercontent.com/1584761/68306659-3d3bf000-00aa-11ea-9422-5d43907b3434.png)

I have not tried to debug this yet, it might be an addon issue, in which case we can move this issue to the BlendLuxCore repo.

**Comment by Dade916** [comment]
I should have fixed this problem.

**Comment by Theverat** [comment]
Do you think it would make sense to create a v2.2.1 bugfix release for fixes like this one, or will we release v2.3 so soon that we shouldn't bother?

**Comment by Dade916** [comment]
I'm not sure if we have a procedure for Azure to release v2.2.1, I think not. The bug is in since 16 July and it is triggered by mixing triangle lights with other types of light sources (otherwise it works fine).

I would prefer to  just aim to release the v2.3 before the end of the year.

**Comment by Theverat** [comment]
Ok. I have confirmed that it's fixed, so I'm closing this. Thanks!

**Comment by Dez1gner** [comment]
How do I get these fixes for version 2.2?

**Comment by acasta69** [comment]
> I'm not sure if we have a procedure for Azure to release v2.2.1, I think not.

I can check what we need to set up a v2.2.1 release.
Having the artifacts should be easy, it might be that we have then to set up the release in GitHub manually.
