### ISSUE TITLE
Render baking

### ISSUE THREAD

**Issue by Dade916** [LuxCoreRender/LuxCore#260]
Add to LuxCore the support for render backing. LuxCore has to be able to bake shaders and lighting to image maps.

The most common usage of this feature will be  to render the scene in real-time with a rasterization API (WebGL, OpenGL, DirectX, Vulkan, Metal, whatever).
They could also be used to speed up animation renderings with LuxCore (with a special material "baked" to use the generated image maps).

Use Blender render baking documentation as general reference for features and terms: https://docs.blender.org/manual/en/latest/render/cycles/baking.html

The implementation should generated the following type of maps:

- Combined: all lights, shadows, materials and textures is baked;
- Shadow (aka light map): only incoming lighting is baked.

In a future the support for the following 2 additional types may be added:

- Normals: baking normal map;
- Environment: baking the environment as seen from the center of the object (in order to be able to render specular objects, etc.).

The idea is to develop a new render engine, something named "BAKECPU", where the camera is ignored and instead a list objects to bake is passed in the configuration parameters. You can render a scene like usual but the output will be a set of image maps that you can than use for real-time rendering, etc.

The configuration should be an array of the following properties:

1) a list of object names to bake in the current map;
2) the type of map to bake (Combined, Shadow, etc.);
3) the index of the UV set to use for baking (after issue #134 as been implemented). One for each object listed;
4) the map file name;

Multiple maps should be generated in a single rendering in order to amortize the cost of scene parsing. Only CPU baking will be supported for the moment.

**Comment by provisory** [comment]
Somehow SDS caustics cache seems to be slow, if there would be a baked map for (non SDS) caustics, it could be used for fast SDS calculations, isn't it?
It would be the best if it could be calculated during the normal rendering.

**Comment by Dade916** [comment]
Yes, if I bake caustics too than they would be reflected on mirrors, refracted trough glass, etc. (i.e. SDS paths).
Baking is just another form of caching at the end of the day.

**Comment by provisory** [comment]
But could it be faster than current caching? 
I think that it could be, because these maps are two dimensional and has a fixed resolution, so no need for periodic cache clearing.

**Comment by Dade916** [comment]
This work has been completed with v2.3 release.

**Comment by qq553563608** [comment]
Hi , I use v2.3 release, everytime I try to bake the demo scene in scenes/bake/render-bake.cfg using LuxCore UI, I get an error in sobal.cpp line 214, assert failed. "index equals to requestedSamples" which expecting "less".  The samples index from 0 not 1, so the last one is 6 for 7 samples?

**Comment by qq553563608** [comment]
Hello, I [combined] bake a object with bump map, the result is a black baked image. I read the code , found that the bsdfSample in the first path vertext was always ZERO when the object with materials connected to bump map.

**Comment by Dade916** [comment]
I should have fixed this problem: https://github.com/LuxCoreRender/LuxCore/commit/1d46e34e1f658eecf0374abcd1de04ed58332a64
