### ISSUE TITLE
locale C.UTF-8 not available on all distros

### ISSUE THREAD

**Issue by omgold** [LuxCoreRender/LuxCore#263]
With the change from 3a40a2e49040a396c5753749dae0408edb076d38:

```
    std::locale::global(std::locale("C.UTF-8"));
```

the Python module fails to load, due to stdc++ raising an exception:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```

Apparently this locale is only available on some distros. While on Ubuntu and Fedora it works, it doesn't on Centos and Arch.

**Comment by Dade916** [comment]
Locale are a nightmare ... anyway, I have modified the code to use the "C.UTF-8" locale only if it is available. This should fix the problem.

**Comment by Dade916** [comment]
I assume it is now working fine.
