### ISSUE TITLE
Something wrong with Pointiness param

### ISSUE THREAD

**Issue by PetrTT** [LuxCoreRender/LuxCore#264]
![Test_2_81_lastLuxCoreBuild](https://user-images.githubusercontent.com/20154959/69897482-ca96fb00-135d-11ea-90ab-cb8201efafb4.png)
This is the test of pointiness example in 2.81 last build
![Test_2_80_tLuxCore_2_2](https://user-images.githubusercontent.com/20154959/69897503-f9ad6c80-135d-11ea-810b-b41695d59156.png)
and this is the test in 2.80 LuxCore 2.2 realease
Is it bug or regression in cod?

**Comment by Dade916** [comment]
I should have fixed the problem. The fix will be included in next automatic build.

**Comment by PetrTT** [comment]
Great news.Thank you very much
