### ISSUE TITLE
Pointiness strange behavior

### ISSUE THREAD

**Issue by PetrTT** [LuxCoreRender/LuxCore#265]
For Pointiness node 
If mesh has shade flat will be no visual changes
Only seting shade smooth will make to see result of pointiness node

**Comment by Dade916** [comment]
It is the expected be behavior: the pointiness is based on the curvature of the surface and, indeed, a flat surface has no curvature at all.

I'm not sure what kind of result you are aiming for but you may need to apply a small bevel at your edges and smooth them with auto-split. At that point you will get pointiness on the edges of your flat surfaces (I assume it is  the kind of result you are aiming for ?).

**Comment by PetrTT** [comment]
![001](https://user-images.githubusercontent.com/20154959/70375542-e414e580-190f-11ea-9697-38ab1dd8f7f6.png)

[TEST_Pointiness.zip](https://github.com/LuxCoreRender/LuxCore/files/3935113/TEST_Pointiness.zip)
I agree with you a flat surface has no curvature at all
But This examples will show exactly that i mean
In test file two Susanne heads one has option shading  flat another shading smooth
and with one material they show diffrent result

Truly main goal is achive layer weight effect for mesh or effect as Falloff Mat in 3ds Max

**Comment by Dade916** [comment]
I'm getting a very different rendering out of your scene:

![point](https://user-images.githubusercontent.com/3247881/70377795-e596db80-1918-11ea-90de-24fad8447ed4.jpg)

Have you posted the wrong scene ?

**Comment by PetrTT** [comment]
Tested this scene again 
It is exactly right scene
Really strange result as for me
Tested this bug on Win 7 and Linux Mint 19.2
Blender 2.81a
Luxcore Last build

**Comment by PetrTT** [comment]
![002](https://user-images.githubusercontent.com/20154959/70393078-9c698900-19f7-11ea-8ac4-ac7ee2bc2066.png)
may be this can helps

**Comment by Dade916** [comment]
Sorry, my fault, I had, installed in Blender, the old version where Pointiness was not working at all.

You seem to have the same problem Egert_Kanep had in this thread: https://forums.luxcorerender.org/viewtopic.php?f=4&t=1475&hilit=pointiness&start=10#p17318

He mentions a problem in the way Suzanne is subdivided.

I can confirm that exporting the Suzanne in your scene to a .obj file and importing back, fixes the problem:

![suz](https://user-images.githubusercontent.com/3247881/70429126-45f05f00-1a78-11ea-95dc-f12837630270.jpg)

Blender (or BlendLuxCore) may do something strange when exporting the mesh with a pending subdivision modifier (?).

**Comment by Theverat** [comment]
> Blender (or BlendLuxCore) may do something strange when exporting the mesh with a pending subdivision modifier (?).

Weird issue. Applying the subdivision modifier doesn't help. 
No duplicate vertices, no flipped normals.

**Comment by Dade916** [comment]
I assume we can close this one.
