### ISSUE TITLE
Blackbody normalize doesn't seem to work

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#267]
I implemented support for the new normalize option in BlendLuxCore, but it doesn't seem to make a difference, see the attached pictures.

[test_Emission2.zip](https://github.com/LuxCoreRender/LuxCore/files/3939521/test_Emission2.zip)

No blackbody texture:

![no_blackbody_tex](https://user-images.githubusercontent.com/1584761/70434516-b00f0100-1a84-11ea-80f8-66b98754f599.PNG)

With blackbody, normalize disabled:

![normalize_disabled](https://user-images.githubusercontent.com/1584761/70434519-b0a79780-1a84-11ea-971c-d272229ddb4e.PNG)

With blackbody, normalize enabled:

![normalize_enabled](https://user-images.githubusercontent.com/1584761/70434517-b00f0100-1a84-11ea-8e2b-44cf56841a23.PNG)

**Comment by Dade916** [comment]
> it doesn't seem to make a difference

It will keep the intensity of light constant **if you change the temperature**. It is explained here: https://forums.luxcorerender.org/viewtopic.php?f=4&t=1476#p17335

> - BlacBody(1000) = RGBColor[9581.77, 0, 0.000183105] (Red-ish)
> - BlacBody(6500) = RGBColor[66523.2, 63735.1, 67380.9] (White-ish)
> - BlacBody(10000) = RGBColor[32116.3, 37786.2, 54656.2] (Blue-ish)

(see, the intensity change a lot with the temperature, as expected, but normalization can be used to avoid that).

**Comment by Theverat** [comment]
But isn't the output also supposed to be in 0..1 range? So in the example images above, it should look like the first image?

**Comment by Dade916** [comment]
Yes, I should have fixed that problem.

**Comment by Theverat** [comment]
Thanks, confirmed.
