### ISSUE TITLE
Crash with DLSC

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#269]
OS: Windows 10
LuxCore version: 3631e1ae24aaa0bf179b991eb3f3f20ae985c595

Steps to reproduce:
* Open the following scene in Blender 2.8: [directlightcrash.zip](https://github.com/LuxCoreRender/LuxCore/files/3969520/directlightcrash.zip)
* Press F12

reported by Acrivec

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Dade916** [comment]
I assume we can close this one.
