### ISSUE TITLE
Stable random number per mesh island

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#282]
There's a feature request to have a random number per mesh island available for use in material shaders. It should be stable across session restarts (aka animation frames), which can be achieved by not using a RNG, but instead using a hash function on a seed value (passed in via property). In the Blender addon we would use the object's original name as seed.

Here is the implementation of this feature in Cycles: https://developer.blender.org/D6154

**Comment by juangea** [comment]
This is a very important feature to add randomization to complex objects that cannot be split to work with them, like wood planks or tiles, grass blades, etc...

**Comment by BennyGovaerts** [comment]
Any news about this option ; can this be included in the near future with Luxcore : 
![000 Screenshot_1](https://user-images.githubusercontent.com/49908008/76765631-ff0cb680-6796-11ea-9abc-adccfaaed8f7.png)

**Comment by Dade916** [comment]
This is under development here: https://forums.luxcorerender.org/viewtopic.php?f=5&t=1918&p=20898#p20896

**Comment by Dade916** [comment]
Done.
