### ISSUE TITLE
denoise binary not executable

### ISSUE THREAD

**Issue by metal3d** [LuxCoreRender/LuxCore#287]
Hi,
First of all, good job, LuxCoreRender is very efficient,  and can work with any OpenCL device: woow

Just one note, I saw an error in viewport for the denoiser "Permission denied". You should probably make something to set it executable if it's not. On my Fedora 31, I did:
```
chmod +x ~/.config/blender/2.81/scripts/addons/BlendLuxCore/bin/denoise 
```

And I finally see denoised preview in viewport.

**Comment by metal3d** [comment]
Ok, sorry, bad repository for the issue

**Comment by Dade916** [comment]
This should be probably in BlendLuxCore repository.
