### ISSUE TITLE
Problem exporting 10 million instances for OpenCL in latest BlendLuxCore

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/LuxCore#288]
With the latest BlendLuxCore addon (from 13/11/2020) if I try to export 10 million cubes instanced with particles It seems I run out of memory, when in theory I should not run out of memory.

![image](https://user-images.githubusercontent.com/20524718/72254190-991f7980-3603-11ea-9a6f-cf23171eb5c8.png)

`The Mesh description buffer is too big for GeForce GTX 1080 Intersect device (i.e. CL_DEVICE_MAX_MEM_ALLOC_SIZE=2127675392): try to reduce related parameters`

And it does not allows me to render it.

**Comment by juangea** [comment]
To reproduce it is as simple as opening this blend file and launching the render.
http://pasteall.org/blend/index.php?id=52769

**Comment by Dade916** [comment]
The OpenCL GTX driver is telling to LuxCore it can not allocate a single block of memory larger than 2GB. You are not running out of GPU memory but your GPU is just unable to allocate a single chunk of memory larger than 2GB.

In the past, GPUs has some severe limitation there because memory was accessed like if it was a texture map (for instance the AMD HD 5870 had an horrible limit of 256MB).

LuxCore splits large memory blocks to work around this problem. However this is done only for most common large blocks, like triangles or image maps related memory blocks (usually up to 8 blocks can be created).

Mesh descriptions memory block is not one of them. They are all allocated in a single block of memory.

A Mesh (aka object) description requires 244 bytes so you have effectively a limit on the total number of objects you can use in a scene with your GPU of 2,127,675,392 / 244 = 8,719,981 objects.

The most obvious work around is usually merge objects together in a single mesh (i.e. works with a tile of grass instead of a single blade).

I could reduce the mesh description structure size and/or split the structure however it is not a trivial amount of work and I'm not sure how often this limit is going to be hit: I run out of 32GB of CPU ram before being able to hit the 2GB limit on my RTX 2070 Super.

**Comment by Theverat** [comment]
We often have the case that a single object is instanced thousands of times, and only the transformation matrix and object ID differs between them. Name is irrelevant, and all instances in such a group use the same material and mesh.

Would it be possible to create an optimized data structure for this situation?
Maybe a class that stores the following:
* Pointer to material
* Pointer to mesh
* Single name string for the whole thing
* Array of transformations
* Array of times (for motion blur)
* Array of object IDs (for per-instance randomization in materials)

**Comment by Dade916** [comment]
I'm talking of slg::ocl::ExtMesh: https://github.com/LuxCoreRender/LuxCore/blob/c9040b072c719e6c4e82fdd25d5ae597731aa9c9/include/luxrays/core/exttrianglemesh_types.cl#L35

I have the feeling you are talking of slg::SceneObject.

**Comment by Theverat** [comment]
Ah, indeed.
Can something similar be done there?

**Comment by juangea** [comment]
Mmm one situation where this limit can be easily reached is when working with particles, 10 million is not too much if you want to render sand or water foam, is there a way to improve this? we often can surpass 10 million objects in a big scene, no just owrking with a blade of grass, we work with patches, but the aount of particls, objects and other things that scene can need may be bigger than 10 million.

in this scene we have more than 10 million objects between all the vegetation, decoration, people, grass, and a big etc... 

https://vimeo.com/366900975

And there is no way to separate the project in smaller scenes, too much human work for very few improvement.

**Comment by juangea** [comment]
BTW this could be very good, because based on my recent tests, the optimizations B.Y.O.B. did in BlendLuxCore resulted in faster export for particles than cycles :D 

Maybe the solution is to have a custom particles object that can store everything, so a set of grass particles can be trated as one object with a bunch of instanced goemetry inside. I've been talking about this with B.Y.O.B. this morning :)

**Comment by Dade916** [comment]
I have investigated a bit the problem and apparently the NVIDIA driver is just lying. The reported CL_DEVICE_MAX_MEM_ALLOC_SIZE is not an hardware limit anymore.

I have transformed original LuxCore error in a warning:

> [LuxRays][0.299] WARNING: the SampleData buffer is too big for GeForce RTX 2070 SUPER Intersect device (i.e. CL_DEVICE_MAX_MEM_ALLOC_SIZE=2086633472)

So it will try to allocate more memory even if the size is greater than CL_DEVICE_MAX_MEM_ALLOC_SIZE. It works pretty much up to the total amount of GPU memory available on my RTX.
If you try to allocate more memory of what is physically available, you will get an error just at the first kernel execution.

**Comment by juangea** [comment]
ok, that's great, I'll test it, awesome!

**Comment by juangea** [comment]
@Dade916 @Theverat is this already in the latest BlendLuxCore compilation?

**Comment by Theverat** [comment]
No, the LuxCore build is still compiling/testing. Once the [orange dot near the top commit](https://github.com/LuxCoreRender/LuxCore/commits/master) turns into a checkmark, the BlendLuxCore build will be started and is usually done after 10-15 minutes.

**Comment by juangea** [comment]
Awesome, Thanks :)

**Comment by juangea** [comment]
Ok, I tested 20 million instanced and I maxed out the GPU ram, but no error :) 

![image](https://user-images.githubusercontent.com/20524718/72357193-d90d5c00-36ea-11ea-96c4-d3d20e167d59.png)

As I said before, could be a good idea to have a particle object that treats particles slightly different, as a single object or mesh or something like that, but I'll create a feature request regarding particles :)

**Comment by Dade916** [comment]
Out of curiosity, rendering the same scene with Cycles how much GPU memory does it require ?

**Comment by juangea** [comment]
I'm testing that, OPTIX has been unable to render it so far, this was the error, it seems it's being able to do that with 15 millions, I'll test 15 millions later with lux too and post the result here:
```
Failed to build OptiX acceleration structure
OptiX error OPTIX_ERROR_INVALID_VALUE in optixAccelComputeMemoryUsage(context, &options, &build_input, 1, &sizes), line 1170
```

**Comment by juangea** [comment]
15 million OPTIX, around 4 minutes 11 seconds to start the render, memory as I show here:

![image](https://user-images.githubusercontent.com/20524718/72358019-348c1980-36ec-11ea-992f-d18a58752772.png)

**Comment by Dade916** [comment]
Thanks, I guess we are more or less on track. Going to close this for the moment.

**Comment by juangea** [comment]
I hope leaving a comment here don't reopen this, I just want to give you a reference point:

Export Time: 3 minutes 26.7 Seconds
Session Init: 40.7 seconds
Memory: 5756Mb

![image](https://user-images.githubusercontent.com/20524718/72358612-238fd800-36ed-11ea-8551-4efb55301c83.png)

In conclussion, the memory I'm not sure what should I take into account from Cycles, the mem or the peak, but if it's the peak is similar, but the export time is lower than the cycles one, congrats @Dade916 and @Theverat !!!!

**Comment by Theverat** [comment]
Is that memory stat in Blender the GPU memory usage though? I was under the impression that it's the CPU RAM.
I would check the GPU memory usage in the task manager instead.
