### ISSUE TITLE
Missing libblosc.so.1 in latest prerelease linux64-opencl tarball

### ISSUE THREAD

**Issue by justinclift** [LuxCoreRender/LuxCore#289]
Just downloaded the "latest" prerelease linux64-opencl tarball, then attempted to run it with the default scene:

```
./luxcoreui scenes/cornell/cornell.cfg 
./luxcoreui: error while loading shared libraries: libblosc.so.1: cannot open shared object file: No such file or directory
```

Guessing the build script (or similar) needs updating to include the `libblosc.so.1` library?

As a data point, the v2.2 release tarball runs fine. :smile:

**Comment by neo2068** [comment]
Blosc should be linked statically together with Openvdb.  In the Cmakelists.txt there are no linking libraries defined for static luxcore library [code](https://github.com/LuxCoreRender/LuxCore/blob/e563a78956a1ec85cb8831d70bc0083062703834/src/luxcore/CMakeLists.txt#L155), while for pyluxcore there is a target_link_libraries, [code](https://github.com/LuxCoreRender/LuxCore/blob/e563a78956a1ec85cb8831d70bc0083062703834/src/luxcore/CMakeLists.txt#L183)
. Is this correct? BTW, on windows it works correctly for luxcoreui...

**Comment by Dade916** [comment]
I'm fixing the problem. C-blosc was linked with the .so and even if I was forcing the link with the .a, the pre-compiled .a binary was compiled without -fPIC so it was not usable to compile pyluxcore.so among other things.

I recompiled c-blosc binaries with -fPIC and I'm updating everything.

**Comment by Dade916** [comment]
Done, the next build should be fine: https://dev.azure.com/LuxCoreRender/LuxCoreRender/_build/results?buildId=1389&view=results

**Comment by justinclift** [comment]
Yep, just tried the latest build as of today and it works.  Good stuff! :smile:
