### ISSUE TITLE
Mesh sometimes black after subdivide + displace via shapes

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#291]
OS: Windows 10
LuxCore version: 32b117b1343285a3c64d3427a77865790421f946

Scene: [subdiv_disp_black_mesh_LuxCore.zip](https://github.com/LuxCoreRender/LuxCore/files/4087484/subdiv_disp_black_mesh_LuxCore.zip)

The mesh in this scene appears black sometimes, sometimes it works correctly, and sometimes Blender crashes on render startup.
It may be caused by uninitialized memory, as this has affected our Windows builds more strongly than the Linux builds in the past.

Black mesh:

![subdiv_disp_black_mesh](https://user-images.githubusercontent.com/1584761/72745660-803d3800-3bb0-11ea-966f-ba5aaf602e1a.png)

How it should look like:

![subdiv_disp_mesh_working](https://user-images.githubusercontent.com/1584761/72745666-84695580-3bb0-11ea-9b9f-683289e749d1.png)

Node setup:

![Capture](https://user-images.githubusercontent.com/1584761/72745674-8a5f3680-3bb0-11ea-8907-c2428e06696f.PNG)

**Comment by Dade916** [comment]
And the scene ?

**Comment by juangea** [comment]
It's easy to reproduce, I just go up a lot in subdivisions and then the mesh is total black, I'll try to prepare the example, but the node setup @Theverat showed here should give the problem :)

**Comment by Theverat** [comment]
> And the scene ?

Sorry, forgot it, added it to the first post: https://github.com/LuxCoreRender/LuxCore/files/4087484/subdiv_disp_black_mesh_LuxCore.zip

**Comment by juangea** [comment]
I was trying to reproduce it with your same node tree but I've been inable, it may depend on the computer or hardware, I'll keep trying because I suffered this, specially if I use a big number in subdivision or a slow number in edge screen size

**Comment by Dade916** [comment]
There about 1000 uninitialized vertices at the end of subdivided mesh vertex list. So when they are 0.0 the Bounding Box of the mesh will be normal while, when they are garbage memory, the Bounding Box will be nearly infinite.
As result the scene radius will be infinite and the power emitted by the constant infinite light source will be infinite too and the rendering will be just black.

I'm tracking where all that uninitialized vertices are coming from.

**Comment by Dade916** [comment]
I should have fixed the problem.

P.S. OpenSubdiv is some of the most convoluted and obscure API I ever used.

**Comment by Theverat** [comment]
Thanks!
