### ISSUE TITLE
How to achieve constant brightness with varying theta for distantlight?

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#298]
Is it possible with the current distantlight to use different thetas, but counteract the brightness changes to keep the end result at the same brightness level? (I'm speaking of the brightness on a surface hit by the light)

Is it possible to do this "from outside" by changing the gain property according to some formula, or would it require changes in LuxCore source code?

**Comment by Dade916** [comment]
Yes, if you multiply the gain for:

```
cosThetaMax = min(cos(radians(theta)), 1.f - epsilon);
gain *= 1.f / (2.f * M_PI * (1.f - cosThetaMax))
```
where theta is the angle in degree, you will get constant light brightness for any theta.

You could add a normalize flags to enable this behavior.

**Comment by Theverat** [comment]
Awesome, it works, thanks!
