### ISSUE TITLE
Material rendered black on non-instanced object, correct if object is instanced

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#300]
Reported by Max from Insertcoin.tv.

LuxCore version: v2.3beta1
Scene: [black_material.zip](https://github.com/LuxCoreRender/LuxCore/files/4159343/black_material.zip)

Steps to reproduce:
* Start a viewport render. The object will be instanced by BlendLuxCore and everything works fine
* Start a final render. The object will not be instanced anymore and appear black

I have a feeling there might be NaNs involved here, possibly caused by some of these factors:
* The object has a negative scale of -0.385706 along the Z axis (when the scale is applied in Blender, the problem vanishes)
* A bump map is used on the object (when the bump map is removed, the problem vanishes)

Viewport render, object instanced:

![viewport_instanced](https://user-images.githubusercontent.com/1584761/73840619-da790280-4818-11ea-91a9-64d976e69860.PNG)

Final render, object not instanced:

![final_render_not_instanced](https://user-images.githubusercontent.com/1584761/73840644-e49b0100-4818-11ea-97a3-a89fb10a7da1.png)

**Comment by Dade916** [comment]
The problem may be in BlendLuxCore (or in the LuxCore export process). Try to do this test:

1) use FILESAVER to export the scene with +Z scale

2) use FILESAVER to export the scene with -Z scale

3) now import the 2 mesh .ply files inside Blender and check the normals: they point in the same direction (while they should be flipped in one case).

So the problem may be in the process of exporting normals when Z scale is negative (?)

**Comment by Theverat** [comment]
You mean somewhere in here? https://github.com/LuxCoreRender/LuxCore/blob/ab1c6c65f7483f7aad50f020b6a4eb1c233da6cd/src/luxcore/pyluxcoreforblender.cpp#L673

Or maybe in https://github.com/LuxCoreRender/LuxCore/blob/09fc1058f148a946248c5f8ce2ce994ab5cc238c/src/luxrays/core/exttrianglemesh.cpp#L249

However, even with normals pointing to the wrong side, why would the mesh be black? Wouldn't that be like looking at it from the other side?

**Comment by Dade916** [comment]
I should have fixed the problem: the transformation was swapping the handiness of reference system.

**Comment by Theverat** [comment]
Confirmed, thanks!
