### ISSUE TITLE
New OCL mat/tex code: Discrepancy in mix amount between CPU and OCL

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#302]
LuxCore version: fd5b9ab5bd0a742362e54f2d0eca79a5d48db110
Scene: [discrepancy.zip](https://github.com/LuxCoreRender/LuxCore/files/4237705/discrepancy.zip)
GPU: Nvidia RTX 2080

The mix material in the OpenCL engine seems to treat the mix amount wrong.
In the example I used a blend texture to get a transition from 0 to 1, but it happens with any texture used as mix amount input.

Path CPU:

![discrepancy_cpu](https://user-images.githubusercontent.com/1584761/75065019-48dfe500-54e8-11ea-9632-f7a7b0a31cfa.png)

Path OpenCL:

![discrepancy_ocl](https://user-images.githubusercontent.com/1584761/75065034-4ed5c600-54e8-11ea-8c79-9bafb2ab268a.png)

**Comment by Dade916** [comment]
Strange, it works fine with Intel OpenCL while it shows this problem with NVIDIA. I'm trying to figure out what is going on.

**Comment by Dade916** [comment]
Ok, I should have fixed the problem.

**Comment by Theverat** [comment]
Nice!
