### ISSUE TITLE
luxcoreconsole missing from release tarballs

### ISSUE THREAD

**Issue by nergdron** [LuxCoreRender/LuxCore#304]
The README included in releases mentions a `luxcoreconsole`, presumably to do things like run headless rendering servers like in luxrender 1.x. However, this seems to be missing from recent release tarballs for linux, and the included tools seem to require a gui. including this in the releases again, or updating the readme to describe headless rendering operation, would be very appreciated.

**Comment by Dade916** [comment]
Luxcoreconsole executable is included in SDK release. The same tool is available as part of Python pyluxcoretools. It is one of the command available: run "python3 pyluxcoretools help" for some information.

**Comment by nergdron** [comment]
oh, great! I guess this is just a req for an update to the readme then calling that out. thanks! :)
