### ISSUE TITLE
RTPATHOCL resolutionreduction broken

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#305]
LuxCore version: e7dd877bfa32a1001d33a611f0b5116b5e08e042

Steps to reproduce:
* Open Blender scene: [ocl_viewport.zip](https://github.com/LuxCoreRender/LuxCore/files/4258732/ocl_viewport.zip)
* Set viewport shading mode to "rendered" (top right corner)

If `rtpath.resolutionreduction.preview` is set to a value > 1, LuxCore slowly fills in the pixels in a block instead of the old behaviour of filling the whole tile with the first sample, then blending to the next finer-sampled pass.

Here's a video showing the broken behaviour:
https://youtu.be/M556o_kxYuk

![Capture](https://user-images.githubusercontent.com/1584761/75398100-f6903100-58f8-11ea-916d-44da6d6b9d23.PNG)

Note: I'm using these other properties of resolutionreduction:
`rtpath.resolutionreduction.step = 1`
`rtpath.resolutionreduction = 1`
The related BlendLuxCore code is here: https://github.com/LuxCoreRender/BlendLuxCore/blob/8823b7d1c54ba234d54849d79a528b03970e9fb3/export/config.py#L188

**Comment by Dade916** [comment]
But v2.3 or v2.4 sources ?

**Comment by Theverat** [comment]
v2.3.

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
I downloaded the latest build with OCL for Windows and I can't really confirm this.
The tiles are now filled with the first sample and no longer black, but the following "filling in" happens in the same slow and pixel-by-pixel way as before, whereas the render is much faster with `rtpath.resolutionreduction.preview = 1`.

Video of the new situation: https://youtu.be/G6fPKboTeCY?t=4
(unchecking "reduce first sample resolution" is setting `rtpath.resolutionreduction.preview` to 1)

**Comment by Dade916** [comment]
Ok, I fixed a second problem in RTPATHOCL.

**Comment by Theverat** [comment]
Thanks, looks like it's back to the old behaviour now.
