### ISSUE TITLE
Is it planned to rework mix material bump behaviour in OpenCL?

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#307]
I mean the fact that for OpenCL, bump maps have to be plugged directly into the mix material, and won't work when plugged into one of the sub-materials.
Do you plan to rework this?

I'm asking because if it's not planned, I'd like to implement a "behind the scenes fix" in BlendLuxCore that works around this behaviour so the user won't have to care about this difference anymore.

**Comment by Dade916** [comment]
Yes, it is.

**Comment by Theverat** [comment]
Great to hear!

**Comment by Dade916** [comment]
I will keep this open to remember the topic.

**Comment by mjutrzenka** [comment]
keep in mind that plugging the bump to the other node.. dosn't really solve the problem it is just forcing bump on all stuff.. instead of just node that should have it.. 

i made special test sceen to test it. 
https://github.com/LuxCoreRender/LuxCore/issues/319

**Comment by Dade916** [comment]
Note: this is true both for mix and glossycoatting.

**Comment by Dade916** [comment]
Now Glossycoating material on GPUs now supports bump mapping exactly like CPU version.

Mix material will follow soon.

**Comment by Dade916** [comment]
Mix material on GPUs now supports bump mapping exactly like CPU version:

![image](https://user-images.githubusercontent.com/3247881/79116041-b9d4a800-7d87-11ea-9bb9-2e20cffcfa57.png)
