### ISSUE TITLE
Camera Background Image is not working with OpenCl pipeline

### ISSUE THREAD

**Issue by Asticles** [LuxCoreRender/LuxCore#310]
Camera Background Image is not working with OpenCl pipeline enabled.

This happens when Use OpenCL is enabled:
![Screenshot - 18_03_2020 , 12_28_38](https://user-images.githubusercontent.com/25231467/76956284-05746d00-6914-11ea-847c-315e9b8b7d4e.png)

When OpenCL is disabled:
![Screenshot - 18_03_2020 , 12_29_48](https://user-images.githubusercontent.com/25231467/76956364-2c32a380-6914-11ea-96b5-0bf7d1d9cb75.png)

Blend File:
[Background_image.zip](https://github.com/LuxCoreRender/LuxCore/files/4348689/Background_image.zip)

**Comment by Theverat** [comment]
Here's the terminal output:

![Screenshot_-_18_03_2020__10_58_01](https://user-images.githubusercontent.com/1584761/76956795-00fc8400-6915-11ea-8c63-bba5639dcb1c.png)

**Comment by Dade916** [comment]
I have already fixed this problem on this branch: https://github.com/LuxCoreRender/LuxCore/tree/luxrays_new_hardwaredev

**Comment by Theverat** [comment]
@Asticles Which LuxCore version are you using? v2.3 stable or the latest daily build?

**Comment by Dade916** [comment]
The branch with the fix has been merged with the main branch.
