### ISSUE TITLE
compile with MinGW on windows

### ISSUE THREAD

**Issue by hwangsong** [LuxCoreRender/LuxCore#314]
Has anyone tried compiling with MinGW on windows？

**Comment by Dade916** [comment]
No as far as I know. The main problem is always to compile all dependencies. If you can use pre-compiled VisulaStudio libraries (https://github.com/LuxCoreRender/WindowsCompileDeps) it may be a doable task otherwise it is likely to be nightmare.

**Comment by hwangsong** [comment]
> No as far as I know. The main problem is always to compile all dependencies. If you can use pre-compiled VisulaStudio libraries (https://github.com/LuxCoreRender/WindowsCompileDeps) it may be a doable task otherwise it is likely to be nightmare.

Now I have compiled most of the third-party libraries, but there is a problem when running luxcore, and the analysis problem looks like a problem with the compiler's linker.

non-virtual thunk to luxrays::ExtMotionTriangleMesh::GetGeometryNormal(luxrays::Transform const&, unsigned int) const 0x0000000000e1b228
slg::HitPoint::Init(bool, bool, slg::Scene const&, unsigned int, unsigned int, luxrays::Point const&, luxrays::Vector const&, float, float, float) 0x0000000000694cb5
slg::BSDF::Init(bool, bool, slg::Scene const&, luxrays::Ray const&, luxrays::RayHit const&, float, slg::PathVolumeInfo const*) 0x00000000005e3da6
slg::Scene::Intersect(luxrays::IntersectionDevice*, int, slg::PathVolumeInfo*, float, luxrays::Ray*, luxrays::RayHit*, slg::BSDF*, luxrays::RGBColor*, luxrays::RGBColor const*, slg::SampleResult*, bool) const 0x0000000000581ef4
slg::PathTracer::RenderEyePath(luxrays::IntersectionDevice*, slg::Scene const*, slg::Sampler*, slg::EyePathInfo&, luxrays::Ray&, luxrays::RGBColor const&, std::vector<slg::SampleResult, std::allocator<slg::SampleResult> >&) const 0x00000000005ede5e
slg::PathTracer::RenderEyeSample(luxrays::IntersectionDevice*, slg::Scene const*, slg::Film const*, slg::Sampler*, std::vector<slg::SampleResult, std::allocator<slg::SampleResult> >&) const 0x00000000005ef025
slg::PathTracer::RenderSample(slg::PathTracerThreadState&) const 0x00000000005f11b2
slg::PathCPURenderThread::RenderFunc() 0x000000000052fe5b
boost::(anonymous namespace)::thread_start_function(void*) 0x000000006964218a
msvcrt!_beginthreadex 0x00007ffc3184b0ea
msvcrt!_endthreadex 0x00007ffc3184b1bc
KERNEL32!BaseThreadInitThunk 0x00007ffc30597974
ntdll!RtlUserThreadStart 0x00007ffc3194a271
<unknown> 0x0000000000000000

**Comment by Dade916** [comment]
It is this method: https://github.com/LuxCoreRender/LuxCore/blob/fcc1c074efc527f5e7054dd2cb2d35c85b8f29ba/include/luxrays/core/exttrianglemesh.h#L515

What test scene are you using ? Does scenes/cornell/cornell.cfg work ? It doesn't uses motion blur like the scene you seem to use for the test.

Are you using GCC ?

**Comment by hwangsong** [comment]
> It is this method:
> 
> https://github.com/LuxCoreRender/LuxCore/blob/fcc1c074efc527f5e7054dd2cb2d35c85b8f29ba/include/luxrays/core/exttrianglemesh.h#L515
> 
> What test scene are you using ? Does scenes/cornell/cornell.cfg work ? It doesn't uses motion blur like the scene you seem to use for the test.
> 
> Are you using GCC ?

The test scene is bigmonkey/bigmonkey-motion.cfg and bigmonkey-vol.cfg

I'm using MinGW on Windows10 64bit
