### ISSUE TITLE
Difference in shading normal orientation between CPU and OpenCL

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#317]
Originally reported by Sharlybg: http://forums.luxcorerender.org/viewtopic.php?f=5&p=21073#p21072
LuxCore version: v2.4alpha0
OS: Ubuntu 19.10
GPU: Nvidia RTX 2080

Scene: [mix_mat_difference.zip](https://github.com/LuxCoreRender/LuxCore/files/4389898/mix_mat_difference.zip)

Steps to reproduce:
* Render once on CPU, then switch the render slot (e.g. by pressing 2)
* Switch to OpenCL, render again
* The results will be different

Notes:
* The scene contains materials that use `Dot(shadingNormal, (0, 1, 0))` to texture parameters
  * When used on the diffuse color of a matte material, the result is the same on CPU and OpenCL
  * But when used as mix amount in a mix material, the result on OpenCL looks like (1, 0, 0) was used as second parameter of the dot product
  * Likewise, there is a difference when used in the glossycoating material

CPU, mix material amount:

![mix_cpu](https://user-images.githubusercontent.com/1584761/77696239-52f47800-6fad-11ea-9c76-c9e139b8d1a8.png)

OpenCL, mix material amount:

![mix_ocl](https://user-images.githubusercontent.com/1584761/77696673-08bfc680-6fae-11ea-9665-7620b86b20e3.png)

CPU, matte diffuse color:

![matte_cpu](https://user-images.githubusercontent.com/1584761/77696693-12492e80-6fae-11ea-8fbb-f92d50d4ac5e.png)

OpenCL, matte diffuse color:

![matte_ocl](https://user-images.githubusercontent.com/1584761/77696710-18d7a600-6fae-11ea-9e0d-f27c2d3c960d.png)

**Comment by Dade916** [comment]
I should have fixed this problem.

**Comment by Theverat** [comment]
Confirmed, thanks.
