### ISSUE TITLE
Linking cycles assets. Renders as white diffiuse.

### ISSUE THREAD

**Issue by mjutrzenka** [LuxCoreRender/LuxCore#323]
Simple.. when u link to lux project a cycles asset for example collection of object with cycles materials... it renders as white diffiuse. blender 2.82 x 2.3 lux

**Comment by Theverat** [comment]
If the assets have no LuxCore materials and are not using the "use cycles nodes" checkbox, this is the correct behaviour.

**Comment by mjutrzenka** [comment]
if u link asset.. u don't have material tab so there is no use cycles node checkbox to click... as it is empty. so yeah it is a bug. there should be in such situation special checkbox or automaticly enabled for ale linkined stuff.

**Comment by Theverat** [comment]
You have to open the original asset .blend, change the settings there, save and then link it in.

**Comment by Theverat** [comment]
I see your point though, it makes sense to use the Cycles node tree if no Lux node tree exists for a linked-in material. I have implemented this in 77f3c76e55c2ffc5f9a4d55de76b6db46acc5f60.
