### ISSUE TITLE
The orthographic camera does not respect caustics cache

### ISSUE THREAD

**Issue by Noah-ok** [LuxCoreRender/LuxCore#324]
basically the orthographic camera does not show the SDS paths or draws them badly on diffuse surfaces .(I don't know if it says drawn)
<a href="https://imgbb.com/"><img src="https://i.ibb.co/6WqqTRN/2020-03-31-163936.png" alt="2020-03-31-163936" border="0"></a>

perspective camera
<a href="https://ibb.co/Bzxwm6Z"><img src="https://i.ibb.co/0DSQk9M/untitled.png" alt="untitled" border="0"></a>

orthographic camera
<a href="https://ibb.co/C9cm2rL"><img src="https://i.ibb.co/WzhGtTC/untitled1.png" alt="untitled1" border="0"></a>

Poorly drawn cache
<a href="https://ibb.co/ypbVK7s"><img src="https://i.ibb.co/5kf2Cwc/untitled3.png" alt="untitled3" border="0"></a>
<a href="https://ibb.co/dKwzhqN"><img src="https://i.ibb.co/Sv49L8k/Anotaci-n-2020-03-31-033640.png" alt="Anotaci-n-2020-03-31-033640" border="0"></a>
<a href="https://ibb.co/b3W2qYJ"><img src="https://i.ibb.co/vBwQgfY/Anotaci-n-2020-03-31-173708.png" alt="Anotaci-n-2020-03-31-173708" border="0"></a>

Also note that the clamping values ​​of the 2 chambers are different.

perspective camera
<a href="https://imgbb.com/"><img src="https://i.ibb.co/SyXq9P5/Anotaci-n-2020-03-31-174605.png" alt="Anotaci-n-2020-03-31-174605" border="0"></a>

orthographic camera
<a href="https://imgbb.com/"><img src="https://i.ibb.co/bvhVzQ1/2020-03-31-175052.png" alt="2020-03-31-175052" border="0"></a>
I don't know if it's a bug but there it is.

**Comment by Dade916** [comment]
I should have fixed this problem.

It was about automatic cache radius estimation of PhotonGI when using Orthographic camera and it was affecting all type of caches.
