### ISSUE TITLE
Orthographic camera bug

### ISSUE THREAD

**Issue by wasd** [LuxCoreRender/LuxCore#327]
[https://forums.luxcorerender.org/viewtopic.php?f=4&t=1970](https://forums.luxcorerender.org/viewtopic.php?f=4&t=1970)
![Image ](https://forums.luxcorerender.org/download/file.php?id=7365&mode=view)

**Comment by Dade916** [comment]
You have a large scene and it is very far from the origin. FP32 precision is lower and lower more is the distance form the origin and you have the lens very near the camera too. I assume, you are just observing a numerical precision problem.
