### ISSUE TITLE
Can eye tracing be disabled for paths done by light tracing?

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#329]
I often have reflections that are rendered super clean by light tracing with few samples, but since eye tracing also attempts to render them (and is very inefficient at it), they are riddled with fireflies from the eye tracing.

Could eye tracing of these paths be disabled when hybridbackforward is used?

Example scene: [light_tracing.zip](https://github.com/LuxCoreRender/LuxCore/files/4432253/light_tracing.zip)

Eye + light tracing:
![eye+light](https://user-images.githubusercontent.com/1584761/78459159-68f1ef00-76b7-11ea-8013-45c0c2dc5ad4.png)

Light tracing only:
![light_only](https://user-images.githubusercontent.com/1584761/78459161-7018fd00-76b7-11ea-9b5a-4fb9d095602a.png)

Eye tracing only:
![eye_only](https://user-images.githubusercontent.com/1584761/78459166-760ede00-76b7-11ea-8307-bdfac583da99.png)

**Comment by Dade916** [comment]
> I often have reflections that are rendered super clean by light tracing with few samples, but since eye tracing also attempts to render them (and is very inefficient at it), they are riddled with fireflies from the eye tracing.

It is already supposed to be like that however there was a bug causing a misclassification of some kind of path. I should have fixed the problem:

![RGB_IMAGEPIPELINE_0](https://user-images.githubusercontent.com/3247881/81073368-d2982f80-8ee7-11ea-9767-378d56240619.png)

**Comment by Theverat** [comment]
Great, thanks!
