### ISSUE TITLE
DirectDiffuse and IndirectDiffuse passes are completely black

### ISSUE THREAD

**Issue by evacnoc** [LuxCoreRender/LuxCore#333]
DirectDiffuse and IndirectDiffuse passes are completely black.
Glossy passes (direct and indirect contain diffuse information)

LuxCoreRender v2.4 beta

**Comment by Theverat** [comment]
I can not reproduce this. Can you post a testscene?

**Comment by evacnoc** [comment]
Here is a testscene and the passes I get.
[bug issue 333.zip](https://github.com/LuxCoreRender/LuxCore/files/4475095/bug.issue.333.zip)

**Comment by Theverat** [comment]
You are using only disney/principled materials, which are of "glossy" type in LuxCore.
In LuxCore, the glossy AOVs only contain glossy materials, the diffuse AOVs only diffuse materials like matte, etc.
This is different from Cycles.

**Comment by evacnoc** [comment]
Okay, now I understand. Thanks for looking at it. I guess I can close it now.
