### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by nkundtz** [LuxCoreRender/LuxCore#335]
NOTE: I was able to find a work around for the reported error, but thought it would be helpful to post anyway. I will post issue and then respond to it with the work around I found.

I'm having some trouble getting LuxCore to compile (Ubuntu 18.04). Following the instructions here: https://wiki.luxcorerender.org/Compiling_LuxCore. Seems to be some issue with python/boost based on message boards; but I'm a few hours into trying to figure this out with no luck.

The error is: "./boost/python/detail/wrap_python.hpp:57:11: fatal error: pyconfig.h: No such file or directory
 "# include <pyconfig.h>""

but it seams to find python just fine earlier in the compilation:" * Using Python library path: /home/nathan/repositories/LinuxCompile/target-64-sse2/lib/libpython3.7.a
 * Using Python include path: /usr/include/python3.6m"

Has anyone ran into this?

**Comment by nkundtz** [comment]
It turned out that the gcc compiler (separate cmake command?) was getting an incorrect directory for the python include path (something different than where the compiler said it was looking). I couldn't find the offending code in the scripts but I was able to circumvent it by creating a dynamic link from the wrong place to the right one.

**Comment by Dade916** [comment]
Ubuntu has 2 versions of python installed (v2.7 and v3.x), it may the source of the problem. The other point is "pyconfig.h" is not part of default installation but it requires to install a python-dev package.

**Comment by nkundtz** [comment]
Yes. In my case I also have Anaconda installed with a series of environments (this is a really handy way to manage the version of python used by blender for different projects that need different packages). Somehow the Lux compiler script was finding the anaconda folder, but not pointing to the correct location in it. Specifically it assumed that there was a folder $(BASEDIR)/include/python3.7. In Anaconda (and standard python install his folder is actually called $(BASEDIR)/include/python3.7m. In the standard install /usr/include/python3.7 is a virtual link with that name to /usr/include/python3.7m. I had to recreate that structure in Anaconda to get it to work.

So really two potential improvements to consider in the install script here: (1) The compile script is finding and using an Anaconda instance of python for part but not all of the compilation process (and not notifying the user when it switches). It's not getting that from PYTHONPATH (which is not set on my system) or similar environment variables so I'm not sure where this happens. Is it possible to have a consistent the python location used throughout the make process? and (2) It might be good to check for a directory "python3.7m" if "python3.7" does not exist since "python3.7m" seems to be the folder that is actually being used by both the standard install and Anaconda.

Best,
Nathan

**Comment by Dade916** [comment]
Feel free to submit a pull request if you have an improvement of the current scripts. We lack a dedicated Linux maintainer at the moment (i.e. I just keep care of Linux support but it is not one of my top priorities). I assume I can close this one for the moment.
