### ISSUE TITLE
Preview rendering in BiDir mode is interrupted when moving the camera (and other interactions)

### ISSUE THREAD

**Issue by SteffenDuenner** [LuxCoreRender/LuxCore#337]
.blend file: 
[Laser_v04.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4480969/Laser_v04.blend.zip)

Steps to reproduce:
- Open the attached file and switch the 3D viewport to "Rendered" mode.
- Rendering starts
- Move or rotate the camera. Rendering stops.
Even just left-clicking inside the 3D viewport to set the 3D cursor stops the rendering.
- Switch the render mode to "Path". Everything works as expected. You can move the camera without interrupting the render process.

OS: Linux Mint 19.3
Blender version: Latest 2.83 (buildbot)
LuxCore version: Latest from https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest

**Comment by SteffenDuenner** [comment]
> It seems to be a bug in LuxCore, it also happens in luxcoreui.

Good to know. This is a quite new issue. I remember that around two weeks ago it worked.

**Comment by Dade916** [comment]
I should have fixed the problem, it was a regression due to a fix of another bug.

**Comment by SteffenDuenner** [comment]
I just installed the very latest build from https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/latest which was built 15 minutes ago.
I don't know if this should already contain the fix. I just wanted to say that the problem still persists in this build.

**Comment by Dade916** [comment]
An automatic build (and tests) takes more than 3 hours to run, it is still under construction: https://dev.azure.com/LuxCoreRender/LuxCoreRender/_build?definitionId=1&_a=summary

**Comment by SteffenDuenner** [comment]
Ah OK. Didn't know that. Thanks :)

**Comment by SteffenDuenner** [comment]
Just installed the latest build and can confirm the fix is working. Both luxcoreui and BlendLuxCore work perfectly again.
Thanks!
