### ISSUE TITLE
Crash when editing mesh with light emitting material

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#34]
Video: https://youtu.be/rsjq0loY-y0 (I try to move a face of the cube)
Scene: [crash.zip](https://github.com/LuxCoreRender/LuxCore/files/1604947/crash.zip)

Happens on Windows and Linux.

**Comment by Dade916** [comment]
I should have fixed this problem.

**Comment by Theverat** [comment]
Yup, can confirm.
