### ISSUE TITLE
OpenCL render makes shader darker

### ISSUE THREAD

**Issue by steveernst117** [LuxCoreRender/LuxCore#342]
.blend file: 
[luxcore_opencl_BUG.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4398034/luxcore_opencl_BUG.zip)

Steps to reproduce:
In the supplied blend file, just alternate between cpu and opencl f12 render. The change is far more dramatic if you use opencl when viewport rendering. It seems to mainly affect the anisotropic shader on the body of the parts. 

Screenshots or rendered images:
CPU render:
![cpu_render](https://user-images.githubusercontent.com/36138994/77835855-f44f0b80-711e-11ea-86a9-35a2ba232277.png)

OpenCL render:
![opencl_render](https://user-images.githubusercontent.com/36138994/77835860-02049100-711f-11ea-814c-199ee78b159a.png)

Error message from Blender console:

OS: 
Blender version: 2.82
LuxCore version: 2.3

**Comment by steveernst117** [comment]
Okay, but I thought the idea was to have the two working simultaneously for faster renders...?

In your renders from v2.4, the CPU result is the correct one.

**Comment by Theverat** [comment]
I was speaking about debugging.

**Comment by steveernst117** [comment]
Ah, cool.

**Comment by Dade916** [comment]
The bump height is set to 15 meters !

![15m](https://user-images.githubusercontent.com/3247881/81163725-7ab50380-8f8f-11ea-87bd-07a82a0c44b9.png)

**Comment by steveernst117** [comment]
yeah, that's weird, but does that explain why it looks ok in cpu rendering but not in opencl?

**Comment by Dade916** [comment]
There may be or may be not a problem but a 15 meters  bump mapping will put the numbers out of scale so it isn't strange to see a different behavior in an undefined situation between CPUs and GPUs (the hardware is very different).

You are also first scaling down the the bump value by something like 0.01, than scaling up 15m (the 2 effects can probably elide each other). If you have still the problem using a "normal" bump map height, I will check again what is going wrong.
