### ISSUE TITLE
BlendLuxCore 2.3 crashes Blender 2.82a whenever rendering or open material preview

### ISSUE THREAD

**Issue by joc11** [LuxCoreRender/LuxCore#343]
.blend file: any
Steps to reproduce: Start render or open material preview.
Error message from Blender console: None
OS: openuse Tumbleweed, Geforce 8800 GTX, 
Blender version: 2.82a
LuxCore version: 2.3 linux64

Whereas v2.2 works fine, 2.3 crashes Blender about 5 sec after starting a render job or opening material preview.

No error message, terminal message ends with:

```
BlendLuxCore 2.3 registered (with pyluxcore 2.3)
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
==================================================
[Engine/Final] Rendering layer "View Layer"
[Exporter] Creating session
[SDL][4.061] Camera type: perspective
[SDL][4.061] Camera position: Point[7.35889, -6.92579, 4.95831]
[SDL][4.061] Camera target: Point[6.70733, -6.31162, 4.51304]
[SDL][4.061] Camera clipping plane disabled
```
What I miss in v2.3 is a startup message in v2.2, warning, that no material node is set for default Material.
I guess this is an issue related to that old GPU, but the NVIDIA proprietary driver did it fine using Version 2.2. Although
kind regards,
joc

**Comment by Dade916** [comment]
The GPU kernels in v2.2 are a lot smaller than the one in v2.3. I assume it is crash due to old and discontinued drivers. I doubt there is anything we can do.
