### ISSUE TITLE
WindowsXP or Vista supported?

### ISSUE THREAD

**Issue by techvintage** [LuxCoreRender/LuxCore#347]
I'd like to submit a pull request which adds support for greater than 64 logical processors on Windows.However,it will not work on Windows XP or Vista without a lot of boiler plate.Are WindowsXP or Vista supported?

**Comment by acasta69** [comment]
As far as I remember, we have removed Windows XP support shortly after "reboot" from old LuxRender to LuxCoreRender.
About Vista, we have never explicitly stopped support, but I would think it's not a problem, probably everyone upgraded at least to 7.

**Comment by Dade916** [comment]
I sincerely consider the support for 64+ threads far more important that any possible support for Vista.

**Comment by techvintage** [comment]
Thanks David and Alessandro for your response.
https://github.com/LuxCoreRender/LuxCore/pull/348 has been submitted for 64 group processor support which has successfully passed all checks.Request you to merge this to main build,if no other issues.

**Comment by Dade916** [comment]
Thanks, I merged the pull request.
