### ISSUE TITLE
[NOT-A-BUG] OpenCL Kernel Analyzer

### ISSUE THREAD

**Issue by robinchrist** [LuxCoreRender/LuxCore#349]
Hi,

Sorry for littering the Issue tracker, as this is not actually an issue.

Which tool do you use to analyse / optimise the OpenCL Kernels? I've tried to use the Radeon GPU Analyzer without any luck (see https://github.com/GPUOpen-Tools/radeon_gpu_analyzer/issues/60).

**Comment by Dade916** [comment]
I have used AMD CodeXL in the past (when I had an AMD GPU). Now, with the under development CUDA support, I'm trying various NVIDIA tools.

**Comment by robinchrist** [comment]
CodeXL seems to be discontinued and it doesn't offer some of the features RGA offers (register flow, for example).

Do you do any architecture specific optimisation, or more exact: Are the OpenCL Kernels WIP with respect to performance optimisations?

**Comment by Dade916** [comment]
> Do you do any architecture specific optimisation, or more exact: Are the OpenCL Kernels WIP with respect to performance optimisations?

We support OpenCL GPUs, CPUs, etc. devices  and now even CUDA too. This mean that we can use only architecture specific optimizations that are not detrimental for other devices.

In my experience, LuxCore kernel code is also so large and complex that most types of architecture specific optimizations are also not very effective or not applicable.

**Comment by Dade916** [comment]
I assume we can close this one.
