### ISSUE TITLE
syntax error in fresnel texture

### ISSUE THREAD

**Issue by neo2068** [LuxCoreRender/LuxCore#35]
Since the merge with the new spectral rendering code I get a syntax error message with fresnelpreset and fresnelsopra textures .

Example material (tex 1 works, tex2 and tex 3 Syntax error):
`scene.textures.tex3.type = fresnelsopra`
`scene.textures.tex3.file = scenes/luxball/Au.nk`
`scene.textures.tex2.type = fresnelpreset`
`scene.textures.tex2.name = copper`
`scene.textures.tex1.type = fresnelcolor`
`scene.textures.tex1.kr = 0.7 0.0 0.0`
`scene.materials.shell.type = metal2`
`scene.materials.shell.fresnel = tex3`
`scene.materials.shell.uroughness = 0.05`
`scene.materials.shell.vroughness = 0.05`

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by neo2068** [comment]
Yes, it's fixed. Nice finding! I looked into the code and haven't found it.
