### ISSUE TITLE
[Bug] Denoising doesn't work anytime

### ISSUE THREAD

**Issue by odil24** [LuxCoreRender/LuxCore#352]
OS: Win7 x64bit;
CPU: Core2Quad Q6600 @2.4Ghz;
VGA: GTX 1060 6Gb GDDR5 192bit;
RAM: DDR2 800Mhz, 3GB;
Blender: E-Cycles version 2.83a (doesn't work on Blender version too).
Screenshot: [img]https://i.postimg.cc/B6MfyktJ/luxtest2.jpg[/img]
Blend file: https://cdn-32.anonfiles.com/J7iaw6u1ob/8a0e9ba5-1588146395/luxtest2.blend

**Comment by zareami10** [comment]
Maybe a 2.83 thing? Can't reproduce on 2.82a.

**Comment by odil24** [comment]
No. In Beta 2.90 Alpha is the problem. The problem with OIDN I think.

**Comment by Dade916** [comment]
v2.90 is a bit too far in the future, we are not yet supporting it.

**Comment by odil24** [comment]
@Dade916, ok. Understand u

**Comment by odil24** [comment]
I'll try with 2.82a now and posting response

**Comment by odil24** [comment]
Here test on Blender 2.82a:
https://i.postimg.cc/c4VnttJR/luxtest282a.jpg
Note: Is there have any related requirements on PC specs for Denoising?

**Comment by odil24** [comment]
It was not a bug. OIDN is required at least SEE4 and later, but mine was SEE3 instructions sets. It so sad that I can't using it. :(
Regards,
Odilkhan Yakubov.
