### ISSUE TITLE
BCD denoiser fails

### ISSUE THREAD

**Issue by MikeZski** [LuxCoreRender/LuxCore#353]
Blender 2.82 Luxcore 2.3
The result of denoising is almost uniform color.
[BCD_denoiser_fail.zip](https://github.com/LuxCoreRender/LuxCore/files/4571106/BCD_denoiser_fail.zip)
![BCD denosier](https://user-images.githubusercontent.com/64746429/80921163-e8391800-8d74-11ea-88ba-b1f2586343d8.gif)

**Comment by Dade916** [comment]
I should have fixed this problem.
