### ISSUE TITLE
CUDA 10.2

### ISSUE THREAD

**Issue by SteffenDuenner** [LuxCoreRender/LuxCore#356]
While the CUDA support in LuxCore is being added right now, do you plan to directly move to CUDA 10.2 now that Blender is also supporting it?

https://developer.blender.org/rBd97c83712cf8d133beb77573fac35c459a64d827

**Comment by SteffenDuenner** [comment]
This is directly related to this issue: https://github.com/LuxCoreRender/LuxCore/issues/357

**Comment by Dade916** [comment]
Any particular reason we should update to v10.2 ?

We usually update external packages at the start of a new release than we stick to what we have until the next one.

**Comment by SteffenDuenner** [comment]
No, I just hit the problem mentioned here https://github.com/LuxCoreRender/LuxCore/issues/357 after updating CUDA yesterday.
Would be no problem going back to 10.1 for me. I just thought it could be possible to run it when 10.2 is installed, too.

**Comment by Dade916** [comment]
As far as I know 10.2 is compatible with 10.1 but there may be just a problem with .so names (and may be, it can worked around with symbolic links).
