### ISSUE TITLE
Not load on libnvrtc.so.10.2

### ISSUE THREAD

**Issue by maljos** [LuxCoreRender/LuxCore#357]
Luxcore is truly spectacular in the final results. I have a pc with xubuntu 18.04 installed, nvidia GeForce GTX 1660 SUPER graphics card and I have downloaded the latest standalone version and when I try to run it it gives an error: error while loading shared libraries: libnvrtc.so.10.1.
I have cuda-10.2. How could you solve this, please?

**Comment by SteffenDuenner** [comment]
Same problem here. Yesterday I thought I'd update from CUDA 10.1 to 10.2 (because it's now officially supported by Blender 2.90 master) but then the same error message popped up.
I could either remove 10.2 and go back to 10.1 but I'd rather find a solution with 10.2.
Maybe a symlink?

**Comment by Dade916** [comment]
NVRTC is the NVIDIA Runtime Compiler and it is included in CUDA SDK. On a normal Ubuntu should be enough to install the following packages:

- nvidia-cuda-toolkit
- nvidia-cuda-dev

**Comment by SteffenDuenner** [comment]
It works if I install CUDA 10.1 but not with 10.2 as libnvrtc.so.10.1 is from 10.1.
Would it be possible to call libnvrtc.so instead? Are 10.1 and 10.2 compatible or will LuxCore need to be compiled with 10.2 to work?

**Comment by Dade916** [comment]
I would try a dirty trick like making a symbolic link from libnvrtc.so.10.1 to libnvrtc.so.10.2.

I assume NVRTC 10.1 and 10.2 are compatible.

**Comment by maljos** [comment]
I tried creating a symbolic link with ln -s but it didn't work. I imagine it could be because the headings of the libraries to link functions are different

**Comment by Dade916** [comment]
Ok but does it work with v10.1 ? On linux, it isn't usually a problem to have multiple version of the libraries installed.

**Comment by maljos** [comment]
A solution that does not require installing the toolkit for cuda-10.1 would be nice.

**Comment by Dade916** [comment]
The only solution I see is to compile Lux from sources on your own with the v10.2 CUDA SDK.

**Comment by maljos** [comment]
Another solution would be: Is there a way to create an intermediate interface that can communicate with the library and obtain the necessary functions independent of the version of the library?

**Comment by maljos** [comment]
I'm going to compile it as you tell me and I'll let you know if it works for me. Thanks for your attention
