### ISSUE TITLE
OPENCL (also CUDA) crash when HSV connected to bump

### ISSUE THREAD

**Issue by bardo78** [LuxCoreRender/LuxCore#360]
.blend file: 

[crash_HSV_Bump.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4550712/crash_HSV_Bump.zip)

Steps to reproduce:
Open the blend file.
Add any kind of bump map (i haven't tried with normal map) to the texture image node.
Connect the HSV to value input of bump node.
Try to render (viewport or final render crash in any case)
Blender crashes.

Screenshots or rendered images:

Error message from Blender console:

OS: Win10 64bit
Blender version: Daily 04/29 2.83 beta version
LuxCore version: Daily 04/29 CUDA blendluxcore build

**Comment by Dade916** [comment]
I should have fixed this problem.
