### ISSUE TITLE
Dispersion turns green on OpenCL, works correctly on CPU

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#363]
Scene: [test_diamond2.zip](https://github.com/LuxCoreRender/LuxCore/files/4603278/test_diamond2.zip)
LuxCore version: 941555f3314aa36cd83e2adeb685d8e9af42261c
GPU: Nvidia 2080 RTX

It seems to happen only with the Metropolis sampler.

OpenCL, Metropolis, 3000 samples:

![diamond_OCL](https://user-images.githubusercontent.com/1584761/81471327-aaaf1180-91f0-11ea-842b-e64eb42203da.jpg)

CPU, Metropolis, 3000 samples:

![diamond_CPU](https://user-images.githubusercontent.com/1584761/81471330-adaa0200-91f0-11ea-9004-77f05db5f6cc.jpg)

OpenCL, Sobol, 3000 samples:

![diamond_OCL_sobol](https://user-images.githubusercontent.com/1584761/81471490-bcdd7f80-91f1-11ea-8741-23f6768cde6b.jpg)

**Comment by Theverat** [comment]
It also happens on Intel CPU OpenCL device.
Metropolis, 2000 samples:

![diamond_OCL_intel_cpu](https://user-images.githubusercontent.com/1584761/81476497-8532ff80-9212-11ea-936b-7007574c8993.jpg)

**Comment by Dade916** [comment]
The attached scene is missing the used HDR file and there is a point light. Hybrid rendering disabled so the point light caustic can not be rendered at all (even if I crank up the intensity).

I have tried to replicate the problem by adding an area light but I don't see this kind of result.

In general, it doesn't make any sense to render this scene with Metropolis over Hybrid rendering.

P.S. I have been tempted to remove OpenCL Metropolis many times, it is like BiDirVM, let's just mark it as unsupported and remove the voice from the list of sampler in BlendLuxCore.

**Comment by Theverat** [comment]
> The attached scene is missing the used HDR file

Sorry about that. Here is the fixed scene: [test_diamond3.zip](https://github.com/LuxCoreRender/LuxCore/files/4629214/test_diamond3.zip)

> P.S. I have been tempted to remove OpenCL Metropolis many times, it is like BiDirVM, let's just mark it as unsupported and remove the voice from the list of sampler in BlendLuxCore.

OK, I'm reworking the render settings a bit anyway.

**Comment by Dade916** [comment]
I would say it is another example of when Metropolis goes ballistic because of wrong image average luminance estimation (that on GPU s is a lot worse than on CPU too). If you set the IOR to 1.0 and zoom a bit the cuastic, it will become first green, than white, than the brightness will just explode.

Going to close/mark this as known problem/won't fix.
