### ISSUE TITLE
LUT loader for camera tonemapper

### ISSUE THREAD

**Issue by lacilaci** [LuxCoreRender/LuxCore#365]
Loading .CUBE or possibly other formats of lut files into camera.

Important to have also a control over mixing/blending in % so that some more agressive configs can be controlled

**Comment by lacilaci** [comment]
I might just be stupid, but i don't see a "post bounty" anywhere...

**Comment by Theverat** [comment]
The bountysource website is having outages for some weeks now, it's probably caused by that.

**Comment by Dade916** [comment]
This is a duplicate of #81.

**Comment by Dade916** [comment]
I assume we can continue the discussion on the original issue.
