### ISSUE TITLE
OpenMP library not found

### ISSUE THREAD

**Issue by wangeguo** [LuxCoreRender/LuxCore#368]
-- CMake version 3.17.2 detected
-- Single-config generator detected
-- Using build variant:
--
-- ################ GENERATED XCODE PROJECT INFORMATION ################
--
-- DETECTED SYSTEM-VERSION: 19.4.0

-- DETECTED SDK-VERSION: unsupported
-- OSX_DEPLOYMENT_TARGET : 10.9
-- CMAKE_XCODE_ATTRIBUTE_ARCHS: $(NATIVE_ARCH_ACTUAL)
-- OSX SDK SETTING : macosxunsupported
-- XCODE_VERSION : Xcode 11.4.1
Build version 11E503a

libomp installed by homebrew in /usr/local

**Comment by u3dreal** [comment]
omp is hardcoded since there is a problem with cmake ..
plz follow this guide [https://wiki.luxcorerender.org/Compiling_LuxCore#MacOs_10.13_.2B](url)
That will make it much easier to communicate.

**Comment by u3dreal** [comment]
You will have to edit cmake/PlatformSpecific.cmake 

Edit it like so 

 IF(${MAC_SYS} MATCHES 19)
    SET(OSX_SYSTEM 10.15)
    ELSEIF(${MAC_SYS} MATCHES 18)
		SET(OSX_SYSTEM 10.15)
	ELSEIF(${MAC_SYS} MATCHES 17)
		SET(OSX_SYSTEM 10.14)
	ELSEIF(${MAC_SYS} MATCHES 16)
		SET(OSX_SYSTEM 10.13)
	ELSE()
		SET(OSX_SYSTEM unsupported)
	ENDIF()

make sure you use the correct sdk. I think it is 10.15 at the Moment but i'm still on High Sierra.

Good luck.

**Comment by u3dreal** [comment]
Changes have been added to git
