### ISSUE TITLE
macOS openCL rendering different than CPU rendering

### ISSUE THREAD

**Issue by cekuhnen** [LuxCoreRender/LuxCore#370]
.blend file: 
standard lux example files

Steps to reproduce:
render the example file via cpu or openCL

Screenshots or rendered images:
![CPU](https://user-images.githubusercontent.com/11001547/81865154-8e3a0e80-953b-11ea-9c0f-a6c4d7715374.png)
![openCL](https://user-images.githubusercontent.com/11001547/81865163-8f6b3b80-953b-11ea-8339-b1e43845cab2.png)

Error message from Blender console:

OS: macos Catalina
Blender version: 2.83
LuxCore version: latest build with macOS openCL

**Comment by Dade916** [comment]
I assume it is just the result broken OpenCL drivers because the scene works fine on Windows and Linux. @u3dreal, does this scene work on your Mac ?

**Comment by u3dreal** [comment]
Seems to be something with glossyness in der Wood Material..

**Comment by u3dreal** [comment]
I have the feeling my System is a bit outdated . Will install Catalina.

**Comment by u3dreal** [comment]
It looks there is some problem with textures involved. In Viewportrendering the textures are not rendered at all. Environment( HDRI ) and all materials ...

**Comment by cekuhnen** [comment]
Would it help to make my macPro via Teamviewer accessible?

**Comment by u3dreal** [comment]
I'm installing Build env on Catalina right now .... i was also stupid enough to buy a RX5700 yesterday. It make no sense to maintain with an old System somehow. So we'll see.

**Comment by cekuhnen** [comment]
I had the 5700 too but then went back to a 5600 

the performance difference was minimal and saved quite some money

also the 5600 draws much less power overall

**Comment by u3dreal** [comment]
It seems textures are not rendered at all on GPU

**Comment by Dade916** [comment]
This is has been fixed, as far as I know.
