### ISSUE TITLE
segmentation fault when photoGI cache is enable with openCL

### ISSUE THREAD

**Issue by pas2bruit** [LuxCoreRender/LuxCore#371]
When I try to enable photoGI cache in openCL mode, lux crashes. My spec is i7, 4x 1080ti, 64G ram, OS archlinux.
I have no problem if I switch to CPU mode. The same crash happens on windows on the same machine.
backtrace:
```
Thread 174 "blender" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff079ed700 (LWP 27674)]
0x00007fffa1c4d6e5 in slg::PathOCLRenderEngine::GetTotalEyeSPP() const ()
   from /home/anthesite/.config/blender/2.82/scripts/addons/BlendLuxCore/bin/pyluxcore.so
(gdb) bt
#0  0x00007fffa1c4d6e5 in slg::PathOCLRenderEngine::GetTotalEyeSPP() const ()
   from /home/anthesite/.config/blender/2.82/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#1  0x00007fffa1c55db7 in slg::PathOCLOpenCLRenderThread::RenderThreadImpl()
    ()
   from /home/anthesite/.config/blender/2.82/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#2  0x00007fffa2e74dcd in thread_proxy ()
   from /home/anthesite/.config/blender/2.82/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#3  0x00007ffff7f71422 in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007ffff7b5db83 in clone () from /usr/lib/libc.so.6
```
test scene :
[luxtest.zip](https://github.com/LuxCoreRender/LuxCore/files/4638222/luxtest.zip)

**Comment by Dade916** [comment]
What LuxCore version are you using ? V2.3 or automatic build ?

**Comment by pas2bruit** [comment]
With version 2.3. Blender is version 2.82a.
I tried also on version 2.4 alpha, same problem

**Comment by Dade916** [comment]
Ok, I will check the test scene.

**Comment by Dade916** [comment]
The attached scene doesn't use PhotonGI (?) but even if I enable the cache, it woks fine here. Are you sure to have attached the right test scene ?

Does the crash always happen ? Does it happen if you use only a single GPU ?
