### ISSUE TITLE
Crash while rendering CUDA Driver API error out of memory code 2

### ISSUE THREAD

**Issue by EM-3D** [LuxCoreRender/LuxCore#372]
.blend file: 
Too big for upload

Steps to reproduce:
F12 with Opencl + only CUDA device selected

Screenshots or rendered images:

Error message from Blender console:

![Captura](https://user-images.githubusercontent.com/63151902/82152417-467bf580-9861-11ea-9ce7-fbf8a7e53054.JPG)

OS: WIN10
Blender version: 2.9
LuxCore version: 2.4 LATEST

**Comment by Theverat** [comment]
It looks to me like the scene is simply too big for your video memory?

**Comment by EM-3D** [comment]
the blend file with a "pack all into blend" its a 3Gb size.. my video card its a gtx1070 8gb vram...

**Comment by Theverat** [comment]
It doesn't matter what the file size on disk is, it's about the uncompressed size of the whole scene in memory.

**Comment by Dade916** [comment]
Does it happen if you open Blender, open the scene and press F12 ? Or does it happen only after few renderings (i.s. it is a memory leak) ?
