### ISSUE TITLE
Blender closes when trying to render through CUDA

### ISSUE THREAD

**Issue by maxpiratemax** [LuxCoreRender/LuxCore#373]
In some projects, BlendLuxCore does not want to render through a video card. I try to render through OpenCL or through CUDA. During the compiling of the kernel, the render just closes. When i trying to render through CPU, everything is ok.
My pc spec:
i7 6700
GTX 1070 (Nvidia Studio Driver 442.92)
SSD 512
32 DDR4
Win10

.blend file: 
https://1drv.ms/u/s!AiiAe1SZzhrEk28bmuD3DYUmN7jG?e=3pSnVJ

Steps to reproduce:
Try to render with OpenCL or CUDA

Error message from Blender console:
Not possible to see. The blender just closes during kernel compilation.

OS: Win 10
Blender version: 2.82.7
LuxCore version: 2.4a latest build from 15 may

**Comment by Dade916** [comment]
I'm testing your scene but it lacks the HDR file and I get an endless number of errors out Blender, including:

> Traceback (most recent call last):
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/engine/base.py", line 83, in render_final
>     final.render(self, depsgraph)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/engine/final.py", line 49, in render
>     _render_layer(engine, depsgraph, statistics, layer)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/engine/final.py", line 61, in _render_layer
>     engine.session = engine.exporter.create_session(depsgraph, engine=engine, view_layer=view_layer)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/__init__.py", line 143, in create_session
>     luxcore_scene.Parse(scene_props)
> RuntimeError: Syntax error in texture name: Zamioculcas.001
> ERROR: Syntax error in texture name: Zamioculcas.001
> Error: Syntax error in texture name: Zamioculcas.001

@Theverat does it work for you ?

**Comment by Theverat** [comment]
Checking it now, this seems to hint to some bug in the addon.

**Comment by Theverat** [comment]
I fixed a regression in the addon, now the scene renders fine here on OpenCL. Can't test CUDA right now.

**Comment by maxpiratemax** [comment]
Here it is another file with crashing when I try to render by cuda or opencl.

https://1drv.ms/u/s!AiiAe1SZzhrEk3CPqCgaAE1TTeOB?e=UAv6wA

**Comment by maxpiratemax** [comment]
> I fixed a regression in the addon, now the scene renders fine here on OpenCL. Can't test CUDA right now. Since the HDRI is missing, the background will be pink, not sure if that matters for the original issue.

It can be any 2k resolution.

**Comment by Dade916** [comment]
@Theverat, I get a ton of errors out of that scene too:

> WARNING: Material "Terrazzo_Stones_2x2_ud4mfako": Writing to ID classes in this context is not allowed: ud4mfako_2K_AO.jpg, Image datablock, error setting Image.filepath_raw
> Traceback (most recent call last):
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/material.py", line 25, in convert
>     return cycles_node_reader.convert(material, props, luxcore_name, obj_name)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/cycles_node_reader.py", line 28, in convert
>     result = _node(link.from_node, link.from_socket, props, material, luxcore_name, obj_name)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/cycles_node_reader.py", line 69, in _node
>     base_color = _socket(node.inputs["Base Color"], props, material, obj_name, group_node)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/cycles_node_reader.py", line 48, in _socket
>     return _node(link.from_node, link.from_socket, props, material, None, obj_name, group_node)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/cycles_node_reader.py", line 624, in _node
>     "texture": _socket(node.inputs["Color"], props, material, obj_name, group_node),
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/cycles_node_reader.py", line 48, in _socket
>     return _node(link.from_node, link.from_socket, props, material, None, obj_name, group_node)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/cycles_node_reader.py", line 343, in _node
>     tex2 = _socket(node.inputs["Color2"], props, material, obj_name, group_node)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/cycles_node_reader.py", line 48, in _socket
>     return _node(link.from_node, link.from_socket, props, material, None, obj_name, group_node)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/cycles_node_reader.py", line 237, in _node
>     filepath = ImageExporter.export_cycles_node_reader(node.image)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/image.py", line 94, in export_cycles_node_reader
>     return cls._save_to_temp_file(image)
>   File "/home/david/.config/blender/2.82/scripts/addons/BlendLuxCore/export/image.py", line 45, in _save_to_temp_file
>     image.filepath_raw = orig_filepath
> AttributeError: Writing to ID classes in this context is not allowed: ud4mfako_2K_AO.jpg, Image datablock, error setting Image.filepath_raw

Anyway, once exported I get an out of memory error and I assume @maxpiratemax  is what you get too:

`CUDA driver API error CUDA_ERROR_OUT_OF_MEMORY (code: 2, file:/home/david/projects/luxcorerender/LuxCore/src/luxrays/devices/cudadevice.cpp, line: 451): out of memory
`

This isn't really surprising because it is a 45,000,000 triangles scene but I'm checking anyway how the memory is used. I have the feeling it may related to the use of particles.

**Comment by Dade916** [comment]
The exported scene.scn alone is 250MB Oo

**Comment by Dade916** [comment]
The scene has some insane subdivision applied, I'm not sure if it is intended:

```
[SDL][24.992] Subdividing shape Mesh_dom140593333551624000 at level: 5
[SDL][30.083] Subdivided shape from 13174 to 13490176 faces
[SDL][30.083] Subdividing time: 5.091secs
[SDL][30.083] Shape count: 1
[SDL][30.083] Displacement shape Mesh_dom140593333551624000_140591201969160 with texture 140591201968136Color
[SDL][31.229] Displacement time: 1.146secs
[SDL][31.229] Subdividing shape Mesh_dom140593333551624002 at level: 5
[SDL][56.770] Subdivided shape from 68212 to 69849088 faces
[SDL][56.770] Subdividing time: 25.541secs
[SDL][56.770] Shape count: 3
[SDL][56.770] Displacement shape Mesh_dom140593333551624002_140590863160328 with texture 140590863162376Color
[SDL][62.687] Displacement time: 5.917secs
[SDL][62.687] Shape count: 4
[SDL][62.687] Displacement shape Mesh_Cylinder__003140593333550088000 with texture 140590863178248Color
[SDL][62.688] Displacement time: 0.001secs
[SDL][62.688] Displacement shape Mesh_Cylinder__001140593333548552000 with texture 140590863178248Color
[SDL][62.689] Displacement time: 0.001secs
[SDL][62.689] Shape count: 6
```
**"Subdivided shape from 68212 to 69849088 faces"** 70,000,000 of faces !

**Comment by Dade916** [comment]
> This isn't really surprising because it is a 45,000,000 triangles scene but I'm checking anyway how the memory is used. I have the feeling it may related to the use of particles.

I must correct myself the scene has  450,000,000 of triangles !

**Comment by Theverat** [comment]
So the bug is that it crashes instead of reporting "out of memory" and aborting the render?

**Comment by Dade916** [comment]
It throw the exception "Out of memory" as usual with LuxCoreUI. I'm not even sure if I have enough CPU memory to try a rendering inside Blender ... I tried and Blender crashes inside Embree code while trying to build the BVH for the GPU.
I'm not sincerely that surprised given the over the sky numbers. The scene has 2 meshes that once exported create 2GB .ply file each.

If I try to import back the .ply in Blender to see what they are, Blender just crashes (no LuxCore/BlendLuxCore involved).

The scene works fine on GPU if I enable out of core rendering and use TILEPATHOCL:

![8gb](https://user-images.githubusercontent.com/3247881/82232317-c6bc5c80-992e-11ea-84ac-d9f9778a314a.jpg)

but it uses more than 8GB of GPU ram so it clearly can not run with OpenCL and a 8GB card.

If you look at the scene:

![RGB_IMAGEPIPELINE_1](https://user-images.githubusercontent.com/3247881/82233471-5ca4b700-9930-11ea-8e01-d8177ac786ef.png)

I have the feeling the 450,000,000 triangles are more the result of some Cycles to LuxCore automatic conversion gone very wrong (subdivision levels ?).

**Comment by maxpiratemax** [comment]
![image](https://user-images.githubusercontent.com/65540210/82236205-751ace80-993c-11ea-9408-2f1c01135d0d.png)
But Blender says that I have only 479000 triangles. Almost all meshes are instances. Therefore, there are a few triangles. Doesn't Lux support instances and hair? Why are 400,000 turning into 450 million?

**Comment by maxpiratemax** [comment]
> So the bug is that it crashes instead of reporting "out of memory" and aborting the render?

At least yes

**Comment by Dade916** [comment]
Subdivision, like I wrote in my previous post you (or some automatic conversion code) are using some huge level of subdivision (probably for than applying displacement).

**Comment by maxpiratemax** [comment]
I checked the scene and did not find subdivision

**Comment by maxpiratemax** [comment]
![image](https://user-images.githubusercontent.com/65540210/82238526-240cd980-9940-11ea-8db4-5919a1747c23.png)
84m without grass. How then to understand which scene a suite can render on a video card and which one cannot?

**Comment by Theverat** [comment]
> But Blender says that I have only 479000 triangles.

The following materials have subdivision nodes in them:
* Gray_Brick_Wall_2x2_ucelcacfw
* Red_Brick_Wall_2x2_udznaenfw

These will only be evaluated on render startup, so Blender can not show the number of triangles they generate. 
These nodes were added manually, the Cycles converter does not do subdivision.

**Comment by maxpiratemax** [comment]
Ok. Thank you! Only one thing remains. That the program crashes instead of showing an error.

**Comment by Dade916** [comment]
The program crashes because of 450,000,000 triangles (not reached trough instancing but objects with 70,000,000 over real triangles). At that point, you are over many limits, for instance, BVH GPU code uses 28 bits for the node index: you can have max 2^28 = 268,435,456 of nodes. It isn't something fixable.
