### ISSUE TITLE
KernelCacheFill() does not allow to specify min/max epsilon

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#374]
Would it make sense to add that here?
https://github.com/LuxCoreRender/LuxCore/blob/0b620992aca249e89504e4c86de1ce2316149e3c/src/luxcore/kernelcachefill.cpp#L272

**Comment by Dade916** [comment]
It is already there (?): you can set min/max epsilon with the properties  you are passing to KernelCacheFill().

**Comment by Theverat** [comment]
From what I can see in the linked code, no: A new `Properties` instance "cfgProps" is created and only the renderengine from `kernelcachefill.renderengine.types` is set on them. The rest of the passed-in `config` properties is ignored, or am I overlooking something?

**Comment by Dade916** [comment]
Ok, luxcore::KernelCacheFill() now supports opencl.devices.select, scene.epsilon.min and scene.epsilon.max properties.

**Comment by Theverat** [comment]
Great, thanks!
