### ISSUE TITLE
Crash when removing object

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#377]
I'm not sure yet if this is a bug in the Blender addon or in LuxCore, would be glad if you could take a look at it:

Scene: [local_view_crash4.zip](https://github.com/LuxCoreRender/LuxCore/files/4669191/local_view_crash4.zip)

Steps to reproduce:
* Open file
* Press "H" to hide the already selected object (this will call `luxcore_scene.DeleteObject()`)
* Blender crashes

Only happens with PathOCL (tested with OpenCL device).

In the log, I get `ERROR: Reference to an undefined NamedObject pointer: 0x7f5d8aad2640`:
```
[LuxCore][7.777] Compile 2 Textures
[LuxCore][7.777] Texture evaluation ops count: 6
[LuxCore][7.777] Texture evaluation max. stack size: 3
[LuxCore][7.777] Textures compilation time: 0ms
[LuxCore][7.777] Compile 2 Materials
Traceback (most recent call last):
  File "/home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/export/__init__.py", line 331, in update
    session.EndSceneEdit()
RuntimeError: Reference to an undefined NamedObject pointer: 0x7f943bcfea40
ERROR: Reference to an undefined NamedObject pointer: 0x7f943bcfea40
[SDL][7.778] Light definition: __SAVIOR__
[LuxCore][7.825] Compile Lights
[LuxCore][7.825] Lights compilation time: 0ms
view_update(): applying changes took 143.3 ms
view_update() took 144.0 ms
Writing: /tmp/local_view_crash4.crash.txt
fish: “/home/simon/programs/blender-2.…” terminated by signal SIGSEGV (Address boundary error)
```

* When I don't use `RemoveUnusedTextures()` [here](https://github.com/LuxCoreRender/BlendLuxCore/blob/d996fa160ae2162827416ac76bd4078f93e2cdf2/export/__init__.py#L404), the crash does not happen - maybe a bug in the code checking for referenced textures?
* When I use PathCPU instead of PathOCL, the crash does not happen

LuxCore version: 93de16134bc24d1ceb80966b02d409d1c0d48120
Addon version: https://github.com/LuxCoreRender/BlendLuxCore/commit/0befe38be3c745ca4eab400d10fc3074bed2bac8

**Comment by Theverat** [comment]
I think this is a case of two interleaved bugs:
1. Something goes wrong either in LuxCore or the addon leading to the `RuntimeError: Reference to an undefined NamedObject pointer: 0x7f943bcfea40` error
2. `EndSceneEdit()` is called after the RuntimeError, leading to the crash (I guess this is not a bug?). Not sure how I can recover from errors that happen after `BeginSceneEdit()` without crashing, is this possible?

**Comment by Dade916** [comment]
It was a problem with Volumes. It should now work fine.
