### ISSUE TITLE
procedurale texture flickering

### ISSUE THREAD

**Issue by Sharlybg** [LuxCoreRender/LuxCore#383]
Strange behaviour with procedural texture and animated object. I got this behaviour in all my animation. As soon as you animate or move something with a procedural texture on it the texture coordination get animated too. like the mapping is done in space that make the texture projection to change according to the mesh position in the 3D space.

i wish we can optionally lock this behaviour. this happen in my last fruit juice animation on the apple. and it give the feeling of luxcore flickering while it isn't.

fruit juice animation apple flickering
[https://youtu.be/jVBEWn9Cxik](url)
[https://forums.luxcorerender.org/viewtopic.php?f=5&p=23301#p23301](url)

**Comment by Dade916** [comment]
You need to use local object space mapping, it is one of the available mapping type.
