### ISSUE TITLE
Fresnel Texture Format

### ISSUE THREAD

**Issue by Turakar** [LuxCoreRender/LuxCore#385]
I want to model the [Multi-Layer-Insulation](https://en.wikipedia.org/wiki/Multi-layer_insulation) of satellites with LuxCoreRender in Blender. I therefore had a look at the Metal material with a Fresnel texture. Unfortunately, the thin-layer aluminum of MLI has different properties than the normal aluminum. I thus want to model the fresnel properties based on optical observations.

The [wiki](https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.3#Type:_Fresnel_Textures) does not explain the `.nk` file format. I found two examples for this ([a](https://github.com/LuxCoreRender/LuxCore/blob/master/scenes/luxball/Au.nk) and [b](https://github.com/LuxCoreRender/LuxCore/blob/master/scenes/luxball/Cr.nk)) with different formats. So what is the format? What are the units? Which data do I need to acquire?

**Comment by Dade916** [comment]
The code for parsing luxpop .nk files is here: https://github.com/LuxCoreRender/LuxCore/blob/1e5801c639312ff9b960ac0c1bd862bc06566ae0/src/slg/textures/fresnel/fresnelluxpop.cpp#L36

As far as I remember, an .nk is just list of 3 numbers: wavelength (in nm unit), N value, K value. It is the case of the "b" example you linked ("a" file is in SOPRA .nk format).

**Comment by Turakar** [comment]
Thanks for the link, that is helpful. So wavelength seems to be in Angstroms and the data must be in ascending order.
https://github.com/LuxCoreRender/LuxCore/blob/1e5801c639312ff9b960ac0c1bd862bc06566ae0/src/slg/textures/fresnel/fresnelluxpop.cpp#L64
