### ISSUE TITLE
Heterogeneous volume Can't select model HDR cannot select Chinese path

### ISSUE THREAD

**Issue by a2325348** [LuxCoreRender/LuxCore#386]
I'm sorry that I can't speak English, so I use the translation
Report two bugs
operating environment: blender2.82. 2.83 2.9 Luxcore 2.3
1. Heterogeneous volume Can't select model 
2. HDR cannot select Chinese path
![TIM图片20200603155300](https://user-images.githubusercontent.com/66355783/83611531-adb0de00-a5b3-11ea-9e34-985b3fa2b066.png)
![TIM图片20200603155306](https://user-images.githubusercontent.com/66355783/83613473-69730d00-a5b6-11ea-982f-d949ed632b11.png)

**Comment by Dade916** [comment]
We added full support for Unicode UTF-8 in under development v2.4: https://forums.luxcorerender.org/viewtopic.php?f=5&t=2197

You should try to install a v2.4 daily build and it should fix your problems: https://forums.luxcorerender.org/viewtopic.php?f=9&t=736

**Comment by Theverat** [comment]
Please create separate issues for each bug.

> Heterogeneous volume Can't select model

Please open an issue about this here: https://github.com/LuxCoreRender/BlendLuxCore/issues
It is a problem in the addon.
