### ISSUE TITLE
RenderConfig loading error

### ISSUE THREAD

**Issue by lh-bx4** [LuxCoreRender/LuxCore#391]
`[SDL][14.031] Scene objects count: 14`
`[SDL][14.031] Light definition: LUXCORE_LIGHT_0`
`[SDL][14.094] Light definition: LUXCORE_LIGHT_1`
`[LuxCore][14.094] Configuration:`
`[LuxCore][14.094]   opencl.platform.index = -1`
`[LuxCore][14.094]   opencl.cpu.use = 0`
`[LuxCore][14.094]   opencl.gpu.use = 1`
`[LuxCore][14.094]   renderengine.type = "PATHOCL"`
`[LuxCore][14.094]   sampler.type = "METROPOLIS"`
`[LuxCore][14.094]   film.filter.type = "BLACKMANHARRIS"`
`[LuxCore][14.094]   accelerator.instances.enable = 0`
`[LuxCore][14.094]   film.width = 1296`
`[LuxCore][14.094]   film.height = 772`
`[LuxCore][14.094]   film.imagepipeline.0.type = "TONEMAP_AUTOLINEAR"`
`[LuxCore][14.094]   film.imagepipeline.1.type = "GAMMA_CORRECTION"`
`[LuxCore][14.094]   film.imagepipeline.1.value = 2.20000005`
`[LuxCore][14.094]   batch.halttime = 0`
`[LuxCore][14.094]   batch.haltspp = 0`
`[LuxCore][14.094]   path.maxdepth = 10`
`[LuxCore][14.094]   film.filter.xwidth = 1.64999998`
`[LuxCore][14.094]   film.filter.ywidth = 1.64999998`
`[LuxCore][14.094]   sampler.metropolis.maxconsecutivereject = 512`
`[LuxCore][14.094]   sampler.metropolis.largesteprate = 0.400000006`
`[LuxCore][14.094]   sampler.metropolis.imagemutationrate = 0.100000001`
`[LuxCore][14.094] File Name Resolver Configuration:`
`[LuxCore][14.094]   .`
`[LuxCore][14.094]   D:/Users/####/Documents/Sketchup`
`RenderConfig loading error:`
`Unknown render engine type in RenderEngine::ToProperties(): PATHOCL`
When I try to load an lxs file in luxcoreui i got this error. If someone can help ?
You have to know that the first engine i ran was the opencl one, but I don't have openCL.
Thanks in advance.

**Comment by Dade916** [comment]
The default render engine is PATHOCL (i.e. rendering using OpenCL GPUs) while I assume you are using a LuxCore version with CPU-only support.
You should edit the .cfg file and change this line:

`renderengine.type = "PATHOCL"`

in:

`renderengine.type = "PATHCPU"`

**Comment by lh-bx4** [comment]
I'm so glad you answer that fast !
I'm sorry but I don't know which cfg you are talking about ?

**Comment by lh-bx4** [comment]
Ok I think I understood how the whole things works. Except about this point : why when I write this in the .lxs file :
```
Renderer "luxcore"
	"string config" ["opencl.gpu.use = 0" "opencl.cpu.use = 1" "renderengine.type = PATHCPU"  "accelerator.type = AUTO"]
```
...the log still tells me this :
```
[LuxCore][8.594] Configuration:
[LuxCore][8.594]   opencl.platform.index = -1
[LuxCore][8.594]   opencl.cpu.use = 0
[LuxCore][8.594]   opencl.gpu.use = 1
[LuxCore][8.594]   renderengine.type = "PATHOCL"
[LuxCore][8.594]   sampler.type = "METROPOLIS"
...
```

**Comment by Dade916** [comment]
Are you using luxcoreui to read the .lxs file ? Just add a "-D renderengine.type PATHCPU" on command line before the .lxs file name.
".lxs" is the old file format used by LuxRender v1.x, it is only partially emulated in v2.x. A new file format is used there.

**Comment by lh-bx4** [comment]
I'm using the SU2LUX extension, I generated .lxs file with it. I may investigate and see if I find a way to generate .cfg file instead.

**Comment by Dade916** [comment]
As far as I remember, SU2LUX has never been updated to support new file format but the (partial) .lxs parse should be enough for most of the stuff. AS I wrote, you can overwrite any property from the command line, for instance:

`luxcoreui -D renderengine.type PATHCPU -D sampler.type SOBOL file.lxs`

**Comment by lh-bx4** [comment]
Thank you so much ! I'm sorry, I don't use ruby so I have some difficulty to guess the correct syntax.
The first time I tried passing the path of my file with `-o` so it doesn't worked.
Also, can you tell me the correct syntax for absolute link in ruby (in luxecorerender) since apparently, the windows type of link `D:\...` doesn't work.

**Comment by Dade916** [comment]
I don't know how SU2LUX works, I was under the impression you were saving the scene to a .lxs file and than you were running luxcoreui command by hand.

Now I have the feeling luxcoreui is execute automatically by SU2LUX. Are you using SU2LUX from https://github.com/LuxCoreRender/SketchUp2LuxCore or an older version ?

**Comment by lh-bx4** [comment]
Yes, I'm using latest SU2LUX to export scene to .lxs and also yes, I'm using luxcoreui to run the lxs render by hand. Apparently, it worked !

**Comment by Dade916** [comment]
Ok, good.
