### ISSUE TITLE
Crash when deleting last light

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#396]
Scene: [crash_no_lights.zip](https://github.com/LuxCoreRender/LuxCore/files/4814805/crash_no_lights.zip)

Steps to reproduce:
* Open scene in Blender
* Start viewport render
* Press delete to delete the selected point light
* LuxCore crashes

OS: Windows
LuxCore version: 9becd86ad2cd3c542473fbc7a0db97e77d56a932
Blender addon version: https://github.com/LuxCoreRender/BlendLuxCore/commit/7de3c9744d06055ccfda8aadd891599d93163e77

**Comment by Dade916** [comment]
I should have fixed this problem.

**Comment by Theverat** [comment]
Confirmed, thanks!
