### ISSUE TITLE
stats.renderengine.time not reset after scene edits in RTPathOCL

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#397]
Demo video: https://youtu.be/-IPFcNNM9Do
(The value of `stats.renderengine.time` is displayed in the upper left corner)

Time is reset correctly in other engines (e.g. RTPathCPU, PathCPU).

**Comment by Dade916** [comment]
I should have fixed this problem.

**Comment by Theverat** [comment]
Confirmed, thanks!
