### ISSUE TITLE
Crash when moving object with RTPathOCL

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#399]
Scene: [crash.zip](https://github.com/LuxCoreRender/LuxCore/files/4818861/crash.zip)

Steps to reproduce:
* Open scene in Blender
* Start viewport render
* press G and move the cursor
* LuxCore crashes

Only happens in RTPathOCL, RTPathCPU is working fine.
Only the OpenCL backend crashes, CUDA is working fine.

OS: Windows 10
LuxCore version: fec47c31b8b6e41f069fc501a11cf8ba91c4ee44

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Thanks!
