### ISSUE TITLE
Blender crashes when switching to "Rendered" viewport mode

### ISSUE THREAD

**Issue by zezic** [LuxCoreRender/LuxCore#401]
.blend file: default cube

Steps to reproduce:
1. Switch render engine to LuxCore
2. Switch "Device" to "GPU" (optional)
3. Switch viewport to the "Rendered" mode

Error message from Blender console:
[blender.crash.282.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/4810313/blender.crash.282.txt)
[blender.crash.282-gpu.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/4810314/blender.crash.282-gpu.txt)
[blender.crash.283.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/4810315/blender.crash.283.txt)
[blender.crash.283-gpu.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/4810316/blender.crash.283-gpu.txt)

OS: Ubuntu 20.04
Blender version: both v2.82a and v2.83.0 were tested
LuxCore version: **Pre-release build** (the f3ace6d one)
Hardware: AMD FX-8350 and AMD Radeon RX Vega 56

Notes:
* I got OpenCL support from amdgpu-pro-20.20-1089974-ubuntu-20.04 ([link](https://drivers.amd.com/drivers/linux/amdgpu-pro-20.20-1089974-ubuntu-20.04.tar.xz)) which is working OK for Cycles.
* BlendLuxCore v2.3 is also working nicely with it

**Comment by Dade916** [comment]
Your fix is correct however it is like your driver is returning multiple binaries for a single device (yes, the OpenCL context in LuxCore has always only a single device associated). It is the only way I can explain the memory corruption with old code.

What is really strange is that clGetProgramInfo() wants to return multiple binaries but than works when reading the cache and only the first one is provided.

I guess the really correct fix would be to add the support for saving/reading multiple binaries from the cache. Anyway, if the current code works, I'm not going to complain.

**Comment by zezic** [comment]
Thank you! The latest BlendLuxCore build works well for me. I think, the issue can be closed.
