### ISSUE TITLE
LuxCore Standalone GPU kernel compile crashes on Intel iGPUs 

### ISSUE THREAD

**Issue by jamespa16** [LuxCoreRender/LuxCore#407]
As things currently stand, there is no way to select what GPUs the PATHOCL kernel should be built for. The result of this is on my machine with an Intel iGPU the kernel attempts to compile against it then crashes in the Intel GPU drivers. I am not surprised that the Intel is not supported, but this crash renders my full-size GPU unusable. Interestingly on a different machine that does not use an eGPU but does have a CUDA dGPU the kernel does not try to compile against the iGPU. 

Hardware that crashes: 
Mac mini i7-8700B 32GB
Intel UHD 630 (the offender here)
eGPU AMD Radeon VII
macOS 11 Big Sur Beta + LuxCore latest, compiled on machine

Hardware that does not crash:
Surface Book 2 i7-8650U 16GB
Intel HD 620 (kernel avoids this one)
dGPU Nvidia GTX 1060 6GB
Windows 10 Insider Preview 2004 + LuxCore 2.4 Beta 1 release

**Comment by Dade916** [comment]
Is possible to select the devices to use in BlendLuxCore and from command line with luxcoreui or luxcoreconsole. What are you using ?
