### ISSUE TITLE
Downloads of LuxCoreRender v2.4 beta 1 are being blocked by Google Chrome

### ISSUE THREAD

**Issue by brianredbeard** [LuxCoreRender/LuxCore#408]
Currently downloading the beta of LuxCoreRenderer version 2.4 beta 1 is being blocked by Google Chrome:

![Screenshot from 2020-07-17 08-42-33](https://user-images.githubusercontent.com/57542/87805399-1d98c200-c80a-11ea-95ed-21407324ce4e.png)

From this dialog, the only options presented are to discard the file or "Learn more" which provides a hyperlink to the following URL: https://support.google.com/chrome/answer/6261569

From that dialog there is no option to retain the file.  Deleting it is the only option.

In the event that a user utilizes the "Show all downloads" mechanism in Chrome (`CTRL` + `J` in Linux) they are presented with a window which contains the following:

"This file may be dangerous, so Chrome has blocked it."

![image](https://user-images.githubusercontent.com/57542/87805185-cb57a100-c809-11ea-8cea-cd4ce4bcdba8.png)

This presently seems to be the only way to retain the file and persist it to local storage specifically through Google Chrome.  All other mechanisms to retrieve the file (Firefox, `curl`, `wget`, `aria2c`, etc work as expected).

This is using Google Chrome v84.0.4147.89 x86_64 on Fedora 31.

My present assumption is that this is technically a flaw with Chrome, but it is noted here as it may affect users of LuxCoreRender.

**Comment by brianredbeard** [comment]
Interestingly, this is also occurring with the v2.3 stable linux64 release, but not the v2.3 stable win64 release:

![image](https://user-images.githubusercontent.com/57542/87809216-e200f680-c80f-11ea-933e-f5846cb77d00.png)

Also, this is the dialog presented to users should they choose to "Keep dangerous file":

![image](https://user-images.githubusercontent.com/57542/87809313-0a88f080-c810-11ea-895f-a1dea402bb76.png)

**Comment by Dade916** [comment]
> My present assumption is that this is technically a flaw with Chrome, but it is noted here as it may affect users of LuxCoreRender.

I assume it is one of the useless addition to last Chrome version, I had the same problem today downloading a .cfg file (i.e. a text file) from our forum.
They have probably a white list of files and only allow people to download what they want ... I doubt it is even legal here in Europe and I hope someone will sue them very soon.
I doubt there is something we can do on or side (but I assume we are not the only one with this problem).

**Comment by vngzs** [comment]
@brianredbeard @Dade916 [Google fixed it.](https://stackoverflow.com/questions/62957859/how-can-i-prevent-chrome-from-blocking-a-xlsx-download)

**Comment by brianredbeard** [comment]
FYI, The work Google was doing is tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=1106858

From a comment in the issue tracker:
>  It wasn't a browser update. Chrome contacts Google's Safe Browsing service to verify that a file being downloaded is safe. There was a bug in that service that caused this issue to happen, but it has now been fixed.
