### ISSUE TITLE
Feature Request: Non-Uniform Bokeh Support

### ISSUE THREAD

**Issue by rrubberr** [LuxCoreRender/LuxCore#409]
In LuxRender, the camera offered support for "Non-Uniform Bokeh Distribution," which allowed the user to set the distribution, number of aperture blades, and power of the distribution. According to the luxrender.net wiki:

_"LuxRender also allows for some modifications to the distribution of light across the focus disk or circle of confusion. The distribution and quality of this light is generally called bokeh. This is achieved through the blade number and distribution parameters. Blade number is the number of blades that make up the iris of a lens. A blade number of zero simulates an infinite blade number of a perfect circle, and will result in bokeh disks that are circular... As no lens distributes light uniformly across the focus disk, some non-uniformity is desirable for photorealistic imaging."_

(https://web.archive.org/web/20161014045454/http://www.luxrender.net/wiki/LuxRender_Cameras)

Here is an example of the feature present while using LuxRender 1.2.1 in the Blender 2.65a interface:

![Capture](https://user-images.githubusercontent.com/11138056/87978356-1f21ee80-ca85-11ea-9b8e-91370026689c.PNG)

This feature was useful in practice, as it allowed users to create much more realistic and high quality bokeh, without resorting to complex setups requiring the use of translucent bokeh images or the compositor. Below I have created some examples using the different distributions, showing their usefulness to generate certain effects.

6 bladed exponential distribution with power 1:
![6Blades](https://user-images.githubusercontent.com/11138056/87980255-2991b780-ca88-11ea-9796-a60f2fbd173b.png)

22 bladed inverse exponential distribution with power 10:
![22inverse](https://user-images.githubusercontent.com/11138056/87980558-ac1a7700-ca88-11ea-8c9b-47916b5fd0c0.png)

0 bladed (perfectly round) aperture with uniform distribution and power 0 (perhaps the sort of DoF LuxCore is capable of?):
![uniform](https://user-images.githubusercontent.com/11138056/87981549-44652b80-ca8a-11ea-87b0-2d4b240246ee.png)

22 bladed aperture with exponential distribution and power 1:
![FinalTS_pregamma_1_mantiuk08_auto_luminance_color_saturation_1_contrast_enhancement_1_postsaturation_1_postgamma_1](https://user-images.githubusercontent.com/11138056/87982794-2b5d7a00-ca8c-11ea-8c6f-483be96167da.jpg)

Implementing this feature into LuxCore would be useful. Thanks!

**Comment by Dade916** [comment]
I have a vague memory it was an image post processing feature and not a real camera option. Do you have an LXS file using this feature ? I should be able to track back what it was.

**Comment by Theverat** [comment]
It's not a post processing feature, check https://github.com/LuxRender/Lux/blob/3550ad33f0d5a3f2a6c5fe435e4a853088db82a5/cameras/perspective.cpp#L326

**Comment by Dade916** [comment]
Right, the one I remember was lens flares. This one should be quite easy to add.

**Comment by michelchafouin** [comment]
Awesome, I have been waiting for this!

While looking at the bokeh shape, please consider supporting lateral and longitudinal chromatic aberration, the possibility to use a custom image, and optical vignetting.

**Comment by Theverat** [comment]
Do you have some links to information that would help implement all of this, by chance?

**Comment by michelchafouin** [comment]
I don't have any white-paper, but someone recreated it physically in Cycles (spoiler: it's extremely slow to render):
https://blenderartists.org/t/advanced-optical-experiments/695835
This page explains well the different lens effects:
http://richardrosenman.com/shop/dof-pro/

**Comment by Dade916** [comment]
I'm working on it:

![bokeh](https://user-images.githubusercontent.com/3247881/88176101-149f5a80-cc27-11ea-9ffd-0948f26b56dc.jpg)

**Comment by Dade916** [comment]
Done: https://forums.luxcorerender.org/viewtopic.php?f=5&t=2374

**Comment by Dade916** [comment]
> While looking at the bokeh shape, please consider supporting lateral and longitudinal chromatic aberration, the possibility to use a custom bokeh image, and optical vignetting.

@michelchafouin, I added the support for lateral and longitudinal chromatic aberration, it only requires to use two parameters instead of one:

```
film.imagepipelines.5.0.type = COLOR_ABERRATION
film.imagepipelines.5.0.amount = 0.025 0.005
```
