### ISSUE TITLE
material.transparency.back and negative object scaling

### ISSUE THREAD

**Issue by valenn** [LuxCoreRender/LuxCore#412]
Material back/front transparencies don't work correctly when used on objects that have negative scale (e.g. -1,1,1).

In a situation where I have two objects, both using same geometry and same material (instanced), and I "mirror" one object (scale = -1 1 1), I would expect it to not display inside out. As far as I can tell it works like that in other software (I tried exporting it as gltf and opening in web viewers babylon/playcanvas/threejs where it works like I would expect).

Here is a test scene for this, four white cubes that have scales (1,1,1), (-1,1,1), (-1,-1,1) and (-1,-1,-1). Each cube also contains another red cube to make this more obvious. I've tried this with latest release (6dacf31)
![image](https://user-images.githubusercontent.com/29863365/88042646-92dafe80-cb4c-11ea-80e4-45c0702d2974.png)
[scale_backface.zip](https://github.com/LuxCoreRender/LuxCore/files/4952724/scale_backface.zip)

I'm not sure if I'm using this correctly (I assume it is like backface culling). Current workaround for me is to not use front/back transparencies or "bake" scale to geometry.

**Comment by Dade916** [comment]
Thanks, going to check this problem.

**Comment by Dade916** [comment]
I have looked into this problem and, as far as I can see, LuxCore current behavior is the correct one. You are assuming that all "negative" scales are equals but it isn't so: someone swap the handiness while some other will not.
With handiness, I mean changing the reference system from left handed to right handed and vice versa.

This is the result of some debug code printing the Transform::SwapsHandedness() of each grey cube:

```
# Top left cube
object_0 => Transform::SwapsHandedness() = true
# Top right cube
object_2 => Transform::SwapsHandedness() = false
# Lower left cube
object_5 => Transform::SwapsHandedness() = true
# Lower right cube
object_7 => Transform::SwapsHandedness() = false
```

As you see, the handiness swap is consistent with flipping/not flipping inside-out the object. The current behavior is consistent with all other LuxCore surface normal related behaviors: Glossy material front/back face, interior/exterior volumes, etc.
