### ISSUE TITLE
Pixel filter width has no effect on light tracing 

### ISSUE THREAD

**Issue by DEBIHOOD** [LuxCoreRender/LuxCore#413]
When changing pixel filter width, this does not affect caustic generated with light tracing.

**Blackman-Harris width 1.50px**
![1 50px](https://user-images.githubusercontent.com/54025271/88225104-61188380-cc83-11ea-9854-1825dbe94182.png)

**Blackman-Harris width 20px**
![20px](https://user-images.githubusercontent.com/54025271/88225047-4940ff80-cc83-11ea-9dfc-40ddbaa99e88.png)

Tested with Luxcore 2.4RC1

**Luxcore standalone & .blend files:**
[Pixel filter LT.zip](https://github.com/LuxCoreRender/LuxCore/files/4962462/Pixel.filter.LT.zip)

**Comment by Dade916** [comment]
It was somewhat intended because, with today denoiser, you pretty much never use pixel filters but I can enable pixel filtering on light tracing when it is also enabled on eye tracing for consistency.

**Comment by Dade916** [comment]
I added the support for pixel filtering to light tracing:

![pf](https://user-images.githubusercontent.com/3247881/88398817-32ef8c80-cdc6-11ea-93c9-421d4626929f.jpg)
