### ISSUE TITLE
PhotonGI Cache problem with light from different lightgroups inside other lightgroups

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/LuxCore#414]
I'm not sure how to explain it, so I decided to prepare a Blender file and publish some pictures.

In the blend file you will see three light groups:

- Interior lights
- exterior lights
- environment

If you press render you will see in this case that the lights from other lightgroups are present everywhere, in other more complex scenes you can even see like a weird light leak.

I forced the energy of the lights to show more the problem, if you reduce the power of each light the problem is less visible but it's still there in the form of something like fireflies or weird noise.

These are the results of the light groups:

Exterior lights light groups, you can see the interior lights effect where it should not be:
![image](https://user-images.githubusercontent.com/20524718/88411367-16f4e680-cdd8-11ea-8926-4993afa57a96.png)

Interior lights light group, you can see the exterior lights effect there, it should not be there:
![image](https://user-images.githubusercontent.com/20524718/88411626-8ff43e00-cdd8-11ea-9578-da66bca7b117.png)

And here is the environment light light group, the problem is obvious :) : 
![image](https://user-images.githubusercontent.com/20524718/88411638-95518880-cdd8-11ea-8621-27405dd74cc2.png)

Attached is the .blend from this.

I hope this helps.

[lux_24_gicache_test.blend.zip](https://github.com/LuxCoreRender/LuxCore/files/4972996/lux_24_gicache_test.blend.zip)

Thanks!

**Comment by Dade916** [comment]
I'm looking into the problem. I started disabling both DLS and PhotonGI cache. A rendering with area light groups disabled already looks strange:

![normal](https://user-images.githubusercontent.com/3247881/88455256-1ca00a00-ce74-11ea-804e-251632f9e5af.jpg)

There are far less fireflies but they are still there (i.e. the problem may be not strictly related to the caches, they may only amplify a bug somewhere else).
I'm aware that light groups can have precision problems (i.e. the value resolution is not infinite so the initial ratio between different light groups intensities does matter) however this looks like something else.

**Comment by juangea** [comment]
Great, at least this bug came to the surface 👍

**Comment by Dade916** [comment]
This problem was driving me crazy but, at the end, it is just the result of an extreme (and wrong) variance clamping setting. The clamping is set to 5 but the scenes has values of 100 or higher, this leads to all sort of problems.

If you rise the clamp value to 100+ (or disable), everything will work as expected.

This is somewhat the result of variance clamping being applied to the complete image (i.e. the sum of all light groups) without any regard for light groups. I can think to apply variance clamping to each light group instead of the complete image but this would be a new feature (for v2.5), not a bug fix for v2.4.

**Comment by Dade916** [comment]
I have added the support for variance clamping applied separately to each radiance group to v2.5 and it handles well this scene even with the original clamping setting of 5.

**Comment by juangea** [comment]
Great, thanks
