### ISSUE TITLE
Subdiv shape doesn't support more than one UV map

### ISSUE THREAD

**Issue by maljos** [LuxCoreRender/LuxCore#416]
I am using two uv maps (uv map-main and uv map-motiv), different on the same object with various materials, but the uvmap that controls displacement map does not work.

OS: Xubuntu 18.04
Blender version: 2.83.3
LuxCore version: 2.4 RC

**Comment by maljos** [comment]
You are right excuse me, I should have investigated a little more. So what is the primary importance of the subdivision node?

**Comment by Theverat** [comment]
It subdivides the mesh (I assume the displacement works even without it because the mesh is already tessellated a bit - the Subdiv node would just subdivide this further).
You can replace it with a Blender subdivision modifier to work around the multi-UV limitation for now.

**Comment by maljos** [comment]
Thank's

**Comment by Dade916** [comment]
@Theverat, I added the support for any UV map channel in v2.5. The index can be set with the new displacement shape property ".uvindex".

**Comment by Theverat** [comment]
Unless I misunderstand something, this doesn't solve the problem here.

The displacement shape is working fine, the actual problem is that the **subdiv** shape does not preserve any UV maps beyond the first one.

**Comment by Dade916** [comment]
Subdiv shape now supports multiple vertex UVs, colors, alphas and AOVs.

**Comment by Theverat** [comment]
Thanks!

**Comment by maljos** [comment]
That's what I meant when I told you that luxcore was taking main uvmap ignoring the others. I find it ingenious to incorporate the subdivision node in the construction of the material so that it is independent of the object or the modifiers of the modeler, of course, there can be a minimum of conditions that the object must meet (example: 2 subdivisions), this would be a deeper approach than just having a node that controls the edges of the object geometry.

Thank you very much for your quick and satisfactory attention, I hope you continue that approach of interaction with your end users, it always brings excellent results in the end.
