### ISSUE TITLE
Cloth Material Error with CUDA GPU Rendering

### ISSUE THREAD

**Issue by rrubberr** [LuxCoreRender/LuxCore#417]
While converting a scene for use with LuxCore, I came across an error when switching to GPU CUDA rendering. Cloth materials seem to lose saturation in the applied color or texture. The issue is shown below.

The error (with GPU selected):
![Cloth_Error](https://user-images.githubusercontent.com/11138056/88528796-f2edfc80-cfb3-11ea-891f-dd49971f4545.jpg)

The correct result (created by selecting only CPU device):
![Cloth_CPU](https://user-images.githubusercontent.com/11138056/88528840-04370900-cfb4-11ea-99d5-abb327e85ff5.jpg)

This result is also reproducible with the default cube scene:
![Default](https://user-images.githubusercontent.com/11138056/88528911-1add6000-cfb4-11ea-9bc1-2068cf4a2922.png)
![Default2](https://user-images.githubusercontent.com/11138056/88528914-1ca72380-cfb4-11ea-8640-30d50478ce4d.png)

The issue persists with light tracing and PhotonGI cache enabled / disabled. The error also applies with color set to the warp or weft diffuse color, or both sockets. The error does not occur when the CPU device is selected. 

**Steps to reproduce:**
1. Load the default scene and apply the default cloth material to the cube.
2. Select "GPU" device.
3. Hit render.

LuxCoreRender 2.4 release and Blender 2.83.3 were used.

**Comment by Theverat** [comment]
I can reproduce it with the CUDA backend.
It seems to be a CUDA-only problem, because I can't reproduce it with the OpenCL backend.

**Comment by betstick** [comment]
I have also confirmed it on Windows 10 version 2004 with a GTX 1070.

**Comment by Dade916** [comment]
I can not reproduce the problem with v2.5. Can you reproduce the problem with v2.5 ?

**Comment by Theverat** [comment]
> Can you reproduce the problem with v2.5 ?

Yes.
Scene: [cloth.zip](https://github.com/LuxCoreRender/LuxCore/files/5011988/cloth.zip)

CPU:
![cpu](https://user-images.githubusercontent.com/1584761/89121192-1d145280-d4bd-11ea-913a-d2a1343c8968.jpg)

OpenCL:
![opencl](https://user-images.githubusercontent.com/1584761/89121195-1dace900-d4bd-11ea-80c1-c1b9e1af5005.jpg)

CUDA:
![cuda](https://user-images.githubusercontent.com/1584761/89121196-1e457f80-d4bd-11ea-95bc-5099f7f5dd15.jpg)

OptiX:
![optix](https://user-images.githubusercontent.com/1584761/89121198-1e457f80-d4bd-11ea-9bcc-9593d1cf14d8.jpg)

**Comment by Dade916** [comment]
I was able to replicate the problem but only on Windows. The root of the problem was in CUDA for Windows considering ulong data type a 32 bits value while it is a 64 bits value in CUDA for Linux (and the rest of the universe...).

I should have fixed the problem.
