### ISSUE TITLE
visibility.indirect.*.enable does not seem to work

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#42]
I'm setting the visibility like this:
```
scene.lights.__WORLD_BACKGROUND_LIGHT__.visibility.indirect.diffuse.enable = 1
scene.lights.__WORLD_BACKGROUND_LIGHT__.visibility.indirect.glossy.enable = 1
scene.lights.__WORLD_BACKGROUND_LIGHT__.visibility.indirect.specular.enable = 0
```
[**scene.zip**](https://github.com/LuxCoreRender/LuxCore/files/1631877/scene.zip)
But when I test it with a sphere with mirror material (specular, right?) the sky2 is still visible in the reflection.
Do I misunderstand how this should work or is there a bug?

**Comment by Dade916** [comment]
".visibility.indirect" properties were used only by BIASPATH. They currently do nothing even if the properties are parsed and stored in LuxCore.

It should be easy to restore the their functionality for PATH/TILEPATH, I'm going to check.

**Comment by Dade916** [comment]
I have re-added the support .visibility.indirect.*.enable flags for PATH/TILEPATH.

Indeed, they are ignored in LIGHTCPU and BIDIRCPU where they don't make very much sense.

**Comment by Theverat** [comment]
Can confirm it works now.
