### ISSUE TITLE
4x2080ti fault

### ISSUE THREAD

**Issue by Txamo** [LuxCoreRender/LuxCore#420]
Hi guys, good night.

I have a problem with the 2.4 release.

My configuration has 4x2080ti. When I start rendering in viewport with the 4 GPUs or with 3 GPUs and I go to solid or to Cycles, for example, the system closes automatically the same happens to me if I go from Cycles to Luxcore, if I put 1 or 2 GPUs this problem does not occur , but with 3 or 4 yes.

If you need any more information tell me and I will gladly try to help you.

A greeting.

OS: win 10
Blender version: 2.83.3
LuxCore version: 2.4 release

**Comment by Dade916** [comment]
I may have been able to reproduce the problem here (i.e. first step to fix it).

**Comment by Txamo** [comment]
Hi Dade,

Thank you very much, I hope it is solved for proper operation. I have seen
that the problem report has been removed on the page where the problem was
uploaded, is it for any reason?

Have I done something wrong?

You tell me how this problem is going and if you need help from me to solve
it.

Thank you very much.

Kepa.

**Comment by Dade916** [comment]
I just moved the issue from BlendLuxCore to LuxCore repository because it is not Blender related but core engine related.

**Comment by Dade916** [comment]
> I just tried now again, and the only way that Blender won't close is to use a single GPU if I put 2-3 or 4, the program closes automatically, I have noticed that luxecore becomes quite slow with the latter. test in which it does not close.

I'm not able to replicate the problem here (with the under development v2.5). Can you try an automatic build (https://forums.luxcorerender.org/viewtopic.php?f=9&t=736) and check if the problem is still there ?

**Comment by Txamo** [comment]
Hello david,

I just tried with 2.5 beta version and the exact same problem happens,
Blender closes, in addition to this I feel that it becomes strangely slow
in use, even from the configuration section of the engine section.

The problem is still there David.

I wait your answer.
Kepa.

**Comment by Dade916** [comment]
@neo2068, as far as I remember, you have 2 x NVIDIA GPUs, are you able to replicate this problem ?

**Comment by Txamo** [comment]
We have tested on a second computer with the same configuration to rule out any other problems, and the same continues with the final version of 2.4 and alpha version 2.5

**Comment by Dade916** [comment]
I installed my old GTX980 on my new PC with the RTX2070 but I can't still replicate the problem, view port rendering is working fine with both GPUs.

**Comment by Txamo** [comment]
Hi David,

The problem is with more than two GPUs, that is to say with 3 or 4, with
two it works without problem.

I have tested on the other computer where we have 4x 2080 and the problem
is the same when you use those 3 or 4 GPUs.

**Comment by Txamo** [comment]
If you need it, I record how the program closes when using the 3-4 GPUs

You tell me what you need.

**Comment by Txamo** [comment]
I send you a link, so you can download the video and see the problem when
rendering the viewport with more than 2 GPUs.

http://sendanywhe.re/20MEKT2L

**Comment by Dade916** [comment]
I have reproduced here the steps shown on the video but it works fine. But I may initial misunderstood the problem: do you get a crash only when switching render engine from LuxCore to Cycles ? I was thinking to a crash during LuxCore view port while is the crash happening only when switching ?

Does it happens even if you leave the view port halt time to 10secs  ? Does it happens both when using, as view port denoiser, OIDN  or Optix ?

Even if it happens, I sincerely consider it a minor problem and it may be even a Blender bug.

**Comment by Txamo** [comment]
Hello david,

I explain everything you ask me, I have carried out the tests with the
questions that you have put me in the message that you just sent me. The
error kept happening, I'm testing with version 2.4 but the same thing
happens with 2.5 alpha, in all circumstances where you ask me, Blender
closes when I switch to Cycles and it has ever happened to me even to
workbench, the crash only happens when switching, it happens even if I let
the viewport render time finish already 10 seconds or the time that I put
it, now I was testing with version 2.4 so I could not test optix that is in
2.5 BUT, I don't know for what reason it occurred to me to try something
that I have attached to you in the video that I send you.

In edition / preference / systema, in the section where we select between
CUDA and OPTIX, I don't know which of the two was activated just before
testing, I have changed from one to the other and have launched a render
viewport and have tried again as you see in the video and I don't
understand why, I don't know if it has loaded something or I don't know
exactly what the problem is but it works, Blender does not hang, so when I
saw that I thought it was that in one of the two modes maybe that error is
caused (CUDA or OPTIX) but neither, because as you see in the video after
trying one and seeing that Blender does not close and the engine works, I
have tried to change from OPTIX to CUDA and SURPRISE !!! Also works.

I don't know what the problem is there, but unless you do these tests as I
have done that, it has happened to me on both teams.

http://sendanywhe.re/1FXKFPPZ

**Comment by Dade916** [comment]
Ok, so now it woks, good. There may have been some interaction with some system wide setting between Cycles with CUDA/Optix and LuxCore with CUDA/Optix.

**Comment by Txamo** [comment]
It may be, but this happens to me on all computers with more than two GPUs,
maybe people should know somehow if this happens to them because you see
how we have gone crazy with unexpected closures or I do not know if it is
even something solvable David.

As always, thank you very much for the work you do and the attention you
give.
