### ISSUE TITLE
Implement Holdout Shader

### ISSUE THREAD

**Issue by MarioPeper** [LuxCoreRender/LuxCore#423]
In the cycles setting you have the possibility to set  Outliner > filter > Holdout and the Object Properties > Visibility > Holdout, together with the function Render Properties > Film > Transparent, to make it invisible but still makes indirect light. Very useful in compositing. I think Luxcore should have this.
Edit: For a better understanding https://youtu.be/fJtaboOKxeE?t=95

**Comment by Theverat** [comment]
Blender manual on holdout shader: https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/holdout.html
Simply put, areas on the film containing a holdout material should be transparent. Otherwise the material behaves normally.
(in Cycles it appears black to camera rays, but I'm not sure if we necessarily need to copy this behaviour)

**Comment by MarioPeper** [comment]
No I didn't mean the holdout shader. It is already listed in the Cycles scene reader task. Please have a look in the linked video (it is only short)
![holdout](https://user-images.githubusercontent.com/66747679/89130792-342c6200-d508-11ea-8ee0-b14eada28e2b.png)

**Comment by Theverat** [comment]
I am pretty sure they are the same thing internally in Cycles.
At least this looks like it to me: https://github.com/blender/blender/blob/c3651adf8914048ecd2668937c3ed4414a6707bd/intern/cycles/kernel/kernel_path.h#L283

**Comment by MarioPeper** [comment]
But when I use the holdout shader, it no longer casts light on other objects. Whereas the holdout setting in the object properties > visibility does. If there is an easier way to achieve this in Luxcore, why not. But this makes a big difference in compositing.

**Comment by Theverat** [comment]
From a user perspective, the best way to implement this might be a material flag, so any material can become a "holdout".

**Comment by MarioPeper** [comment]
Yeah that sounds good.

**Comment by Dade916** [comment]
I added the support for holdout. It is a material attribute and can be set with property ".holdout.enable". This is a normal rendering:

![normal](https://user-images.githubusercontent.com/3247881/89290685-803aec00-d659-11ea-80cc-5001a37dfa5a.jpg)

and this with ".holdout.enable" set to 1:

![holdout](https://user-images.githubusercontent.com/3247881/89290703-8d57db00-d659-11ea-81c0-4a4c0792ef99.jpg)

**Comment by MarioPeper** [comment]
Wow, that was fast. Thank you so much.

**Comment by Theverat** [comment]
I added support for it in the Blender addon.

**Comment by MarioPeper** [comment]
Thank you very very much, you are incredible.

**Comment by Theverat** [comment]
Note: I didn't yet add support for holdout to the Cycles scene reader.
The view layer holdout setting is also not supported yet.
Until that is done, you have to open the "advanced" options in a Lux material output node and enable "Holdout" there.

**Comment by MarioPeper** [comment]
Actually I find this solution much better than the scrolling nightmare in cycles. It fits perfectly to the Shadow Catcher and to luxcore :-) . The sense of the Holdout shader (without GI) is not quite clear to me either. Being able to set holdout and indirect only in the outliner would be nice, but it is no longer necessary in my workflow now. Thanks again for that feature.
