### ISSUE TITLE
out of core for geometry 

### ISSUE THREAD

**Issue by bestman8** [LuxCoreRender/LuxCore#428]
right now i have a pretty large scene with a lot of geometry (around 9 billion) but gpu compute is not working then i tried it with out of core and it still didn't render cpu compute works fine i think out of core for geometry migth be fixing the issue. and i am aware that this probably wont help me but it might help someone else.

**Comment by Theverat** [comment]
Geometry can already be stored out of core, see the section "List of OoC buffers" here: https://forums.luxcorerender.org/viewtopic.php?f=5&t=2102#p22174

**Comment by bestman8** [comment]
got it
