### ISSUE TITLE
Mismatch between GPU and CPU render of brick texture

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#438]
When using the "Herringbone" or "Basket" patterns on a brick texture, the texture appears scaled along one axis when rendered on the GPU.

OS: Ubuntu 20.04
GPU: Nvidia RTX 2080
Backend: CUDA

Scene: [brick_difference.zip](https://github.com/LuxCoreRender/LuxCore/files/5136756/brick_difference.zip)

CPU:

![cpu](https://user-images.githubusercontent.com/1584761/91450486-a597d000-e87c-11ea-92c7-6b3f4c316e0f.png)

GPU (CUDA):

![gpu_cuda](https://user-images.githubusercontent.com/1584761/91450617-c52ef880-e87c-11ea-8705-33907c458f77.png)

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Thanks!
