### ISSUE TITLE
OpenCL driver API error [Blender]

### ISSUE THREAD

**Issue by nhhollander** [LuxCoreRender/LuxCore#439]
Any attempt to render with LuxCore within Blender 2.83.4 fails with the following error:

`ERROR: OpenCL driver API error (code: -30, file:/home/vsts/work/1/s/LinuxCompile/LuxCore/src/luxrays/utils/ocl.cpp, line: 178): CL_INVALID_VALUE`

Blender: 2.83.4 x64
OS: Ubuntu 20.04.1
CPU: AMD Ryzen 9 3900x
GPU: AMD RX 5700 XT

Steps to reproduce:
 1. Open blender on a computer with above specs
 2. Enable LuxRender
 3. Start Render

What I've tried:
- Uninstall amdgpu-pro entirely
- Reinstalling amdgpu-pro
- Reinstalled only amdgpu-pro opencl

[log.txt](https://github.com/LuxCoreRender/LuxCore/files/5139764/log.txt)

**Comment by Dade916** [comment]
Is your OpenCL installation working ? Try to run LuxMark, if it doesn't work, the problem is there.

You have 2 OpenCL platforms installed:

```
[LuxRays][7.856] OpenCL Platform 0: Clover
[LuxRays][7.856] OpenCL Platform 1: AMD Accelerated Parallel Processing
```

Do you have something like Pocl installed side by side with AMD OpenCL ?

P.S. running "clinfo" command can help you to track what OpenCL platforms and devices you have installed.

**Comment by nhhollander** [comment]
The issue or a similar issue was present in other LuxCore based renderers, but after reinstalling my OS it was resolved.  I believe the problem was caused by a faulty driver install.  I have not been able to replicate the issue since.

**Comment by erfizt** [comment]
Hi, I have some problem with luxcore 2.5. Then I open Edit > Preferences > Add-ons > search luxcore > In the Film Device: Choose CPU.
