### ISSUE TITLE
Flashing caustics

### ISSUE THREAD

**Issue by eidsheim** [LuxCoreRender/LuxCore#441]
Hi,

As I'm testing LuxCore for Blender, I've encountered an issue where I get flickering caustics even with persistent photon mapping caching turned on. The object is static with a moving camera that has DOF. Lighting is done by HDRI. I've tested without caching the caustics photons and the flickering happens then as well. The render is only 128 samples but many neighbouring frames does not exhibit the flashing caustics which leads me to believe it is not purely a sampling issue?

I've uploaded the scene and render here: https://drive.google.com/drive/folders/1fEXR8i7L5-berCS0ZeDIOQLd3v8egyF1?usp=sharing 

Blender 2.83.5
LuxCore 2.4

Thanks,
Ole

**Comment by Dade916** [comment]
I'm somewhat aware of the problem, it should be tracked back some Metropolis numerical precision problem and env. light (distant light sources like sun, sky, HDR, etc.).

It shouldn't happen whit local lights like point, spot, area, etc. light sources.

**Comment by Dade916** [comment]
I can not download your test scene.

Anyway, I should have fixed the problem. The fix will be included in next automatic v2.5 build (available in a couple of hours): https://forums.luxcorerender.org/viewtopic.php?f=9&t=736
