### ISSUE TITLE
PyLuxCoreTool unable to merge films

### ISSUE THREAD

**Issue by Deadwing888** [LuxCoreRender/LuxCore#444]
This is on the very latest build of 2.5a compiled and run in a windows environment on both the render server and the netconsole machine.

The scene binary comes from blender with blendluxcore 2.4. The scene binary renders fine in luxcoreui. All scenes from blender have this issue, even the default cube scene with a only matte material applied to the cube.

When the job gets sent off to the server for rendering, it runs as normal.

When it's time to merge the film from the server(s) pyluxcoretool console spits out the following error:

File C:\Users\username\appdata\local\temp\_MEI34082\pyluxcoretools.zip\pyluxcoretools\renderfarm\renderfarmfilmmerger.py, line 101, in MergeAllFilms
RuntimeError: unregistered class

The line in question is: 				filmThread = pyluxcore.Film(filmThreadFileName)

It will throw this error in regards to this line no matter what python file is calling it, for instance resuming the job with .flm files ready for merge causes it to have the same issue even without any render nodes connected.

The line itself has not changed since the stable release of 2.4 in which everything runs as expected for any scene. I can provide an flm file with this issue if needed.

**Comment by Dade916** [comment]
I should have fixed this problem.
