### ISSUE TITLE
pysideluxcoredemo not working on linux

### ISSUE THREAD

**Issue by canwail** [LuxCoreRender/LuxCore#445]
Python version: 3.8.5
System: Linux x86_64

Steps to replicate:
Download "LuxCore API SDK release v2.4" (and extract)
Copy pysideluxcoredemo.py from /samples/pysideluxcoredemo to the root folder (so that relative imports are correct)

When running "python pysideluxcoredemo" then it gives the following output: 
```
$ python pysideluxcoredemo.py
LuxCore 2.4
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Windows, Fusion
[2020-09-13 15:34:44][SDL][0.154] Material definition: shell
[2020-09-13 15:34:44][SDL][0.156] Material definition: whitematte
[2020-09-13 15:34:44][SDL][0.156] Material definition: luxtext
[2020-09-13 15:34:44][SDL][0.156] Material definition: blacktext
[2020-09-13 15:34:44][SDL][0.156] Camera type: perspective
[2020-09-13 15:34:44][SDL][0.156] Camera position: Point[0.6, -1.7, 0.4]
[2020-09-13 15:34:44][SDL][0.156] Camera target: Point[0, 0, 0.4]
[2020-09-13 15:34:44][SDL][0.157] Camera clipping plane disabled
RPly: Error reading 'x' of 'vertex' number 0
Traceback (most recent call last):
  File "pysideluxcoredemo.py", line 729, in <module>
  File "pysideluxcoredemo.py", line 723, in main
  File "pysideluxcoredemo.py", line 62, in __init__
RuntimeError: Unable to parse PLY file 'scenes/luxball/room-nowall.ply'
```
I made a small test script that does just the scene loading up to the point where pysideluxcoredemo.py fails, which doesnt throw said error for some reason. Source for the (working) test file:
```
$ cat crashtest.py

import sys
sys.path.append("./lib")
import pyluxcore

props = pyluxcore.Properties("scenes/luxball/luxball-hdr.cfg")
props.Set(pyluxcore.Property("renderengine.type", ["PATHCPU"]))
scene = pyluxcore.Scene(
    props.Get("scene.file").GetString(), props.Get("images.scale", [1.0]).GetFloat(),
)

$ python crashtest.py # exits without error
$ 
```
This is the output when starting it in VSCode with debugger:
![image](https://user-images.githubusercontent.com/50383630/93021532-62ab5b80-f5e3-11ea-8e4b-e54b564fb91a.png)

**Comment by Dade916** [comment]
pysideluxcoredemo is working fine here (Ubuntu Linux). The scenes/luxball/room-nowall.ply may be corrupted. There can be problems with Git because it thinks it is a text file and may do a mess replacing LF/CR.

Try to replace your scenes/luxball/room-nowall.ply file with the original: https://raw.githubusercontent.com/LuxCoreRender/LuxCore/master/scenes/luxball/room-nowall.ply

**Comment by Dade916** [comment]
Another possible problem may be related to locale settings with standard C library may try to replace "." with "," etc.

This has been fixed in the latest sources but you will have to use the under development v2.5: https://forums.luxcorerender.org/viewtopic.php?f=9&t=736

**Comment by canwail** [comment]
ply file is "correct" according to hexdump and git was not used here
I temporary changed the LC_NUMERIC locale in my terminal to en_US.UTF8 and now it indeed works, thank you very much.

The daily build doesnt seem to have pysideluxcoredemo and libluxcore.so, were they removed? Or can I just compile libluxcore.so myself and replace the one from the v2.4 SDK release?

**Comment by Dade916** [comment]
We have 3 package versions: for Blender, Standalone and SDK. The SDK is unfortunately built only for the final release. However you can just use the pyxlucore.pyd file included in standalone version if you are using python. It is everything you need to update to use the very latest version with python.
The alternative is to build everything directly from sources, it is a relatively simple process described here: https://github.com/LuxCoreRender/LinuxCompile

**Comment by canwail** [comment]
Alright, thank you very much for your help.
