### ISSUE TITLE
White balance plugin "reverse" option makes result darker

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#448]
Scene: [wb.zip](https://github.com/LuxCoreRender/LuxCore/files/5241687/wb.zip)

This scene contains a meshlight set to 2600 K temperature, and the white balance plugin is set to reverse 2600 K.
The reversed result is a lot darker than I would expect.

Note that you need the latest BlendLuxCore sources to have support for the "reverse" option.

Without white balance plugin:

![no_wb](https://user-images.githubusercontent.com/1584761/93525098-cf9d5900-f935-11ea-85dc-a2cf7480f988.jpg)

With white balance plugin:

![with_wb](https://user-images.githubusercontent.com/1584761/93525101-d330e000-f935-11ea-8c25-a5aa7a8e9ab0.jpg)

**Comment by Dade916** [comment]
You have the ".normalize" options set on blackbody texture but not on white balance plugin. You have to set both on or off.

The image pipeline plugin orders also looks wrong (however it has not effect in this particular case):

```
film.imagepipelines.000.0.type = "NOP"
film.imagepipelines.000.1.type = "TONEMAP_LINEAR"
film.imagepipelines.000.1.scale = 1
film.imagepipelines.000.2.type = "WHITE_BALANCE"
film.imagepipelines.000.2.temperature = 2600
film.imagepipelines.000.2.reverse = 1
film.imagepipelines.000.2.normalize = 1
film.imagepipelines.000.3.type = "GAMMA_CORRECTION"
film.imagepipelines.000.3.value = 2.2
```

"WHITE_BALANCE" must be used before tone mapping, it is an HDR operation.

**Comment by Theverat** [comment]
Fixed in https://github.com/LuxCoreRender/BlendLuxCore/commit/6c4ac4ef032cab3689f7a9e265023ea5dc04ed7c.
