### ISSUE TITLE
GPU does not start if Glossy Coating Material is assigned

### ISSUE THREAD

**Issue by Dez1gner** [LuxCoreRender/LuxCore#453]
.blend file: 
https://dropmefiles.com/butTx

Steps to reproduce:
Apply to any material Glossy Coating Material. Start render in GPU

Screenshots or rendered images:
https://i.imgur.com/9Ye1pXP.png

Error message from Blender console:
Unknown eval. type in CompiledScene::CompileMaterialOps(16): 23

OS: Linux Manjaro
Blender version: 2.83.6
LuxCore version: 2.5

**Comment by Dade916** [comment]
I should have fixed the problem.
