### ISSUE TITLE
GLFW error 65544: No monitor found on Windows Remote Desktop Connection

### ISSUE THREAD

**Issue by tonka3000** [LuxCoreRender/LuxCore#456]
Hey,

I've get  an error (2.4) when I open luxcore via Windows Remote Desktop connection. Graphic card driver is already the latest.

`GLFW error 65544: No monitor found`

I'm not sure which OpenGL versions Windows Remote Desktop supports. Is there any way to lower the required OpenGL version via e.g. a commandline argument? Or is there any other trick to get that working?

Greetings

Tonka

**Comment by Dade916** [comment]
I assume you are talking of LuxCoreUI (?). Do you need the interactive graphics output ? I ask because you could use "pyluxcoretools console" and just do command line rendering with no UI output at all.

**Comment by tonka3000** [comment]
Yes, I mean LuxCoreUI. In my case in need the GUI.
