### ISSUE TITLE
direct light goes under glass but not back to camera

### ISSUE THREAD

**Issue by hitrpr** [LuxCoreRender/LuxCore#457]
I am trying to achieve light passing through glass and back (like witn architectural fakeglass) but keep caustics and refraction like with normal glass. And it looks like there is no way to get it, because direct light goes under glass and do not go back to camera.

This is architectural glass. Caustics are kept, but no refraction in the glass volume.
![untitled1](https://user-images.githubusercontent.com/21099918/95994070-80651e00-0e38-11eb-8ea8-097a9d3079a1.png)

Here regular glass…
![untitled](https://user-images.githubusercontent.com/21099918/95994074-822ee180-0e38-11eb-8c97-d663b670532f.png)

[luxtest thin glass.blend.gz](https://github.com/LuxCoreRender/LuxCore/files/5380513/luxtest.thin.glass.blend.gz)

Bidirect do the same…

**Comment by CodeFHD** [comment]
Under the normal glass, you have so called SDS paths which are mostly impossible to render, hence the dark image.
To render them in LuxCore, you need the "caustics cache". See modified blend file attached. The settings can probably be improved.

Here is also an example render. (Note that I moved the right glass dome a little.)

![sds](https://user-images.githubusercontent.com/48182552/96460125-2f33a080-1223-11eb-8938-043a8c4c8b1d.png)

[luxtest thin glass_chd.zip](https://github.com/LuxCoreRender/LuxCore/files/5402263/luxtest.thin.glass_chd.zip)

**Comment by hitrpr** [comment]
@CodeFHD  Thanks for helping me!
I understand problem and tried photons before, but failed. I'll compare files, atm I can`t figure out main the difference.  

And I can`t understand why direct-light photons do not work. Do they stop bouncing on diffuse under dome?
Sorry for disturbing, thanx a lot!

**Comment by hitrpr** [comment]
@CodeFHD Thanks a lot for wide explanation!
Last question: should I try to tackle Bidirect raytraycing, or it will not help anyway in case of SDS-rays?
I tried Bidir with default settings and failed. But may be there is something, that can help.
Should I try, or no way?

**Comment by CodeFHD** [comment]
No, it will not help with SDS.
