### ISSUE TITLE
Install issue due to invalid C++ redist from official guide

### ISSUE THREAD

**Issue by Chrisyss** [LuxCoreRender/LuxCore#460]
the usual install error for luxcore 2.4 blender 2.83.7 with C++ redistributables was only fixable by installing. 

- Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.27.29016
- Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.27.29016

The links provided by the official installation guide on the website is not sufficient enough on windows 10 64 bit

**Comment by Dade916** [comment]
The "usual install error" ? What do you mean ?

As far as I know, the Visual C++ 2015 runtime redristibutable linked in the first line of the Download page was the correct one and has worked for a long time. Wasn't it working for you ?

 May be, Microsoft has changed the landing page ?
