### ISSUE TITLE
CPU and GPU Render dont look the same

### ISSUE THREAD

**Issue by BobbyBronx** [LuxCoreRender/LuxCore#461]
I have missmatch between CPU and GPU Render

CPU
![cpuhykgv](https://user-images.githubusercontent.com/73343096/97025071-e0a24100-1557-11eb-9a6e-2038e0e9c2f1.png)

GPU
![gpuayk0b](https://user-images.githubusercontent.com/73343096/97025097-e861e580-1557-11eb-83e5-45c791cafce9.png)

Nodes
![nodes3akh6](https://user-images.githubusercontent.com/73343096/97025116-ee57c680-1557-11eb-80aa-f09201733cea.png)

Scene
[Lightbox1.zip](https://github.com/LuxCoreRender/LuxCore/files/5430484/Lightbox1.zip)

**Comment by Dade916** [comment]
I should have fixed this problem.
