### ISSUE TITLE
Matte Translucent material not working on GPU

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#463]
OS: Windows 10
GPU: Nvidia RTX 2080
Backend: CUDA and OpenCL

Scene: [matte_translucent_bug.zip](https://github.com/LuxCoreRender/LuxCore/files/5483404/matte_translucent_bug.zip)

Path GPU:

![gpu](https://user-images.githubusercontent.com/1584761/98027858-92b9f280-1e0d-11eb-976a-7f04ae14f6d3.jpg)

Path CPU:

![cpu](https://user-images.githubusercontent.com/1584761/98027863-96e61000-1e0d-11eb-8de7-1e7bc536d798.jpg)

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Confirmed, thanks.
