### ISSUE TITLE
Volume scattering ignored by laser light source

### ISSUE THREAD

**Issue by Acrivec** [LuxCoreRender/LuxCore#464]
.blend file: 
[volume scatter laser.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4907738/volume.scatter.laser.zip)

Steps to reproduce:
Create a homogenous volume with scattering, light it up with laser light source.

There are two cubes on the image, left one is lit up by area light source, second one by duplicated area light source with 'laser' check marked.

Worth noting:
If the laser light source is bigger than the object, scattering seems to work (see image 3 & 4).

Screenshots or rendered images:
![obraz](https://user-images.githubusercontent.com/26365504/87235324-43bdfc80-c3db-11ea-92e3-3be0554bf569.png)
![volume scatter laser_001](https://user-images.githubusercontent.com/26365504/87235281-c72b1e00-c3da-11ea-9f50-0d2fb40c5288.png)

![obraz](https://user-images.githubusercontent.com/26365504/87235320-3a349480-c3db-11ea-8251-fb15ba5b1bfc.png)
![volume scatter laser_003](https://user-images.githubusercontent.com/26365504/87235389-f5f5c400-c3db-11ea-85de-8c5f4ecc12cd.png)

![obraz](https://user-images.githubusercontent.com/26365504/87235397-0ad25780-c3dc-11ea-9360-d54109d3d75b.png)

Error message from Blender console:
-

**System Information**
Operating system: Windows-10-10.0.19041-SP0 64 Bits
Graphics card: GeForce GTX 980 Ti/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 451.48

**Blender Version**
Broken: version: 2.90.0 Alpha, branch: master, commit date: 2020-06-30 20:02, hash: `rBa3e6b7c2ce06`
LuxCore: 2.4 beta1

**Comment by Dade916** [comment]
This is expected: path tracing can render some part of a delta light only if it is intersectable and laser are not (i.e. point, spot, etc. are all delta light sources and they suffer of some limitation when using path tracing). BiDir is able to render the same scene.

This is a general limitation of path tracing however I could work around, a bit in this particular case, so it is also a limitation of current implementation of laser light source (i.e. it doesn't use direct light sampling but I could in some case).

P.S. both caches and light tracing are useless to render this particular scene.
