### ISSUE TITLE
LuxCore builds fail on macOS due to Bison syntax error

### ISSUE THREAD

**Issue by jamespa16** [LuxCoreRender/LuxCore#467]
On both macOS 10.15 Catalina and 11.0.1 Big Sur, LuxCore no longer compiles due to this Bison syntax error (with both make and Xcode):

`LuxCore/src/luxcore/luxparser/luxparse.y:20.14-35: syntax error, unexpected string, expecting =`

Not sure exactly what is wrong though, the file mentioned looks fine (that said, I don't really know much about Bison). This seems to be a relatively recent issue, it built a few weeks ago just fine if I remember right. 

Hardware:
Intel Mac mini i7-8700B + 32GB RAM, macOS 10.15.7.1 and macOS 11.0.1

**Comment by Dade916** [comment]
I may have fixed the problem, can you try with the latest sources ?

**Comment by jamespa16** [comment]
ah looks like not quite. Error changed though, so you're on the right track. 
`luxparse.y:20.9-18: syntax error, unexpected identifier, expecting string`
Changing the inside of the braces in the line you changed to a string (or swapping the braces for quotes too) didn't seem to fix it either. (gets exact same error) 

Looking into this further, they say on their docs that if you need more verbose errors you can start with `%define parse.error detailed`, however this define _also_ fails as a syntax error, so it seems it might not be a LuxCore issue, unless the problem is that its failing somewhere else down the file and it just returns the error at the beginning of the file.

**Comment by jamespa16** [comment]
OH wait! while I have the newest version of Bison installed via brew, the Xcode-CLI suite is using an older one, so its building with the 2.3 version of Bison - that's probably what needs fixed now.

**Comment by jamespa16** [comment]
Yep - forcing 3.7.3 + your fix now builds! I'll close this issue.
