### ISSUE TITLE
Full Blender crash with a material with displacement and subdivisio

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/LuxCore#469]
.blend file: 
[BUG_DISPLACE.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5543319/BUG_DISPLACE.zip)

Steps to reproduce:
Just open the example .blend and enable viewport render, then Blender crashes
The scene is pretty simple.

Screenshots or rendered images:

Error message from Blender console:
Here is the crash report:

[BUG_PARED_Interior_LuxCore_Displace.crash.txt](https://github.com/LuxCoreRender/BlendLuxCore/files/5543321/BUG_PARED_Interior_LuxCore_Displace.crash.txt)

OS: Linux Mint Tricia
Blender version: 2.90 and 2.83 LTS
LuxCore version: 2.5 Beta from 15/11/2020

**Comment by Dade916** [comment]
Sometime bugs are odd and easy to fix (check the patch linked above). I should have fixed the problem.

**Comment by juangea** [comment]
Hahaha these are the best bugs to fix... when you catch them 👍 
Awesome :)
