### ISSUE TITLE
Significant change in specularity when switching from GPU to CPU

### ISSUE THREAD

**Issue by MetinSeven** [LuxCoreRender/LuxCore#470]
Hi,

I noticed a significant change in specularity on surfaces when switching from GPU to CPU. The more glossy highlights a material has, the more visible the change is.

It seems purely related to GPU versus CPU, where the CPU rendering results look better by showing more specularity. The CPU result also corresponds with the same scene rendered in another renderer like Cycles.

Changing rendering methods doesn't seem to influence the difference. Path + Sobol shows the same specular highlights as Bidir + Metropolis when rendered with CPU.

Here's my pumpkin scene using GPU rendering:
![Halloween pumpkin by Metin Seven - GPU](https://user-images.githubusercontent.com/18738261/99509260-d40dde80-2985-11eb-8e8a-9c6847f4bf69.png)

And here is the exact same scene with the only change being GPU switched to CPU
— Notice the knife blade showing much more specular highlight, but the pumpkin skin and the eye also show more highlights:
![Halloween pumpkin by Metin Seven - CPU](https://user-images.githubusercontent.com/18738261/99509281-da9c5600-2985-11eb-99d3-ad128fc683ed.png)

I have already sent the scene to Simon via a PM at the Luxcore forum.

I'm using BlendLuxcore. My system configuration is:

Intel Core i9 9900K CPU
NVIDIA GeForce RTX 2080 Ti GPU
Windows 10 Pro 64-bit

**Comment by Dade916** [comment]
In need a simple test scene: can you try to isolate the problem ? For instance, can you erase everything but the blade, the light sources and background and post the scene ?

**Comment by MetinSeven** [comment]
Hi David,

No problem. I'll send the complete scene to you.

Thanks,

Metin

**Comment by MetinSeven** [comment]
I've emailed a link to the scene to your GMail address.

**Comment by Dade916** [comment]
I'm unable to open the file, it crashes my Blender (v2.83).

**Comment by MetinSeven** [comment]
Sorry, I made the scene in a recent alpha or beta version of Blender. It should open in 2.9x.

**Comment by juangea** [comment]
@MetinSeven have you noticed that the bump in the upper part of the pumpkin is also lost when you change from GPU to CPU?

**Comment by MetinSeven** [comment]
> @MetinSeven have you noticed that the bump in the upper part of the pumpkin is also lost when you change from GPU to CPU?

You're right. I overlooked that, because I had already rendered the scene with different renderers for a personal test, and each renderer displayed the bump map differently.

**Comment by Theverat** [comment]
It would help to have a scene that is reduced to the bare minimum necessary to reproduce the bug.
For example, you could do these steps, checking after each one if the problem still shows up:
* delete everything but the pumpkin and the main light
* replace the pumpkin with a sphere, but use the same material
* try to simplify the material, delete nodes while still reproducing the problem

The end result would save a lot of time for us developers.

By the way, it might be that there are multiple, possibly distinct, issues here:
* The reflections on the pumpkin
* The reflections on the knife
* The bump phenomenon

So it might make sense to simplify for each of these cases a different scene (simplified pumpkin, simplified knife, simplified bump)

**Comment by MetinSeven** [comment]
Hi @Theverat,

No problem. I'll try that tomorrow and report back.

**Comment by MetinSeven** [comment]
OK, I've done some tests: changed world environment from HDRI map to None, deleted the blue background and deleted lights, but the difference in specularity between GPU and CPU remains constant. It doesn't seem to depend on specific scene elements or materials.

Could it be that GPU rendering takes a slightly different approach to the specular calculations than CPU rendering, because some calculations are not suitable for a GPU? I know that Keyshot and Maxwell remained CPU-only for a long time because of this.

**Comment by MetinSeven** [comment]
In the #support channel of the LuxCoreRender Discord server, user Mischterlampe has posted a video showing the same specularity difference issue when switching between GPU and CPU.

**Comment by mischterlampe** [comment]
Here is the mentioned video.
https://streamable.com/x6yj47

**Comment by Dade916** [comment]
> Here is the mentioned video.
> https://streamable.com/x6yj47

I need a test scene.

**Comment by JonSargent** [comment]
I made a potentially related observation yesterday while running validation tests. I was going to hold off on posting until I'd had a chance to reproduce on other graphics cards, but perhaps there's a link to Metin's finding, so here goes. 

[This zip file](https://github.com/LuxCoreRender/LuxCore/files/5570493/ocl_specular_reflection_issue.zip) contains two stripped down test scenes:

- **Simple example**: Just an ortho camera pointing at a glossy2 surface, with a light behind the camera view. Pixel rays leave the camera, bounce off the test surface at normal incidence, and then hit the light (which has a luminous intensity of 1). As far as specular reflection tests go, this is as simple as it gets. A surface with kd=0 and ks=0.5 should have a luminance of 0.5 in the rendering. This is exactly what the PATHCPU engine reports. The PATHOCL engine, on the other hand, reports a value that's 12% too low -- at least on my GPU (NVIDIA GeForce RTX 2080 Ti, see log for details). The simulation has converged nicely, so noise is not to the issue.
![spec reflection](https://user-images.githubusercontent.com/15347685/99743258-2cc69f80-2a8a-11eb-8f81-35019a8124b2.png)

- **Incidence angle study**: Similar logic, but using 90 surfaces angled away from the camera plane in 1-degree increments (from 0 to 89 degrees). Just a cheap hack for turning one ortho rendering into a discrete plot of specular reflection vs. incidence-angle. Here's what it shows for glossy2 surfaces with ks=0.25, 0.5, and 0.75. The PATHCPU results are spot on. Ks values fit exactly, and the fresnel effect pushes the reflectance toward 1 at grazing angles, as expected:
![image](https://user-images.githubusercontent.com/15347685/99744541-bc6d4d80-2a8c-11eb-8ace-2809911f3a89.png)
The PATHOCL results, though, are again systematically low:
![image](https://user-images.githubusercontent.com/15347685/99744979-92685b00-2a8d-11eb-9872-f77d8c8ebcea.png)
Plotting the _relative_ error looks like this:
![image](https://user-images.githubusercontent.com/15347685/99745088-d0657f00-2a8d-11eb-9d3e-23a141110144.png)
Three different ks values, every possible incidence angle, same result: a systematic error of about -12%. I haven't been brave enough to wade into the CL engine code, but hopefully the pattern points to a simple cause? Let me know if I can be of use with troubleshooting. I should have access to a few other GPUs over the course of the next week, so I can at least see if the pattern repeats.

**Comment by MetinSeven** [comment]
Thanks @JonSargent . You observations match my impression that the specularity difference is more apparent at the sides, where Fresnel is the strongest.

**Comment by mischterlampe** [comment]
I can't reproduce it right now.

**Comment by JonSargent** [comment]
Interesting. @mischterlampe did you change any config params aside from "renderengine.type"? I should mention that the discrepancy occurred on my end for glossy2 and glossytranslucent, but not glass or archglass.

**Comment by MetinSeven** [comment]
To my experience, the more prominent glossiness is in a material, the more apparent the difference is. For example, the metal blade in my pumpkin scene shows the most radical difference, where the CPU rendering looks the best, and corresponds with the same scene rendered with Cycles.

**Comment by Dade916** [comment]
@MetinSeven, I have installed Blender 2.90 but loading your scene still crash my Blender here.

I still need a simply test scene.

**Comment by MetinSeven** [comment]
Tried it in the Blender 2.9.1 release version. You're right, it crashes. Probably because I created it in a 2.91 alpha / beta version. Could you please try the [Blender 2.91 beta or 2.92 alpha build](https://builder.blender.org/download/)? It should work in there. Sorry for the inconvenience.

**Comment by JonSargent** [comment]
@Dade916 the [test scenes](https://github.com/LuxCoreRender/LuxCore/files/5570493/ocl_specular_reflection_issue.zip) I posted above are sufficient to illustrate the issue. No Blender required. 

Repeating the "simple_example" test on other devices revealed the following relative errors for PATHOCL glossy2 specular reflectance:

-  NVIDIA RTX 2080 Ti (as above): -12%
-  Radeon Pro 560: -21%
-  Radeon RX 5600 XT: -72%
-  Intel Core i5-5287U CPU: 0%

It's clear that the magnitude of the error is GPU specific -- and non existent when building the same CL kernels on a CPU (at least on the one compatible device I have). It's also clear that scope of the error is limited. The diffuse component calculates just fine, as does the specular component for non-glossy materials (e.g. glass). Not sure what about the SchlickBSDF_Coating* cl funcs (?) could be device sensitive, but maybe that's a place to start looking.

**Comment by Dade916** [comment]
@JonSargent, your problem is likely to not be related to the one in this thread: you may want to open a separate issue.

**Comment by Dade916** [comment]
> Tried it in the Blender 2.9.1 release version. You're right, it crashes. Probably because I created it in a 2.91 alpha / beta version. Could you please try the [Blender 2.91 beta or 2.92 alpha build](https://builder.blender.org/download/)? It should work in there. Sorry for the inconvenience.

It still crash with v2.91beta.

**Comment by MetinSeven** [comment]
Damn. 😐 Maybe there's a conflicting add-on or so. What a hassle.

I've got 2.9.1 installed at the moment. I'll install download 2.92 alpha next to that and see if I can open it without a crash.

**Comment by MetinSeven** [comment]
The scene opens without a crash in Blender 2.92 alpha (no add-ons installed). I might have re-saved the scene in Blender 2.92 alpha, which probably causes the crash in earlier versions.

Again, sorry for the inconvenience.

**Comment by Theverat** [comment]
This is one of the reasons why we say that a specific Blender version is "supported" by us: Because we only want to have one Blender version installed and not dozens, and we don't want to update them all the time, or try to guess if some bugs come from our beta software or from an alpha/beta Blender build.
Please make sure that your testscenes can be loaded and used in the officially supported Blender version (currently, 2.83) and the problem can be reproduced there. Everything else puts a lot of menial and annoying work on us developers.

**Comment by MetinSeven** [comment]
I understand, but you should be only a 2.92 download away from checking this not-so-minor issue. Blender is portable, so you can run it right after unpacking the Zip.

I've deinstalled 2.92 myself again, so I'd need to download it again, try to find out why the scene crashes in an earlier version, make changes and share the scene again with a new download link. I'm working on a deadline job in 2.9.1 right now, sorry.

**Comment by JonSargent** [comment]
> @JonSargent, your problem is likely to not be related to the one in this thread: you may want to open a separate issue.

👌 Moved [here](https://github.com/LuxCoreRender/LuxCore/issues/474#issue-748274900).

**Comment by Dade916** [comment]
The problem is triggered by light tracing, if you disable light tracing you get the same result. This is CPU rendering without light tracing:

![cpu](https://user-images.githubusercontent.com/3247881/99953814-1f5b2f00-2d82-11eb-8586-8d2bb29765a6.png)

and this is GPU rendering without light tracing:

![gpu](https://user-images.githubusercontent.com/3247881/99953882-339f2c00-2d82-11eb-8010-bedc27254960.png)

I will check what is going wrong with light tracing.

**Comment by MetinSeven** [comment]
Great that you've found the cause, and I'm glad you could open the scene. 😅

**Comment by Dade916** [comment]
I should have fixed this problem.

**Comment by Dade916** [comment]
@JonSargent, I can confirm this has nothing to do with your problem (I guess you are not using light tracing).

**Comment by MetinSeven** [comment]
Great job, @Dade916 ! Will the next BlendLuxCore build incorporate the fix?

**Comment by Theverat** [comment]
It should already be included in the current "latest build", unless something went wrong.

**Comment by MetinSeven** [comment]
Great, thanks @Theverat , and apologies to you both for the alpha version hassle.

**Comment by MetinSeven** [comment]
Sorry, one more question:

@juangea mentioned that the bump is not visible anymore in the CPU rendering. Is this also fixed along with this issue, or is that a separate case?

**Comment by juangea** [comment]
In latest @Dade916 test bump is not visible in GPU rendering, so maybe it was something kind of broken on the bump side of things

**Comment by MetinSeven** [comment]
It's a bit hard to see in @Dade916's renderings because of the graininess, but I guess it's worth checking if the bump map is equally visible when switching between CPU and GPU. I'll install the latest LuxCore build and check it as soon as I've escaped the grip of the deadline monster.

**Comment by MetinSeven** [comment]
Hi,

I finally had the time to test the bump map on GPU and CPU, and I can confirm that the bump map is only visible using GPU rendering, not when rendering with CPU.

I'll open a new issue for this.

**Comment by MetinSeven** [comment]
The specularity (this issue) seems to be alright now, so I guess this issue can be closed.
