### ISSUE TITLE
(QUESTION) Can LuxCore be "turboed" ? - explanation inside

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/LuxCore#471]
This is a question, not a bug or a problem.

One of the ways to accelerate Cycles is to give more steps per sample to the GPU, that way it crunches more data in every step, the counterpart is that you can loose responsiveness from that GPU and you loose the bucket preview, not so bad when it accelerates Cycles quite a bit.

It may not be the best thing to do for general users, since this puts more presure over the GPU and can make windows to show the white veil over the app, but it is good for those that know what they are doing.

Can something like that be applied to LuxCore with CUDA/OPTIX (not sure about OpenCL) or is that done already?

I searched for the amount of samples given to the GPU on each iteration and for something like steps per sample and I found nothing, something I already expected since the code and variables are totally different :)  

Cheers!

**Comment by Dade916** [comment]
There is a parameter to set the amount of GPU "tasks" to run at the same for PATHOCL. It works pretty much as the Cycles parameter. You have also to keep in mind that it increase the amount of memory used (there is a fixed cost for each task). It is not a small amount of memory.

The default value is set here (https://github.com/LuxCoreRender/LuxCore/blob/923e493748c2c0b55ec5b94fbc9cff4e80895801/src/slg/engines/pathocl/pathocl.cpp#L229) according the amount of GPU ram:

- 512k tasks for 8+ GB cards
- 256k tasks for up to 8 GB cards
- 128k tasks for up to 4 GB cards
- 64k tasks for up to 2 GB cards

The property to set is "opencl.task.count". It can be set in render.cfg file or inside BlendLuxCore code.

There is a log line showing the task count used:

`[LuxCore][0.281] [PathOCLRenderEngine] OpenCL task count: 262144`

This is a rendering with 256k tasks:

![256k](https://user-images.githubusercontent.com/3247881/99794288-39023980-2b2a-11eb-949d-5307cac9b06b.jpg)

And this with 1M tasks:

![1M](https://user-images.githubusercontent.com/3247881/99794324-44edfb80-2b2a-11eb-8c5a-753a725076eb.jpg)

Notice the samples/sec and the amount of memory used: an high cost for a little advantage.

With TILEPATHOCL, you can use the AA samples to increase the amount of tasks. There is one task for each sample in the current tile.

Note: if you want to try the parameter, use the latest sources because I removed a cap to the value to allow more freedom when the parameter is set.

**Comment by Theverat** [comment]
@juangea If you want to do tests with this parameter in BlendLuxCore, insert it here in line 70: https://github.com/LuxCoreRender/BlendLuxCore/blob/master/export/config.py
You will have to restart Blender after each edit to the file.

**Comment by juangea** [comment]
Thanks to both of you!

I'll do some tests and see if there is any impact regarding the GPU's I have.
I'll test in a GTX1080, a GTX970 and an RTX2080Ti, I'll come back to you with the results and see if there is any outcome.

In Cycles a thing that affected a lot to this was the tile size, but in this case I assume there is no effect because it's progressive.

THANKS!

**Comment by Theverat** [comment]
It might be a good idea to create a plot of speed vs. memory usage at different task count values, then looking for a good balanced sweet spot. However judging from Dade's examples, the automatically chosen values seem already pretty good.

**Comment by juangea** [comment]
I like the heuristic idea, however I would leave that as an option for the user, kind of "optimize GPU load for your scene", or something like that.

I'll try a scene I use for my ArchViz course, it's a simple one, but a bit more complex than a cornell box :) 
Maybe the load balance is different in a more complex scene, and with or without CUDA.

The other option is to allow the user to "force" the machine, so just put a "Turbo" button, like with the 486 DX2 hahaha
The speed gain may be small, but if we save some minutes out of a 45 minutes render, it's something, specially if we talk about animation :)

**Comment by juangea** [comment]
BTW @Dade916 @Theverat if you removed the cap recently, is it removed in today's build already or I have to wait until tomorrow?

**Comment by Theverat** [comment]
Just check the commits (they can be found on the front page of each github repository).
If there's a green checkmark besides the commit message, the automatic build has been completed.

**Comment by juangea** [comment]
I managed to add the property to the UI in order to avoid re-starts between tests and what I found so far is interesting.

Using 64 * 1024 as task count it's true that the render is slower, these are the times for my test scene:

"AUTO" - 1 minute 14.0 seconds
32 - 1 minute 15.5 seconds
64 - 1 minute 17 seconds
128 - 1 minute 17.5 seconds
256 - 1 minute 15.2 seconds

HOWEVER the memory consumption reduction was pretty cool, these are the numbers:

"AUTO" - 1953 Mb
32 - 1390 Mb
64 - 1470 Mb
128 - 1631 Mb
256 - 1953 Mb

And you may wonder why there is no bigger number than 256, it's because no matter what number I use, the value of "OPenCL task count" never goes over the corresponding for 256, so I assume the cap is still affecting somewhere, because the LuxCore change was from 12 hours ago and the latest BlendLuxCore build was from 3 hours ago, so the cap patch should be in, but I'm still getting limited values.

I'll check tomorrow in case there is a new build, but I suspect something else is capping that value.

At least so far I did not get an acceleration on the render yet, but the memory reduction could be interesting and may be the difference to having to use Out of Core or not use it at all :) 

Could be great if you can confirm that the cap is not working anymore and I can put values like 512 or 1024, because so far they are not working :)

I'm eager to find the difference with those values! :D

**Comment by Dade916** [comment]
It is working fine here:

```
david@Desktop-3900x:~/projects/luxcorerender/LuxCore$ /home/david/projects/luxcorerender/LuxCore/bin/luxcoreui -D opencl.task.count 1000000 scenes/cornell/cornell.cfg 
LuxCoreUI v2.5beta1 (LuxCore demo: http://www.luxcorerender.org)
[LuxCore][0.002] Configuration: 
[..]
[LuxCore][0.411] [PathOCLRenderEngine] OpenCL task count: 1007616
```

Are you sure to not still using the old binaries ?

**Comment by juangea** [comment]
No, I'm not sure XD 

The build was the latest BlendLuxCore that was ready yesterday, since the change was green in LuxCore and it was done 12 hours ago, and the BlendLuxCore build was 3 hours old I assumed that it should have been in that binary.

Should I download the latest binary separatedly? it's not included in the latest BlendLuxCore?

**Comment by juangea** [comment]
OMG... I'm SUUUUURE that I don't have the latest binary... I downloaded the Beta and not the latest release... it was late... it was night... I was tired... OMG sorry...

I'll repeat the tests later, sorry for this.

**Comment by juangea** [comment]
I changed a thing in the scene, I disabled the cache and the denoiser, just to avoid the cache and denoise computation time, I'll repeat tests with persistent cache, but later.
I also disabled the CPU, since this is a pure GPU parameter.
These tests are being done with a GTX1080 / 8Gb.

So far these are the results:

"AUTO" - 1 minutes 35.6 seconds - 1919 Mb VRam
32     - 1 minutes 43.5 seconds - 1356 Mb VRam
64     - 1 minutes 36.9 seconds - 1436 Mb VRam
128   - 1 minutes 35.7 seconds - 1597 Mb VRam
256   - Same as "AUTO"
512   - 1 minutes 35.6 seconds - 2563 Mb VRam
1024 - 1 minutes 36.8 seconds - 3851 Mb VRam

So far, with my current tests I don't see a clear benefit in increasing the amount of tasks, at least with this card and this scene, however there is a benefit on reducing from 256 to 128 with a small penalty in render time.

I'll do more tests with more samples and resolution, this seems interesting so far :)

**Comment by juangea** [comment]
Ok, I repeated the tests with a smaller image but way more samples and there I was able to see a difference.

I suspect that as long as the render has enough samples to leverage the amount ot tasks provided it can gain performance, but if the samples are lower then there is no performance gain.

Just a suspicion so far, I need a bit more of time to do the tests with long renders, not 1 / 2 minutes renders in low res, but this parameter seems to be very interesting, I think ti could be useful for advanced users only, but could be useful nevertheless.

**Comment by Dade916** [comment]
I guess we can close this one.

**Comment by juangea** [comment]
Yes, you can close it.

What I've found so far is that there is a benefit IF you render the image to a similar amount of tasks and samples, so for example 512 as the task number would benefit a scene with 512 samples or more, but it will also have a big penalty in memory.

I found that this could be an interesting option to reduce the memory footprint in very loaded scenes, so you can avoid using "Out Of Core", it's not a big marging but it may "save" you, and I assume the speed penalty would be less than the OOC penalty.

I want to do some more testing in production scenes, but so far I agree, the defaults are good enough, at least for the time being 👍
