### ISSUE TITLE
Rendering a huge amount of particles

### ISSUE THREAD

**Issue by PavelBlend** [LuxCoreRender/LuxCore#477]
Hello.

Is it possible to render a huge amount of particles in luxcorerender? Without using a standard blender particle system. I need to render 125 million particles. Like here:
https://youtu.be/oiuSax_iPto

So that rendering does not take up a lot of RAM. The blender particle system takes up a lot of RAM space. I want to be able to render compact particle systems. Here is the code that generates data for the particle system.
```python
import numpy, time, locale


locale.setlocale(locale.LC_ALL, '')
start_time = time.time()
MEGA_BYTE = 2 ** 20
axes_count = 3
cube_length = 500    # 500 particles
cube_size = 1.0    # 1 meter
psize = cube_size / cube_length    # particle size
pcount = cube_length ** 3    # particles count
pos = numpy.empty((pcount, axes_count), dtype=numpy.float32)    # particles positions
vel = numpy.empty((pcount, axes_count), dtype=numpy.float32)    # particles velocities
col = numpy.empty((pcount, axes_count), dtype=numpy.float32)    # particles colors

for i in range(cube_length):
    for j in range(cube_length):
        for k in range(cube_length):
            pindex = i * cube_length * cube_length + j * cube_length + k    # particle index
            pos[pindex] = (psize * i, psize * j, psize * k)
            vel[pindex] = (0.0, 0.0, -psize)
            col[pindex] = (0.1, 0.1, psize * k)

total_time = time.time() - start_time
print('\n' * 3)
print('\t{:<25}=    {:.2f} seconds'.format('total time', total_time))
print('\t{:<25}=    {:.2f} MB'.format('particles data size', (pos.nbytes + vel.nbytes + col.nbytes) / MEGA_BYTE))
print('\t{:<25}=    {:n}'.format('particles count', pcount))
print('\n' * 3)
input('OK!')
```

I want to be able to specify the positions, speeds and colors of the particles for luxcorerender, bypassing the blender's particle system.

125 millions particles will take up 4.2 GB of RAM.

**Comment by Theverat** [comment]
You can generate a (flat) list of transformation matrices which describe the location, rotation and scale of each particle. Then define a LuxCore object, and use the `DuplicateObject()` function to duplicate it with the transformation matrix list.
This is how instances are created in BlendLuxCore: https://github.com/LuxCoreRender/BlendLuxCore/blob/8770806c716581baf6aa3f20ecc6ff68739c3e47/export/caches/object_cache.py#L247

**Comment by PavelBlend** [comment]
@Theverat is it possible to specify a color for particles?

**Comment by Theverat** [comment]
There is no dedicated color property for instances, but you can use the object ID for this if you don't need it otherwise.
You can pass a list of object IDs to `DuplicateObject()` and use it in the material with the "objectidcolor" texture: https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.5#Type:_objectidcolor
