### ISSUE TITLE
Clamp etc. does not work with any channel other than "default"

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#48]
I would expect clamp/black/white wrap modes to also work when the channel is set to red/alpha/mean/...
Currently on all channels but default it seems like the wrap mode is fixed to "repeat".

![scrn_2018-01-18_11-38-40](https://user-images.githubusercontent.com/1584761/35094079-85b0ee06-fc44-11e7-8c31-634490c77667.png)
(The red channel is not clamped, but repeated)

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Thanks!
