### ISSUE TITLE
Reflected laser ray disappears before reflection point (not sure if a bug)

### ISSUE THREAD

**Issue by thima2017** [LuxCoreRender/LuxCore#485]
The problem is shown on following gif. The laser rays looks normal while they aren't reflected. If they are reflected lasers disappear before theirs reflection points. Is it normal? Is there an explanation if so?
![vokoscreen-2020-12-15_02-22-01 mp4](https://user-images.githubusercontent.com/32433505/102149117-c95c4180-3e7e-11eb-996d-da6f277a6bbf.gif)
[zk-283.blend.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/5692220/zk-283.blend.zip)

**Comment by Dade916** [comment]
Your scene is malformed: you need to set the outside volume of the material of the "spiral" (or to any other object inside the scattering volume). It isn't set so LuxCore uses the default scene volume (i.e. nothing, clear space). LuxCore deduces the volume a ray was traveling trough when it hits a surface.

Once you set the materiel exterior volume, it will work fine:

![Screenshot from 2020-12-15 13-05-33](https://user-images.githubusercontent.com/3247881/102212968-4e267a00-3ed6-11eb-9269-08aa0a0e550a.png)

**Comment by thima2017** [comment]
Thank you, it works
