### ISSUE TITLE
CUDA Issue (ptx compilation fails)

### ISSUE THREAD

**Issue by howetuft** [LuxCoreRender/LuxCore#490]
When I try to render a scene (for instance, scenes/simple/simple.cfg), rendering fails with the following message:

`RUNTIME ERROR: CUDA driver API error CUDA_ERROR_UNSUPPORTED_PTX_VERSION (code: 222, file: src/luxrays/utils/cuda.cpp, line: 221): the provided PTX was compiled with an unsupported toolchain.
`

Don't know if it is related, but the PTX files in ~/.config/luxcorerender.org/cuda_kernel_cache/LUXRAYS_2_5beta1 start with 4 weird characters:

```
«Ó©//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-29373293
// Cuda compilation tools, release 11.2, V11.2.67
// Based on NVVM 7.0.1
//

.version 7.2
.target sm_52
.address_size 64

	// .globl	Film_MergeBufferInitialize
[...]
```
When I try to compile manually those PTX with nvcc, it fails (`ptxas d25db7a6-1c234bc9.ptx, line 1; fatal   : Missing .version directive at start of file 'd25db7a6-1c234bc9.ptx'`). But if I remove the 4 faulty characters, it succeeds. However the correction is not persistent, files are replaced each time I launch Luxcore...

Many thanks in advance for your help.

OS: Arch Linux
GPU: GeForce GTX 750 Ti
CUDA: release 11.2, V11.2.67

**Comment by Dade916** [comment]
LuxCore include NVRTC (NVIDIA Run Time Compiler) from CUDA 10 so it requires driver supporting CUDA 10 or better. It looks like your GPU drivers are too old.

Our PTX cache file has a 4 bytes checksum at the start to avoid corrupted files: https://github.com/LuxCoreRender/LuxCore/blob/e738b0543cc49c4b29e43723329986599b7fdfbf/src/luxrays/utils/cuda.cpp#L153

**Comment by howetuft** [comment]
Thank you for your answer!
You were right, there was a discrepancy between my GPU driver version (in the present case: 11.1) and the runtime compiler version (11.2), which prevented PTX loading by the driver. It originated from my distro, and was fixed this week. Thanks again.
