### ISSUE TITLE
Says CL_OUT_OF_RESOURCES when rendering for second time.

### ISSUE THREAD

**Issue by AndGuz** [LuxCoreRender/LuxCore#494]
i am having the OpenCL driver API error (code: -5, file:D:\a\1\Luxcore\src\luxrays\devices\ocldevice.cpp, line: 321): CL_OUT_OF_RESOURCES when i render for a second time or change the engine back and forth between PATHOCL and PATHCPU. this is happening too in the blendluxcore implementation.

Bug Replicating Procedure:
Render with the PATHCPU for a time then change the engine to PATHOCL and change it again.

Hardware:
Intel Celeron N4000 @1.10GHZ (dual core)
Intel UHD Graphics 600 (supports opencl 1.2 neo)
Ram: 4gb

Software:
Windows 10 Pro Education 2001

Thanks!

**Comment by Dade916** [comment]
Intel UHD Graphics 600, is a very limited GPU compared to high-end NVIDIA/AMD for computing task. The Intel OpenCL drivers have been also unable to run any complex code for years (probably because the underlaying hardware is just too limited).

I assume the driver throw a CL_OUT_OF_RESOURCES because it is simply running out of memory/resources/etc.

Does LuxMark work on the same hardware ?

**Comment by AndGuz** [comment]
I'm going to try, cuz I actually rendered some things but immediately after it opened. But if I rendered a image and I try to render ir again it says that. Thanks for your response

**Comment by AndGuz** [comment]
![ovni](https://user-images.githubusercontent.com/62262763/104975147-3f008380-59d0-11eb-93f1-3312ed6bdeb8.png)
I rendered this with the GPU+CPU, 256 samples and 20 min render time.

**Comment by AndGuz** [comment]
Maybe its a bug in the intel driver and not on luxcore OCL.

**Comment by AndGuz** [comment]
![Captura de pantalla (217)](https://user-images.githubusercontent.com/62262763/105034321-b1548080-5a2f-11eb-84f1-fe7c13f6e557.png)
It Works perfectly but with a low score Dade916
![Captura de pantalla (216)](https://user-images.githubusercontent.com/62262763/105034355-bc0f1580-5a2f-11eb-9288-03d7a1ca245a.png)

**Comment by AndGuz** [comment]
![imagen](https://user-images.githubusercontent.com/62262763/105034948-a5b58980-5a30-11eb-810b-1a7ce755d939.png)
