### ISSUE TITLE
Feature request: alpha support for transparent materials

### ISSUE THREAD

**Issue by MetinSeven** [LuxCoreRender/LuxCore#495]
I'd like to request alpha channel support for transparent materials.

For example: I need to render cars with semi-transparent windows against a transparent background. It would be great if I could use architectural glass and render that half-transparent on a transparent background.

Many thanks.

**Comment by jiabaoyu** [comment]
Terribly useful for product rendering too!

**Comment by Dade916** [comment]
It should already work if you use object transparency: try to use mirror material and to set something like a 50% transparency for the car glass.

**Comment by MetinSeven** [comment]
Thanks! Before posting this request a few users at the Luxcore Discord stated it isn't possible.

**Comment by jiabaoyu** [comment]
> It should already work if you use object transparency: try to use mirror material and to set something like a 50% transparency for the car glass.

Unfortunately, that's not what I've mentioned. I'm hoping for partial transparency with refraction material. 
Here's a example of cycles:

![image](https://user-images.githubusercontent.com/12813865/105578544-07bd1880-5dbc-11eb-8b90-ea3e3c67cec6.png)

**Comment by Dade916** [comment]
Material transparency is a generic LuxCore material attribute available for any kind of material: mirror, glass, etc.

**Comment by jiabaoyu** [comment]
> Material transparency is a generic LuxCore material attribute available for any kind of material: mirror, glass, etc.

Thanks. Is what you said be the opacity parameter? I'm using 2.5 beta1
![image](https://user-images.githubusercontent.com/12813865/105579109-6a63e380-5dbf-11eb-95c0-7e09c1c8ca09.png)

**Comment by Dade916** [comment]
Yes, it is called transparency in LuxCore API and opacity inside Blender (it follows alpha channel rule: 1.0 solid, 0.0 transparent).

**Comment by jiabaoyu** [comment]
OK. That's not what I want. BTW, is there any plan lux can get the same effect as I mentioned above? The opacity parameter makes semi-transparent, while the "Transparent Glass" option in cycles which  makes partial-transparent is a global effect. The tooltip says like this:
![image](https://user-images.githubusercontent.com/12813865/105579648-ab112c00-5dc2-11eb-90c4-de0584388d7c.png)
While from my understanding, it makes "areas whoes refraction of the environment light beyonds 10%, then it's transparent". I may be totally wrong. But I use it a lot when rendering products made of glass like water bottles.

**Comment by Theverat** [comment]
> It would be great if I could use architectural glass and render that half-transparent on a transparent background.

Archglass already has the behaviour you describe:

![Capture](https://user-images.githubusercontent.com/1584761/105918228-e1a1ad80-6033-11eb-9155-615dadfb8dab.PNG)

**Comment by MetinSeven** [comment]
> > It would be great if I could use architectural glass and render that half-transparent on a transparent background.
> 
> Archglass already has the behaviour you describe:
> 
> ![Capture](https://user-images.githubusercontent.com/1584761/105918228-e1a1ad80-6033-11eb-9155-615dadfb8dab.PNG)

Thanks! Didn't know that. 👍
