### ISSUE TITLE
Can't Render Hair Curly

### ISSUE THREAD

**Issue by cliffnhansen42** [LuxCoreRender/LuxCore#496]
I am having an issue which may be a bug or a feature limitation with LuxCore in Blender. I have a character with curly particle hair mostly using the kink settings. While it appears properly in the eevee-based viewport, when I switch over to Luxcore preview or render things start getting strange. The hair renders as either straight, or as mostly straight with a few rough curls.

Please note that in the following images, I'm only referring to the shape of the hair and not the materials applied to it.

This is what it is supposed to look like as per the Eevee viewport:
![luxcore-viewport](https://user-images.githubusercontent.com/34868005/105611974-b128ed80-5d6d-11eb-8239-8959c97ba4a5.png)

This is what is looks like in the Luxcore viewport:
![luxcore-viewport3](https://user-images.githubusercontent.com/34868005/105612005-ca319e80-5d6d-11eb-8fe4-c7f7633d90ca.png)

Things get even worse when I actually render:
![luxcore-render](https://user-images.githubusercontent.com/34868005/105612098-8db27280-5d6e-11eb-988e-2fb65d706b90.png)

I'm using a brand new computer with everything mostly up to date. Is curly hair not a feature LuxCore supports, or do you think it's a bug? I am new to LuxCore, but not new to Blender and am happy to answer any questions you might have in pursuit of fixing this. I'd much rather prefer to use LuxCore for this project as I'm really happy with how it handles the rest of the scene and I don't want to start dealing with complicated issues of rendering parts of the scene in different browsers. You can see my system information here: [https://drive.google.com/file/d/1LcS8y5UCcM-xD8KwIVwSheftAq69BPDj/view?usp=sharing](url)

Here's a copy of the Blend File if it can help you reproduce the problem: [https://drive.google.com/file/d/1VZ1azon1gOYoDBIFiP5CGC8-UKrmdXCl/view?usp=sharing](https://drive.google.com/file/d/1VZ1azon1gOYoDBIFiP5CGC8-UKrmdXCl/view?usp=sharing)

I appreciate any help you can offer! Luxcore is so amazing!

**Comment by cliffnhansen42** [comment]
I realized I wasn't at the most recent stable version of Blender when I'd posted the above, so I upgraded and tested it again but got the same results.

**Comment by cliffnhansen42** [comment]
I just tried this in Cycles and had the same problem, so it looks like it's a larger Blender problem and probably has nothing to do with LuxCore...

**Comment by Dade916** [comment]
LuxCore tessellates the hairs/strands with triangles so first thought was that your problem was related to an insufficient tessellation, etc.
However if you can reproduce the same result with Cycles, it must something related to an internal Blender problem.
