### ISSUE TITLE
haltSPP_ScreenNormalized check not working correctly

### ISSUE THREAD

**Issue by BeheadedKamikaze** [LuxCoreRender/LuxCore#497]
It appears that in the comparison in the first halt case (line 1356), the variables for samples completed (`spp_ScreenNormalized`) and the user setting (`haltSPP_ScreenNormalized `) have been swapped, resulting in the render terminating as soon as the eye samples have completed (assuming the eye samples complete before the light samples do).

https://github.com/LuxCoreRender/LuxCore/blob/b8822419ca5ef2c676a57a1bf9d20908d1697273/src/slg/film/film.cpp#L1356

I think it should appear like the check in the third case (line 1366):

https://github.com/LuxCoreRender/LuxCore/blob/b8822419ca5ef2c676a57a1bf9d20908d1697273/src/slg/film/film.cpp#L1366

Potential bug: should the user's CPU be much faster than their GPU, `spp_ScreenNormalized` exceeds the user setting before `spp_PixelNormalized` does, then the render might never complete.

**Comment by Dade916** [comment]
Thanks, I should have fixed the problem.

**Comment by BeheadedKamikaze** [comment]
Thank-you, Dade!
