### ISSUE TITLE
Emissive material emits only on one side.

### ISSUE THREAD

**Issue by errantspark** [LuxCoreRender/LuxCore#503]
Light emitting materials appear to emit only on one side, even when using a double sided material light emission only happens on the front side. Flipping the normals swaps emitting sides. Mirroring the plane across the Y axis causes the front side to stop emitting and the back side to start emitting. I think in all these cases the expectation is that both sides would emit.

## Default
![image](https://user-images.githubusercontent.com/623916/108640597-7f2fa780-744f-11eb-9b9e-33d511e77670.png)
## Two Sided Material
![image](https://user-images.githubusercontent.com/623916/108640587-6fb05e80-744f-11eb-9203-5c2a1ed518b0.png)
## Flipped Normals
![image](https://user-images.githubusercontent.com/623916/108640622-aa19fb80-744f-11eb-91c5-31105df911af.png)
## Mirrored across Y-axis
![image](https://user-images.githubusercontent.com/623916/108640648-ce75d800-744f-11eb-873a-46ea51c4c17f.png)
![image](https://user-images.githubusercontent.com/623916/108640652-d766a980-744f-11eb-8547-55419146b9ae.png)

|Orientation | Result   | 
|---|---|
|Baseline| +Normal Emits|
|Flipped Normals| +Normal Emits|
|Mirrored| -Normal Emits|

Here's the offending file in the mirrored state.
[doublesided_emission.zip](https://github.com/LuxCoreRender/LuxCore/files/6018749/doublesided_emission.zip)

**Comment by Dade916** [comment]
> Light emitting materials appear to emit only on one side

Yes, this is the expected and correct behavior (for obvious reasons, you don't want to emit light inside walls, etc.).

> even when using a double sided material light emission only happens on the front side.

Yes, twoside material doesn't affect emission.

> Flipping the normals swaps emitting sides.

Yes, it is the expected behavior.

> Mirroring the plane across the Y axis causes the front side to stop emitting and the back side to start emitting.

Yes, an negative scale transformation swap the reference system handiness and flips the normals (so swap the emitting side).
