### ISSUE TITLE
background image renders black

### ISSUE THREAD

**Issue by Luxcoreimage** [LuxCoreRender/LuxCore#505]
In the camera properties if i enable the background image and choose an image it does not appear, it renders black.
latest Luxcore daily - blender 2.91.2 - win10

**Comment by Dade916** [comment]
Actually, it was the Alpha channel (and any other not 3 channels AOV) to have been broken by this commit: https://github.com/LuxCoreRender/LuxCore/commit/64f799259e11ea834de6475766700631c3e12674

I should have fixed the problem.
