### ISSUE TITLE
Luxcore 2.5beta1fails to build with oidn 1.3.0

### ISSUE THREAD

**Issue by luyatshimbalanga** [LuxCoreRender/LuxCore#506]
LuxCore 2.5 beta1 built failed to properly detect Open Image Denoise 1.3.0 despite its inclusion. See the 
[build.log](https://github.com/LuxCoreRender/LuxCore/files/6047622/build.log) and 
[installed_pkgs.log](https://github.com/LuxCoreRender/LuxCore/files/6047633/installed_pkgs.log) which showed the installed dependencies.

**Comment by Dade916** [comment]
We will support OIDN v1.3.0 in next release. The only supported build method is the one available at https://github.com/LuxCoreRender/LinuxCompile.
