### ISSUE TITLE
Bad link to SLG on API web page

### ISSUE THREAD

**Issue by BrianSwift** [LuxCoreRender/LuxCore#507]
At https://luxcorerender.org/luxcore-api/ there is a link to "SLG (aka SmallLuxGPU)" http://www.luxrender.net/wiki/SLG

It looks like the previous owners of luxrender.net lost control of that domain, as it now just shows ads.

Here is a link to archived version of site https://web.archive.org/web/20180413222648/http://www.luxrender.net/wiki/SLG

**Comment by Dade916** [comment]
Thanks, fixed.
