### ISSUE TITLE
"define multiple image pipelines at the same time" link stale

### ISSUE THREAD

**Issue by BrianSwift** [LuxCoreRender/LuxCore#509]
On the wiki page https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.5#Image_pipeline
under "Image Pipeline" there is a link "define multiple image pipelines at the same time" which points to http://www.luxrender.net/forum/viewtopic.php?f=8&p=120169#p120169
which is no longer home of the old forums.

I spent some time trying to find this topic in the internet archive, but didn't have success. But maybe someone familiar with the old forums would have better luck.

**Comment by Dade916** [comment]
Thanks, I replaced the link with a brief description. You can find many examples of image pipeline usage under LuxCore "scenes" directory, for instance: https://github.com/LuxCoreRender/LuxCore/blob/55fa8de83e0ed6f018edb80417c8d4b3ab47a899/scenes/luxball/luxball-imagepipelines.cfg#L39
