### ISSUE TITLE
Random compiling of CUDA kernels

### ISSUE THREAD

**Issue by johndow16** [LuxCoreRender/LuxCore#513]
Windows 10 x64 (2004 19041.867)
Blender 2.92
GTX1660 (461.92)

LuxCore 2.5RC1 randomly compiles CUDA kernels. It happens all of sudden and out of nowhere. I was rendering frames and BAM! it started compiling CUDA kernels. I was trying different camera angles in viewport (GPU w/o denoiser) and BAM! it suddenly started compiling CUDA kernels. It happens quite often and I couldn't pinpoint the issue. Material change, camera switch, shader tweak, change in a model... Anything can trigger it.

**Comment by Theverat** [comment]
The CUDA kernels are stored in the temp directory.
What OS are you using?
Do you have some kind of script or program that deletes everything in the temp directory from time to time, like CCleaner? This could be responsible.

**Comment by johndow16** [comment]
I do have CCleaner and I use once every few days, but recompiling could happened a few times a day.

**Comment by johndow16** [comment]
**UPDATE:** After I put 'luxcorerender.org' folder in Windows temp folder on different exclusion lists, so it wouldn't be deleted during a clean up by CCleaner, Windows or any other app, the bug with random compiling of CUDA kernels has gone. At least it seems so.

**Comment by Theverat** [comment]
Then I guess we can close this issue.
