### ISSUE TITLE
lnk 2001 microsoft visual studio 2019

### ISSUE THREAD

**Issue by kamnetanker** [LuxCoreRender/LuxCore#516]
![image](https://user-images.githubusercontent.com/31188231/112061488-9c9b8280-8b6f-11eb-8b3a-f86bd20ca0a2.png)

luxcore.lib included, dll is in debug directory. CMake don't work. I made project manualy. I don't know what to do.
Pls, make instructions for use your software.

**Comment by u3dreal** [comment]
Did you look at this ?

[https://github.com/LuxCoreRender/WindowsCompile](url)

**Comment by kamnetanker** [comment]
I didn't see this link on any page of Lux, sorry. I'm closing issue
