### ISSUE TITLE
DIRECT_DIFFUSE_REFLECT not working correctly

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#517]
I created a scene that outputs the new AOVs for the "new in v2.5" page and discovered the following:

Regular combined result:

![combined](https://user-images.githubusercontent.com/1584761/112193210-f8194f00-8c07-11eb-96ae-f3bdaa8f54c0.jpg)

DIRECT_DIFFUSE_REFLECT AOV:

![direct_diffuse_reflect0001](https://user-images.githubusercontent.com/1584761/112193233-fc456c80-8c07-11eb-885d-7930b5526a1c.jpg)

This AOV looks identical to the combined result, so it looks like there's a bug here.

Steps to reproduce:
* Open the .blend file: [more_AOVs.zip](https://github.com/LuxCoreRender/LuxCore/files/6191781/more_AOVs.zip)
* Press F12 to render and wait for it to finish
* The results will be saved in the folder where the .blend is. Examine direct_diffuse_reflect0001.png.

OS: Win 10
LuxCore version: v2.5rc1

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Confirmed, thanks!
