### ISSUE TITLE
Allowing OpenCL/CUDA To Be Runtime Disabled

### ISSUE THREAD

**Issue by michaellarabel** [LuxCoreRender/LuxCore#523]
Hi,

With the recent LuxCoreRender builds having integrated OpenCL/CUDA, it appears they are used by default when available. At least from glancing through the code there doesn't appear to be the ability to explicitly say if you want to use OpenCL / CUDA / OptiX / CPU-only. Would LuxCore be open to such a patch? (Namely for benchmarking purposes in being able to compare the different options without having to rebuild LuxCore with the support disabled.) I see OptiX has a context.cuda.optix.enable property so would be useful if there were similar enable/disable properties for CUDA and OpenCL too. Thanks for any feedback or guidance if there is already this ability somewhere within the existing binaries.

**Comment by Theverat** [comment]
You can just use the CPU render engines: https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.5#Render_Engine
E.g. use PATHCPU if you want CPU-only rendering, use PATHOCL if you want additional GPU rendering.

**Comment by michaellarabel** [comment]
Thanks, I seemed to have missed that renderengine.type property.

**Comment by Dade916** [comment]
To further elaborate:

1) CPU only rendering

```
renderengine.type = PATHCPU
# Optional number of threads to use (default: max. hardware concurrency)
# 24 on my AMD 3900X is the max. hardware concurrency
native.threads.count = 24
```

2) CPU + OpenCL/CUDA:

```
renderengine.type = PATHOCL
# Optional explicit OpenCL+CUDA devices selection (0/1 to disable/enable each device avilable)
opencl.devices.select  = 00010
# Optional number of CPU threads to use (default: max. hardware concurrency)
# 0 means CPU isn't used for rendering
# 24 on my AMD 3900X is the max. hardware concurrency
opencl.native.threads.count = 24
```

PATHOCL render engine uses, by default, all and only CUDA devices available. If CUDA devices are not available, it will use all OpenCL devices.
RTX hardware acceleration is used by default on any NVIDIA RTX GPU.

Note: with NVIDIA GPUs, each hardware device is listed 2 times, one as CUDA device and one as OpenCL.

You can pass the arguments on command line if you are using luxcoreui or luxcoreconsole for rendering.
