### ISSUE TITLE
Random UV rotation in steps (new option)

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/LuxCore#528]
Right now we can randomly rotate the UV's which is great for pur randome or tileable textures, however when we have a tile texture for floors if we randomly rotate the texture we could endup with diagonal graphics in the floor, something that it's not desired.

Could be great to include a step feature, so we can say what we say right now:

- Randomly rotate from 0 to 360 degrees.

But clamp the rotation to the steps, for example:

- Randomly rotate from 0 to 360 degrees in steps of 36 degrees

This would give us 10 random rotations in a controlled angle clamping, for my tile example it would be:

- Randomly rotate from 0 to 360 degrees in steps of 90 degrees

That would give us 4 directions for each tile, like what it's done in reality, and much more control of random rotation in tiling :)

I'm not sure if this is a BlendLuxCore feature or a LuxCore feature, I'll mention both of you about this @Dade916 @Theverat :)

**Comment by Dade916** [comment]
I have added the support for a new (optional) rotation step parameter to UVRandomMapping2D and LocalRandomMapping3D:

Without step:

`scene.textures.imgtex.mapping.rotation = 0 360`

With:

`scene.textures.imgtex.mapping.rotation = 0 360 45`

**Comment by juangea** [comment]
Awesome! Thanks @Dade916 , very useful addition :)
