### ISSUE TITLE
Full crash with 2.6 and Blender 2.92

### ISSUE THREAD

**Issue by juangea** [LuxCoreRender/LuxCore#531]
I'm not sure about what's happening the bug, but it's doing a full crash on the scene, before simplifying it I had a different error, but after simplifying it it gives a full blender crash.

I'll send you @Dade916 the file through a PM in the forum since it's part of a project.

To reproduce, get the fil I will send you, open it and press F12, @Theverat thinks is a LuxCore bug more than a BlendLuxCore bug, that's why I'm sending it to you directly

**Comment by juangea** [comment]
Update: I tested with another complex scene and I got a total crash too, this is under Linux Mint 19.3

LuxCore 2.5 works perfectly fine

**Comment by Dade916** [comment]
I get a lot of warnings for a missing p4_base.blend but I'm assume it still triggers the problem.

It is a crash inside OpenImageIO while reading the first TIFF image. Actual, it is a crash replicable with any of the TIFF in this .blend.
What is really strange is that using the same TIFF in a simple scene (i.e. hand written .cfg/.scn) works fine. This puzzle me.

Looking at the debug trace of the crash, it looks similar to another problem I have patched in our version of OpenImageIO for Linux.

Can you try if the same scene works fine on Windows with v2.6 ? It should if it is the same problem.

**Comment by juangea** [comment]
Ok, I’ll test it and come back 👍

**Comment by juangea** [comment]
It does not crash on windows, it works.

**Comment by Dade916** [comment]
This confirm my hypothesis, I will look for a solution but it is actually more a OpenImageIO bug than LuxCore one.

**Comment by juangea** [comment]
Is this related to TIFF images only or it’s a general thing?
I’m asking this to find a workaround if it’s possible :)

**Comment by Dade916** [comment]
The problem you reported seems related only to TIFF files for the moment.

**Comment by Dade916** [comment]
If you convert the 4 TIFF files in your scene to PNG, it works fine here.

**Comment by juangea** [comment]
I’ll test again, I just deleted the tiff and it crashed, but may be some kind of cache I suspect, I’ll test it and report back, if that’s the workaround then we have a workaround :)

**Comment by juangea** [comment]
I can confirm it, it's a TIFF problem, I repeated the test and made sure that I had no tiff files around, and bingo, it worked fine, so that's the problem for sure, I can also confirm it from my end :)

**Comment by Theverat** [comment]
Might be related to #345

**Comment by juangea** [comment]
Totally

**Comment by Dade916** [comment]
I should have fixed this general problem with OpenImageIO and Linux GCC regular expressions (by switching to Boost regex). It was affecting many part of the OIIO code.

**Comment by juangea** [comment]
I’ll confirm this on my side, but it will probably work since you tested it also with our file :)

Awesome!
