### ISSUE TITLE
LuxCore PhotonGI missing volumetric caustics?

### ISSUE THREAD

**Issue by epileptrolytics** [LuxCoreRender/LuxCore#533]
LuxCore 2.6a with blender 2.92 on Windows PC.

There is a problem with PGI rendering reflected light beams, see also [here](https://forums.luxcorerender.org/viewtopic.php?f=3&t=3584#p30349).

![4](https://user-images.githubusercontent.com/46543531/118513642-388ed800-b734-11eb-8dfe-54b77296a0a3.jpg)

In the attached scene BiDir Metro renders a correct reference of all four parts of the beam.
Hybrid + full PGI is missing the SDS (specular - volumetric diffuse - specular) part of the beam.

When testing indirect and caustic caches separately it looks like none of them is getting any volumetrics (PGI activated for volume) in this setting.

[reflectedbeam_LuxCore.zip](https://github.com/LuxCoreRender/LuxCore/files/6494911/reflectedbeam_LuxCore.zip)

**Comment by Dade916** [comment]
I should have fixed the problem:

![fix](https://user-images.githubusercontent.com/3247881/119227989-fdfcb500-bb10-11eb-9e4b-e896d9e8eb0e.jpg)

**Comment by epileptrolytics** [comment]
> I should have fixed the problem:

Thanks for the fix, it works now!

Probably an unrelated issue, but when I switched from PathCPU to PathOCL in order to speed up the render, suddenly the indirect cache appears in the final render ??

![Screenshot](https://user-images.githubusercontent.com/46543531/119232767-b7b25080-bb26-11eb-9e39-851cce1ce3d2.jpg)

**Comment by Dade916** [comment]
It wasn't related to this issue but I should have fixed that problem too.

**Comment by epileptrolytics** [comment]
> It wasn't related to this issue but I should have fixed that problem too.

Yep, now everything works as expected, thanks again!
