### ISSUE TITLE
Luxcoreconsole ：ERROR: basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by Lorik-1728** [LuxCoreRender/LuxCore#538]
I use systemctl to start a render queue, and the queue is using the luxcoreconsole tool to do some render job.
But this happened :
![image](https://user-images.githubusercontent.com/84373240/120136306-9a574380-c204-11eb-8f26-f045e1c2e4cc.png)
By the way scene can be render in terminal normally. 
How should I deal with this problem?

**Comment by Dade916** [comment]
It looks like the error is thrown while initializing the CUDA device. You seem to have a peculiar GPU (what is a GRID T4-2Q ?). It sounds like CUDA return a NULL value when I ask for some information and I try to initialize a string with the received information.

The error is likely to be thrown while executing this constructor: https://github.com/LuxCoreRender/LuxCore/blob/1f56119081cfa0e16dfa1b13f7f1280fc21ae024/src/luxrays/devices/cudadevice.cpp#L148

Can you run the command under gdb to obtain a stack trace ?

It is very strange that the problem happen only under render queue. This may suggest some kind of configuration problem or missing right with CUDA. Can you replace "luxcorerender" with a different CUDA executable ? To check if it is a generic CUDA problem or specific of LuxCore.

**Comment by Lorik-1728** [comment]
@Dade916  Thanks for your reply. 
For some reason, I can't do some tests on this server.
The GPU is Tesla t4 and using the virtual gpu technology.
Yead, It is very strange that the problem happen only under render queue. 
I think the problem coms from the systemctl. Now i am using nohup to start the render queue instead of systemctl and it works fine!
