### ISSUE TITLE
Low resolution texture image blur problem

### ISSUE THREAD

**Issue by shadowcreeper-hash** [LuxCoreRender/LuxCore#545]
![屏幕截图 2021-07-03 015905](https://user-images.githubusercontent.com/65867725/124322952-fc63e980-dbb2-11eb-8fa8-515fbff3e1f3.png)
Figure 1 shows the node of cycle rendering. The image input node has a recent sampling algorithm, which does not blur the low-resolution map.
![屏幕截图 2021-07-03 020231](https://user-images.githubusercontent.com/65867725/124323110-52d12800-dbb3-11eb-9ba2-9fff82cc2f09.png)

But the luxcore image input node cannot turn off fuzzy sampling.

**Comment by shadowcreeper-hash** [comment]
@Dade916

**Comment by Dade916** [comment]
LuxCore supports only texture bilinear filtering while you are looking point filtering. You can find an explanation of different types of texture pixel filtering here: https://learnopengl.com/Getting-started/Textures (Texture filtering chapter, GL_NEAREST Vs GL_LINEAR).

The support of different types of interpolation has been asked a couple of times so I may add it in the under development v2.6.

**Comment by Dade916** [comment]
I have added the support for "nearest" filtering: https://forums.luxcorerender.org/viewtopic.php?f=5&t=3771

**Comment by shadowcreeper-hash** [comment]
> 我已添加了"最近"过滤的支持： https://forums.luxcorerender.org/viewtopic.php?f=5&t=3771

Thank you  😘

**Comment by shadowcreeper-hash** [comment]
> 我已添加了"最近"过滤的支持： https://forums.luxcorerender.org/viewtopic.php?f=5&t=3771
There will be one more renderer for minecraft animation in the future.😂
