### ISSUE TITLE
OpenEXR/half.h not found

### ISSUE THREAD

**Issue by kebugcheckex** [LuxCoreRender/LuxCore#551]
Run into this error during compilation
```
include/slg/imagemap/imagemap.h:22:10: fatal error: OpenEXR/half.h: No such file or directory
   22 | #include <OpenEXR/half.h>
      |          ^~~~~~~~~~~~~~~~
```
Looks like openexr removed Imath (maybe in [this commit](https://github.com/AcademySoftwareFoundation/openexr/commit/53a67aa23392023940026f493676ef2ae4fddc1d)?). I replaced all occurrences of `#include <OpenEXR/half.h>` to `#include <Imath/half.h>` and it compiles.

Environment: Arch Linux.
Issue can be reproduced when making [the AUR package](https://aur.archlinux.org/packages/luxcorerender).

**Comment by Dade916** [comment]
You need to use the procedure described here to compile LuxCore on Linux: https://github.com/LuxCoreRender/LinuxCompile

It includes all the right version of the dependencies (i.e. we don't yet support OpenEXR v3.0).
