### ISSUE TITLE
luxcorerender doesn't work in debian 10?

### ISSUE THREAD

**Issue by useranty** [LuxCoreRender/LuxCore#552]
Will latest luxcorerender be able to run on debian 10?

/LuxCore$ ./luxcoreui 
./luxcoreui: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./luxcoreui)

In my debian buster is only /lib/x86_64-linux-gnu/libm-2.28.so (glibc 2.28)

**Comment by Dade916** [comment]
It is compiled on an Ubuntu 20.04 LTS. If you can not install a newer glibc, you can try to compile Lux on your own, the procedure is relatively simple and described here: https://github.com/LuxCoreRender/LinuxCompile
