### ISSUE TITLE
code report

### ISSUE THREAD

**Issue by JackKaiXing** [LuxCoreRender/LuxCore#566]
duplicate header reference
https://github.com/LuxCoreRender/LuxCore/blob/59fada607da05c50748e0ede816c5dba0d022eab/include/slg/film/film.h#L44

https://github.com/LuxCoreRender/LuxCore/blob/59fada607da05c50748e0ede816c5dba0d022eab/include/slg/film/film.h#L42

no implementation for this function
https://github.com/LuxCoreRender/LuxCore/blob/59fada607da05c50748e0ede816c5dba0d022eab/include/slg/film/imagepipeline/imagepipeline.h#L47

**Comment by Dade916** [comment]
Thanks, I removed them.

**Comment by JackKaiXing** [comment]
Would you explain more about the difference between RADIANCE_PER_PIXEL_NORMALIZED and RADIANCE_PER_SCREEN_NORMALIZED? Why do we separate those two?

**Comment by JackKaiXing** [comment]
@Dade916  that is vert clear, thanks.

**Comment by JackKaiXing** [comment]
@Dade916 

Why is that imagePipeLine would hold `std::vector<RadianceChannelScale>` for each plugin?

https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/include/slg/film/imagepipeline/imagepipeline.h#L95

**Comment by Dade916** [comment]
It is not for each plugin but it is for each image pipeline: you can have different image pipelines with different scales. Out of a single rendering you can produce different images with different light setup (for instance, with indoor light sources turned on or off, etc.).

There is a RadianceChannelScale for each light group (i.e. std::vector<RadianceChannelScale>) and a std::vector<RadianceChannelScale> for each image pipeline.

**Comment by JackKaiXing** [comment]
@Dade916 that is very clear, thanks.
