### ISSUE TITLE
scene.camera.screenwindow seems to be ignored in orthographic cameras

### ISSUE THREAD

**Issue by sanguinariojoe** [LuxCoreRender/LuxCore#568]
You can test that in the cornell sample. Just render the default scene

`luxcoreui -o cornell.cfg -f cornell.scn`

![image](https://user-images.githubusercontent.com/1668392/141815678-617a9d8b-e507-4b8d-81ea-c08dc47f199b.png)

Then uncomment cornell.scn:15 and cornell.scn:16, and repeat

![image](https://user-images.githubusercontent.com/1668392/141815935-3b233699-98e8-4c01-a5f3-d9455da3b312.png)

No matter what you use in cornell.scn:16, you will always get the same image

**Comment by Dade916** [comment]
Actually, this is a side effect of how LuxCoreUI works, it is just overwriting the scene.scn "scene.camera.screenwindow" property to match the window size: https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/samples/luxcoreui/luxcoreapp.cpp#L339

You need to use:

`luxcoreui -D screen.tool.type IMAGE_VIEW -o cornell.cfg -f cornell.scn`

so window resizing will not affect the rendering anymore and "scene.camera.screenwindow" will not be ignored anymore.

**Comment by sanguinariojoe** [comment]
And that sir is totally accurate! :-)

Now I wonder if should BlendLuxCore set `screen.tool.type = "IMAGE_VIEW"` when exporting othographic cameras. That's anyway  a different issue

Thanks!
