### ISSUE TITLE
code report 

### ISSUE THREAD

**Issue by JackKaiXing** [LuxCoreRender/LuxCore#570]
Missing default constructor.

https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/include/slg/core/statictable.h#L75

https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/include/slg/core/statictable.h#L110

**Comment by Dade916** [comment]
As far as I remember, C++11 compilers define an empty default constructor, if one is not explicitly defined. So defining one in RegisterTableValue should be redundant.

Are you getting an error with some compiler ?

**Comment by JackKaiXing** [comment]
@Dade916  No, compiler has passed, never mind. 

Besides,  what does `imageSamplesEnabled` imply?

https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/include/slg/samplers/sampler.h#L137

**Comment by JackKaiXing** [comment]
One more question, what is the difference between those two film, the one owned by randomSampler and the one owned by randomSamplerSharedData?

https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/include/slg/samplers/random.h#L51

https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/include/slg/samplers/sampler.h#L131

**Comment by Dade916** [comment]
> @Dade916 No, compile has passed, never mind.
> 
> Besides, what does `imageSamplesEnable` imply?
> 
> https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/include/slg/samplers/sampler.h#L137

It affects the values returned for the first two elements of the sample (Sampler::GetSample(0) and Sampler::GetSample(1)). If imageSamplesEnable is true, the samples are expressed in image coordinates (i.e. pixels). Otherwise they are [0.0, 1.0] like all other values.

It is handy when you want to use a Sampler for something else than rendering an image (i.e. fire photons from light sources, etc.).

**Comment by JackKaiXing** [comment]
That is very clear, thank. One more question about the below line, what does the threshold mean and why does it compared to a random value? I can only image that it is about the radius of the sample position, why is it related to noise?

https://github.com/LuxCoreRender/LuxCore/blob/7ff6d46e4b0b7ef83c0132ff069afaf1774974da/src/slg/samplers/random.cpp#L147

**Comment by Dade916** [comment]
It is for adaptive sampling of pixels with more noise: the threshold is based on the estimated amount of noise of the pixel. I decide if to sample or skip a pixel based on the comparison between a random [0.0, 1.0] value and the noise based threshold.

I use a random value so the method is unbiased: on the long run all pixels are still sampled, just the average amount of samples per pixel is based on the estimated noise.
