### ISSUE TITLE
Caustics are not visible under refractive object (can't see trough other transparent object)

### ISSUE THREAD

**Issue by cosmical2021** [LuxCoreRender/LuxCore#574]
Caustics are not visible (when there is refractive object over caustics) unless  shader has opacity on (smaller than -1.0) or architectural glass set on.
Here is the problem/limitation/bug demonstrated with video:
https://youtu.be/n2hduvre7No
can this be solved in future?

**Comment by Dade916** [comment]
They are called SDS (Specular-Diffuse-Specular) paths and they require a very specific algorithm to be able to render them. You need to enable caustic cache to be able to see them.
