### ISSUE TITLE
shadow color for glass issue

### ISSUE THREAD

**Issue by nocivo72** [LuxCoreRender/LuxCore#576]
Hello,
I applied the shadow color white to the glass, but the ray that pass through the glass become more bright than where is not the glass.
please correct this issue.

link to the forum post:
https://forums.luxcorerender.org/viewtopic.php?f=4&t=4219

thanks

**Comment by Dade916** [comment]
Your problem is BiDir specific, Path is working fine here. I will check what is going on.

**Comment by Dade916** [comment]
I should have fixed this problem. The next automatic build will include the fix.

**Comment by nocivo72** [comment]
thanks
