### ISSUE TITLE
Question About `sampler->NextSample` in BiDirCPURenderThread::RenderFunc

### ISSUE THREAD

**Issue by JackKaiXing** [LuxCoreRender/LuxCore#579]
@Dade916 

Hello, long time no see. It took some time past to understand Eric Veach's thesis, on which I believe the implemention of `bidircpu.h` is related, also Iliyan Georgiev's technical report.

however, I am a little confused about the line below.
https://github.com/LuxCoreRender/LuxCore/blob/7ce21392d2f7b674ce9ae105abc1e0711ca862c4/src/slg/engines/bidircpu/bidircputhread.cpp#L973

Why do we need to do this work, even through when `validLightPath=false`.
https://github.com/LuxCoreRender/LuxCore/blob/7ce21392d2f7b674ce9ae105abc1e0711ca862c4/src/slg/engines/bidircpu/bidircputhread.cpp#L785

**Comment by Dade916** [comment]
It is required by some type of Sampler, to close the loop: for instance, Metropolis needs to know if the sample has been of any "use" or not.

P.S. LuxCore BiDir is based on Georgiev's https://github.com/SmallVCM/SmallVCM
