### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#58]
Since recently (don't know which commit exactly) I can't compile anymore.
The errors I'm getting are:
```
[ 66%] Built target slg-film
Scanning dependencies of target benchsimple
[ 66%] Building CXX object tests/benchsimple/CMakeFiles/benchsimple.dir/benchsimple.cpp.o
[ 66%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/bidircpu/bidircpurenderstate.cpp.o
[ 66%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/bidirvmcpu/bidirvmcpu.cpp.o
[ 66%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/bidirvmcpu/bidirvmcputhread.cpp.o
[ 66%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/bidirvmcpu/hashgrid.cpp.o
[ 67%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/compiledscene.cpp.o
[ 67%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/compilecamera.cpp.o
[ 67%] Linking CXX executable ../../bin/benchsimple
[ 67%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/compilegeometry.cpp.o
[ 67%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/compileimagemaps.cpp.o
[ 67%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/compilelights.cpp.o
[ 67%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/compilematerials.cpp.o
[ 68%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/compilesceneobjects.cpp.o
[ 68%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/compiletextures.cpp.o
[ 68%] Building CXX object src/slg/CMakeFiles/slg-core.dir/engines/pathoclbase/pathoclbase.cpp.o
/home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore/../target-64-sse2/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'
/home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore/../target-64-sse2/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_initialize()'
/home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore/../target-64-sse2/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_current_slot()'
/home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore/../target-64-sse2/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const'
/home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore/../target-64-sse2/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_terminate()'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/benchsimple] Error 1
make[1]: *** [tests/benchsimple/CMakeFiles/benchsimple.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
I have tried with copy of the LinuxCompile folder and a fresh clone of LuxCore, but the error remains the same. 

I went back to commit 71696593a30dd0ccf81caf583107e31da5cd765f and compilation works there.

**Comment by Dade916** [comment]
You have multiple version of the Intel TBB library installed and cmake is picking the wrong version (the old one installed in your system and not the one included in Embree). I'm pretty sure to have fixed this problem so you may have an old CMakeCache.txt file in LuxCore directory. Edit the file and look for the "tbb" string, check if the path is right (pointing to the same place of where Embree library is) or not.

Check to have updated everything (not only LuxCore but also LinuxCompile) and than delete the CMakeCache.txt file and the LinxuCompile/target-something directory and re-try, it should work.

**Comment by Theverat** [comment]
> Edit the file and look for the "tbb" string, check if the path is right (pointing to the same place of where Embree library is) or not.

The path was wrong as you said, but deleting the CMakeCache.txt and re-building from scratch did not help.
Also, it's now complaining that it can't find boost anymore for whatever reason, so I'm now trying a completely new LinuxCompile and LuxCore clone, re-downloading the depencencies etc. from scratch.

By the way, it seems like Qt compiled as singlethread (also I don't think we use it currently?).

The 5 seconds sleeps in the build script are also getting on my nerves, forgot to change SLEEP to 0 after the fresh clone.

**Comment by Dade916** [comment]
Qt is still used to compile LuxMark (the last optional stage of LinuxCompile). Yes, Qt is compiled in single thread but I assume it was always like this (but I'm not sure, I can not remember).

The sleeps were introduced at some point by SATtva as a work-around to some obscure race condition I have never experienced. I feel they are useless now but I wouldn't bet on that.

**Comment by Theverat** [comment]
A completely fresh clone did not help either.

After manually editing the CMakeCache.txt file it works now, but this should not be necessary, right?
Something in the discovery process of libtbb does not work and it looks in the wrong places.

**Comment by Dade916** [comment]
Tested from scratch and it is still working fine here, It has also always worked fine on Trevis-CI. What cmake version do you have ? cmake version 3.5.1 here.

**Comment by Theverat** [comment]
I also have 3.5.1

**Comment by Dade916** [comment]
Try to git-pull the latest LinuxCompile repository, delete CMakeCache.txt and retry. I'm now forcing the Embree search path.

**Comment by Theverat** [comment]
Thanks, looks like it works out of the box now.

(I just realize I should have opened this issue in the LinuxCompile repo)
