### ISSUE TITLE
Can't get SAMPLECOUNT from Python

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#62]
When I try to get the new SAMPLECOUNT AOV from Python, I get this error:
`RuntimeError: Unknown film output type in Film::GetOutput<float>(): 28`

I compiled the latest sources.

I'm defining it like this:
```python
film.outputs.1.type = SAMPLECOUNT
film.outputs.1.filename = samplecount.png
```
And I try to get it like this:
```python
session.GetFilm().GetOutputFloat(pyluxcore.FilmOutputType.SAMPLECOUNT, channel_buffer)
```

Is there anything I'm missing?

**Comment by Dade916** [comment]
I'm on the mobile but it should be an int aov not float so you need to call GetOuputInt or something like that.

**Comment by Theverat** [comment]
Thanks, that was it.
I needed to use `GetOutputUInt`.
