### ISSUE TITLE
Crash when camera near and far clipping planes are exactly equal

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#64]
Testscene:
[00001.zip](https://github.com/LuxCoreRender/LuxCore/files/1732453/00001.zip)

To reproduce in any scene, just set the following props to the same values:
```
scene.camera.cliphither = 10
scene.camera.clipyon = 10
```

**Comment by Theverat** [comment]
I think I got it, it's in src/luxrays/core/geometry/transform.cpp

When n == f then n / f == 1 and then 1 - 1 == 0 and then we have a division by zero.
```
Transform Perspective(float fov, float n, float f) {
	// Perform projective divide
	const float inv_denom = 1.f / (1.f - n / f);
```

**Comment by Dade916** [comment]
Added a workaround.

**Comment by Theverat** [comment]
Thanks, can confirm it's fixed.
