### ISSUE TITLE
LuxCore crashes with SIGFPE if film width or height is zero

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#65]
Crash with SIGFPE (floating point exception).
Example scene (start with luxcoreconsole, luxcoreui adjusts the film size before the crash can happen):
[00001.zip](https://github.com/LuxCoreRender/LuxCore/files/1734548/00001.zip)

I think LuxCore should throw a runtimeerror if either width or height are zero.

edit: it also crashes with filmsize 1x1. Only 2x2 and higher are safe.

**Comment by Dade916** [comment]
Both luxcoreui and luxconsole work fine with 1x1 film,  are you sure the problem with 1x1 isn't elsewhere ?

**Comment by Theverat** [comment]
I think it might be OpenGL's fault.
So it's a BlendLuxCore issue. I just make sure size is never smaller than 2x2.
