### ISSUE TITLE
LuxCore crashes when Film::GetOutput is called with invalid index

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#66]
Example:

```python
# Note: there are less than 100 imagepipelines defined
film.GetOutputFloat(RGB_IMAGEPIPELINE, buffer, 99)
```

I think it should throw a runtime error.
By the way I found no way to check if a given index of an output exists, is this possible?

**Comment by Dade916** [comment]
I have added some check an now Python has 2 new Film methods:

bool HasOutput(filmType)
int GetOutputCount(filmType)

to check if an output is available and the index valid range (index < GetOutputCount(filmType)).

**Comment by Theverat** [comment]
Thanks, can confirm the crash is gone, too.
