### ISSUE TITLE
shadow color is inconsistent using bidirectional and path

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/LuxCore#68]
Under same settings and same light, 
Path:
![path](https://user-images.githubusercontent.com/8104251/37279616-3e70227a-263b-11e8-8f88-eea948d5c4f4.png)
Bidi:
![bidi](https://user-images.githubusercontent.com/8104251/37279631-4496baa6-263b-11e8-91d9-472896a72617.png)
Cycles:
![cycles](https://user-images.githubusercontent.com/8104251/37279646-4aaaa5d8-263b-11e8-83ad-b09a6f56277e.png)
Prorender
![prorender](https://user-images.githubusercontent.com/8104251/37279807-c802cb5a-263b-11e8-81a0-5e1d513dde3c.png)

**Comment by Dade916** [comment]
Please, always post the scene to reproduce the problem. It can be attached to the post (https://help.github.com/articles/file-attachments-on-issues-and-pull-requests).

**Comment by frankyifei** [comment]
[test light.zip](https://github.com/LuxCoreRender/LuxCore/files/1802762/test.light.zip)

**Comment by Dade916** [comment]
The scene has 2 light sources: a point light and a constantinfinite light. PATHCPU and BIDIRCPU produce exactly the same output when using only the point light or the constantinfinite light. There is a problem only when using both.

This seems to suggest a bug in PDF light strategy. Checking.

**Comment by frankyifei** [comment]
tried latest patched version, still darker than bidi's

**Comment by Dade916** [comment]
Yes, I have not yet finished =)

**Comment by Dade916** [comment]
Ok, I should have now fixed the problem.

PATHCPU:

![p1](https://user-images.githubusercontent.com/3247881/37392171-b62506a4-276d-11e8-8ef5-c8394dfa5d95.png)

BIDIRCPU:

![b1](https://user-images.githubusercontent.com/3247881/37392191-bfd86998-276d-11e8-8987-086577a10d3e.png)

**Comment by Dade916** [comment]
Ok, now, I should have fixed all cases.

**Comment by frankyifei** [comment]
yeah, great! I'll close this one.
