### ISSUE TITLE
session.HasDone() does not work with batch.halttime and batch.haltspp and TILEPATH

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#70]
When `batch.halttime` or `batch.haltspp` are set and the engine is TILEPATH, the `session.HasDone()` method never returns `True`.
The rendering actually stops though.

**Comment by Dade916** [comment]
It is working fine here with:

`~/projects/luxcorerender/LuxCore/bin/luxcoreconsole -D renderengine.type TILEPATHCPU -D sampler.type TILEPATHSAMPLER -D batch.halttime 5 scenes/luxball/luxball-hdr.cfg`

LuxCoreConsole exits at the end and it uses HasDone(): https://github.com/LuxCoreRender/LuxCore/blob/a8b33b2df22ef9a0c760047f419016f0b56b45e6/samples/luxcoreconsole/luxcoreconsole.cpp#L54

There must be something different in your test (?)

**Comment by Theverat** [comment]
My configuration:
```
tile.multipass.convergencetest.threshold.reduction = 0.5
renderengine.type = "TILEPATHCPU"
sampler.type = "TILEPATHSAMPLER"
batch.halttime = 2
batch.haltthreshold.stoprendering.enable = 0
tile.multipass.enable = 1
tilepath.sampling.aa.size = 3
path.pathdepth.total = 7
path.pathdepth.specular = 6
tile.multipass.convergencetest.threshold = 0.0234375
batch.haltthreshold = 0.0001
film.height = 540
path.pathdepth.glossy = 5
path.pathdepth.diffuse = 5
tile.size = 64
```
This happens when I render:
```
Session created in 0.2s
[LuxCore][30.296] Tiles initialization time: 0.06 secs
[LuxCore][32.243] Time 100%, rendering done.
[LuxCore][32.853] Rendering time: 2.56 secs
engine.session.HasDone(): False
engine.session.HasDone(): False
engine.session.HasDone(): False
engine.session.HasDone(): False
```

But I noticed that sometimes (maybe 1 of 5 times I start a render) it works as expected and HadDone() returns True.

**Comment by Dade916** [comment]
It is likely to be the TILEPATH convergence test:

`tile.multipass.convergencetest.threshold = 0.0234375`

It overwrites the HasDone() value until it has done. You can not mix Film halt conditions (batch.*) and TILEPATH halt conditions at the moment. I can check if I can easily support both at the same time.

**Comment by Theverat** [comment]
Ok, I thought if one of the halt conditions is true, HasDone() returns True.

Also, it seems like HasDone() returns True exactly one time and if you call it again after that, it returns False again.

**Comment by Dade916** [comment]
I think it is just a race condition between Film halt conditions (setting true) and TILPATH (setting false) but I have to check the code.

**Comment by Dade916** [comment]
I should have fixed the problem. It was in boost::timed_join(). It returns true only the first time than false even if the thread has done. It is also deprecated so changed the implementation.

**Comment by Theverat** [comment]
Confirmed.
