### ISSUE TITLE
Crash when parsing imagepipeline

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#72]
The following code crashes:
```python
            try:
                print(">>>>>>>>>>>")
                print(self.imagepipeline_cache.props)
                print(">>>>>>>>>>>")

                session.Parse(self.imagepipeline_cache.props)
            except Exception as error:
                print(error)
```

Console output:
```
view_update
Update because of: CAMERA | IMAGEPIPELINE | REQUIRES_SCENE_EDIT | REQUIRES_SESSION_PARSE
[SDL][6.111] Camera type: perspective
[SDL][6.111] Camera position: Point[0, -0.783292, 0]
[SDL][6.111] Camera target: Point[0, -0.683292, 4.37114e-09]
[SDL][6.111] Camera clipping plane disabled
>>>>>>>>>>>
film.imagepipelines.0.1.type = "TONEMAP_LINEAR"
film.imagepipelines.0.0.type = "NOP"
film.imagepipelines.0.1.scale = 0.060499999672174454

>>>>>>>>>>>
[SDL][6.121] Image pipeline: film.imagepipelines.0
[SDL][6.121] Image pipeline step 0: NOP
[SDL][6.121] Image pipeline step 1: TONEMAP_LINEAR
Writing: /tmp/blender.crash.txt
fish: Job 1, './programs/blender-2.79a-linux-glibc219-x86_64/blender' durch Signal SIGSEGV (Adressbereichsfehler) beendet
```

The same code worked previously, I suspect it breaks due to the [recent changes to radiance groups/imagepipelines](https://forums.luxcorerender.org/viewtopic.php?f=5&t=177&p=2292#p2285).
Am I using the new code wrong or is this a regression in LuxCore?

**Comment by Dade916** [comment]
Running:

```
				app->session->BeginSceneEdit();
				app->config->GetScene().Parse(Properties().SetFromString(
					"film.imagepipelines.0.0.type = NOP\n"
					"film.imagepipelines.0.1.type = TONEMAP_LINEAR\n"
					"film.imagepipelines.0.1.scale = 10.060499999672174454\n"));
				app->session->EndSceneEdit();
```
works fine here, how can I reproduce the problem ? It is likely to happen because some additional condition like having light groups defined, etc.

**Comment by Dade916** [comment]
I did the cut&paste of the wrong code, wtf.

**Comment by Dade916** [comment]
Ok, now it is crashing here too. Good.

**Comment by Dade916** [comment]
Ok, I should have fixed the problem.

**Comment by Theverat** [comment]
Confirmed, thanks for the quick fix.

**Comment by Theverat** [comment]
I found another crash, probably related to these changes.

It happens when I change a radiancescale setting during final render (during viewport render the same code works).
Python code (basically the same as before):
```python
print("----------")
print(self.imagepipeline_cache.props)
print("----------")
session.Parse(self.imagepipeline_cache.props)
```

Console:
```
Session created in 0.2s
----------
film.imagepipelines.0.radiancescales.1.globalscale = 1
film.imagepipelines.0.radiancescales.0.globalscale = 1
film.imagepipelines.0.radiancescales.2.enabled = 1
film.imagepipelines.0.radiancescales.0.enabled = 1
film.imagepipelines.0.radiancescales.2.rgbscale = 1 1 1
film.imagepipelines.0.0.type = "NOP"
film.imagepipelines.0.radiancescales.1.enabled = 0
film.imagepipelines.0.1.scale = 0.00050000002374872565
film.imagepipelines.0.radiancescales.2.globalscale = 1
film.imagepipelines.0.radiancescales.1.rgbscale = 1 1 1
film.imagepipelines.0.1.type = "TONEMAP_LINEAR"
----------
[SDL][9.171] Image pipeline: film.imagepipelines.0
[SDL][9.171] Image pipeline step 0: NOP
[SDL][9.171] Image pipeline step 1: TONEMAP_LINEAR
pure virtual method called
terminate called without an active exception
fish: Job 1, './programs/blender-2.79a-linux-glibc219-x86_64/blender' durch Signal SIGABRT (Abort) beendet
```

**Comment by Dade916** [comment]
This time it really works fine here (in C++ and Python). The message "pure virtual method called" is a strange error and can happen only in a very specific situation. How can I reproduce the problem here ?

**Comment by Theverat** [comment]
If you have a clone of the BlendLuxCore repo, you can checkout the [tonemapped_aovs](https://github.com/LuxCoreRender/BlendLuxCore/tree/tonemapped_aovs) branch of BlendLuxCore, start a final render and disable the default light group (it is in the scene tab).

Tell me if that's too much trouble, then I will think of a small Python script to reproduce the error tomorrow.

![scrn_2018-03-19_23-59-38](https://user-images.githubusercontent.com/1584761/37626852-f9d498a2-2bd1-11e8-979a-23f0f11f8619.png)

**Comment by Dade916** [comment]
Effffff, I wasn't looking at what you were trying to achieve: the SDL fragment you pass is deleting all old image pipelines and defining only a single new one. Instead you want to redefine just a single one.  Than you are asking for the output of an image pipeline doesn't exist anymore (the #1, while only the #0 is now defined) and boom !

The current behavior is common in LuxCore, old definition (of all pipelines) is deleted and the new one is used. This happen because "film.imagepipelines." is considered the root of the object (i.e. the object is the set of pipelines, not the single one).

Note: the above behavior is required because otherwise you have no way to delete the existing image pipelines.

I could change this behavior to consider "film.imagepipelines.#." the root of the object so the object is the single pipeline and not the set (I like this). But I would have to add a method to explicitly delete pipelines (and I don't like this). Do you prefer the current behavior or the "single pipeline" behavior ?

**Comment by Theverat** [comment]
Looking at my code it would make my life a lot easier if "film.imagepipelines.#." was the root of the object.

However, in any case LuxCore should not crash when asking for the output of a non-existing imagepipeline.

**Comment by Dade916** [comment]
> However, in any case LuxCore should not crash when asking for the output of a non-existing imagepipeline.

No, it is common to any C/C++ API to have an undefined behavior (i.e.  crash) when using parameters out of their intended range.
This behavior is intrinsic to the very core of the languages: for instance, if you use an out of bound index array, the program will crash, it will not through an exception or print an error. It is the same for any C/C++ API.

Going to change "film.imagepipelines.#." as the root of the object.

**Comment by Dade916** [comment]
It is now possible to replace a single image pipeline and the BlendLuxCore test works fine now.

**Comment by Theverat** [comment]
Thank you.
I am stupid by the way: I will need to update all the AOV imagepipelines anyway, otherwise they don't match the combined tonemapping anymore when it is adjusted... 
But the new behaviour is probably a bit more intuitive for developers. And I can publish the lightgroup implementation now and can do the update of the AOV pipelines at a later time.
I have the feeling that my new code in this direction is a huge mess and needs a rework anyway :/
