### ISSUE TITLE
Material emission "importance" property in wrong group?

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#77]
Hi,

The material emission importance property does not use the "emission." prefix - is this intended?
https://github.com/LuxCoreRender/LuxCore/blob/master/src/slg/scene/parsematerials.cpp#L439
```
# So you have to use this:
scene.materials.test.importance = 2
# Instead of (more logical?)
scene.materials.test.emission.importance = 2
```
Since the other light emission related properties are grouped there, I would have expected it.

**Comment by Dade916** [comment]
It is probably the result of a cut&paste from light sources properties (where there is no ".emission" prefix). 

Anyway, I renamed the material ".importance"  property to  ".emission.importance".

**Comment by Theverat** [comment]
Thanks.
