### ISSUE TITLE
Camerainvisible objects not invisible to BIDIR/LIGHTCPU

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#95]
Camerainvisible objects are not invisible to the light paths of Bidir (and I assume LIGHTCPU as well).
Not sure if this can be solved.

Bidir:

![bidir](https://user-images.githubusercontent.com/1584761/38822108-be768b6c-41a2-11e8-9d34-e3ce07ec31bb.jpg)

Path:

![path](https://user-images.githubusercontent.com/1584761/38822109-be8f615a-41a2-11e8-8a70-ecb30e5843cf.jpg)

[bidir_invisible_to_cam.zip](https://github.com/LuxCoreRender/LuxCore/files/1916244/bidir_invisible_to_cam.zip)

**Comment by Dade916** [comment]
I should have fixed the problem.
