### ISSUE TITLE
I'm having a problem with cmake's boost library at the time of generating the project

### ISSUE THREAD

**Issue by nathanmiguel123** [LuxCoreRender/LuxCore#97]
This is my problem in cmake

![sem titulo](https://user-images.githubusercontent.com/29849613/39400054-473467c0-4aff-11e8-95ee-deb296d0cba8.png)

**Comment by Dade916** [comment]
You should use the procedure described here: https://github.com/LuxCoreRender/WindowsCompile/blob/master/README.txt

The .bat scripts will takes care to run the cmake for you with the appropriate parameters.
