### ISSUE TITLE
Problem with openexr library in cmake

### ISSUE THREAD

**Issue by nathanmiguel123** [LuxCoreRender/LuxCore#99]
I'm having a problem trying to find certain library to generate the visual studio solution. I have cloned the 3 repositories (luxrender, windowscompiling and deps) and already tried to direct to the directory, but without success.

![sem titulo](https://user-images.githubusercontent.com/29849613/39677116-2eed0ffc-514c-11e8-8297-00fa55bb4d74.png)

**Comment by Dade916** [comment]
Have you followed my suggestion in your previous #97 issue ?

**Comment by nathanmiguel123** [comment]
@Dade916 yes, all pass

**Comment by Dade916** [comment]
Ok, so does the .\cmake-build-x64.bat work and end without errors ?

Once you have run the script, you can open with VisualStudio the project created inside the directory WindowsCompile/Build_CMake/LuxCore

**Comment by nathanmiguel123** [comment]
@Dade916 Yes without errors, my problem more specifically is that it does not find open exr .lib, and even directing it to windows compiling deps where the includes is not resolvable.

**Comment by Dade916** [comment]
You mean you are loading the VisualStudio project inside WindowsCompile/Build_CMake/LuxCore and if you try to compile from inside VS you get an error about missing openexr .lib while if you run .\cmake-build-x64.bat everything compiles and links fine ? It is very strange.

Are you using the Git tag "luxcorerender_v2.0" ? During the last 2 days we are switching from VisualStudio 2013 to VisualStudio 2017 so if you are using the very latest sources you are likely to get an error. But the "luxcorerender_v2.0" tag (on all 3 git repositories) is working fine.

**Comment by nathanmiguel123** [comment]
@Dade916 good correcting my answer about build-deps-x64 error, it is giving error that does not find msbuild, and I'm using visual studio 2017. cmake has the same error with cmake, but I think if I solve this should work . already the branch I'm using the master, later I test the 2.0 branch because now I'm out of time. But if I can help with this msbuild error for now.

![sem titulo](https://user-images.githubusercontent.com/29849613/39782476-b7cffcce-52e8-11e8-97d2-f73bcbcc7e9b.png)

**Comment by Dade916** [comment]
Uh, nope, you don't need to run  build-deps-x64.bat. It is required only for developer in order to update the WindowsDeps repository. Just run the cmake-build-x64.bat as described here: https://github.com/LuxCoreRender/WindowsCompile/blob/luxcorerender_v2.0/README.txt 

You need also to use VS2013, as I wrote before, we are working on VS2017 support. You need to checkout the v2.0 tag and to follow the instruction of README.txt.

If you want to use VS2017, you have to wait, we are working on that right now.

**Comment by nathanmiguel123** [comment]
Well, I'll have to wait because you're connected in this vsual studio. Thank you for your support

**Comment by Dade916** [comment]
The VS2017 support now works fine.
